apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aggregator.fullname" . }}
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
data:
{{- range $envKey, $envVal := .Values.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
{{- end }}
