apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "aggregator.fullname" . }}-pg
  labels: {{- include "aggregator.labels" . | nindent 4 }}
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0

  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: aggregator

  storage:
    size: 40Gi

  resources:
    limits:
      cpu: 8000m
      memory: 16Gi
    requests:
      cpu: 200m
      memory: 8Gi

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: {{ .Values.postgres.backup.destinationPath | quote }}
      endpointURL: {{ .Values.postgres.backup.endpointURL | quote }}
      s3Credentials:
        accessKeyId:
          name: {{ include "aggregator.fullname" . }}
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: {{ include "aggregator.fullname" . }}
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2

  postgresql:
    parameters:
      # DB Version: 17
      # OS Type: linux
      # DB Type: dw
      # Total Memory (RAM): 8 GB
      # CPUs num: 8
      # Connections num: 100
      # Data Storage: hdd

      max_connections: "100"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "1GB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "500"
      random_page_cost: "4"
      effective_io_concurrency: "2"
      work_mem: "16MB"
      huge_pages: "off"
      min_wal_size: "4GB"
      max_wal_size: "16GB"
      max_worker_processes: "8"
      max_parallel_workers_per_gather: "4"
      max_parallel_workers: "8"
      max_parallel_maintenance_workers: "4"
