kind: pipeline
type: kubernetes
name: test

metadata:
  annotations:
    injector.tumblr.com/request: "drone-cache"

services:
  - name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: data_aggregator_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

steps:
  - &drone_cache
    name: restore-cache
    image: meltwater/drone-cache
    settings:
      restore: true
      cache_key: 'cache-{{ arch }}-{{ os }}-{{ checksum "mix.lock" }}'
      mount: ["_build", "deps"]

  - name: test
    image: hexpm/elixir:1.15.4-erlang-25.3.2.5-debian-buster-20230612-slim
    environment:
      MIX_ENV: test
    commands:
      - apt-get update
      - apt-get install build-essential -y
      - mix local.rebar --force
      - mix local.hex --force
      - mix deps.get
      - mix deps.compile
      - mix compile --warnings-as-errors --force
      - mix deps.clean --unused
      - mix lint
      - mix test

  - <<: *drone_cache
    name: rebuild-cache
    settings:
      restore: false
      rebuild: true

---
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [push]
  branch: [main]

steps:
  - &docker
    name: builder
    image: plugins/docker
    settings:
      registry: quay.io
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      repo: quay.io/zebbra/data_aggregator
      target: builder
      tags: builder
      mtu: 1300
      cache_from:
        - quay.io/zebbra/data_aggregator:builder

  - <<: *docker
    name: release
    settings:
      target: null
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
# ---
# kind: pipeline
# type: kubernetes
# name: deploy

# depends_on:
#   - test
#   - build

# trigger:
#   event: [push]
#   branch: [main]

# steps:
#   - name: helm
#     image: pelotech/drone-helm3
#     settings:
#       kube_api_server: https://kubernetes.default
#       kube_token: { from_secret: kubernetes_token }
#       kube_certificate: { from_secret: kubernetes_certificate }
#       chart: ./deploy/charts/data_aggregator
#       release: data_aggregator
#       namespace: medi
#       values_files: [./deploy/production.yaml]
#       values: image.tag=git-${DRONE_COMMIT_SHA:0:7}

#   - name: sentry
#     image: sierrasoftworks/drone-sentry
#     settings:
#       server: https://sentry.zebbra.ch
#       organization: zebbra
#       project: data_aggregator
#       token: { from_secret: sentry_token }
#       release: true
#       release_version: "${DRONE_COMMIT_SHA}"
#       release_url: "${DRONE_COMMIT_LINK}"
#       deploy: true
#       deploy_environment: "prod"
#       deploy_name: "Deploying ${DRONE_COMMIT_SHA:0:7} to production"
#       deploy_url: "https://data-aggregator.zebbra.ch"
