
Table collections {
  id uuid [pk]
  name varchar
  code varchar
  description varchar
  owner varchar
  collection_type varchar
  digitization_status varchar
  collection_size integer
  inserted_at timestamp
  updated_at timestamp
  institution_id uuid
}

Table import_change_events {
  id uuid [pk]
  inserted_at timestamp
  updated_at timestamp
  import_record_id uuid
  change_event_id uuid
}

Table import_files {
  id uuid [pk]
  url varchar
  meta_data jsonb
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
}

Table import_records {
  id uuid [pk]
  unique_qualifier varchar
  import_data jsonb
  meta_data jsonb
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
}

Table institutions {
  id uuid [pk]
  name varchar
  address varchar
  zip_code varchar
  city varchar
  country varchar
  mail varchar
  tel varchar
  contact_person varchar
  inserted_at timestamp
  updated_at timestamp
}

Table static_assets {
  id uuid [pk]
  url varchar
  meta_data jsonb
  inserted_at timestamp
  updated_at timestamp
  import_record_id uuid
}

Table attribute_resolving_strategies {
  id uuid [pk]
  do_not_encode boolean
  inserted_at timestamp
  updated_at timestamp
  catalog_id uuid
  dwc_attribute_id uuid
  collection_id uuid
}

Table catalogs {
  id uuid [pk]
  name varchar
  description varchar
  url varchar
  version integer
  inserted_at timestamp
  updated_at timestamp
}

Table dwc_attributes {
  id uuid [pk]
  name varchar
  inserted_at timestamp
  updated_at timestamp
  default_catalog_id uuid
}

Table records {
  id uuid [pk]
  unique_qualifier varchar
  meta_data jsonb
  inserted_at timestamp
  updated_at timestamp
  import_record_id uuid
}

Table annotations {
  id uuid [pk]
  comment varchar
  state varchar
  value_suggestion varchar
  user varchar
  dwc_attribute_id uuid
  inserted_at timestamp
  updated_at timestamp
  record_id uuid
}

Table change_events {
  id uuid [pk]
  category varchar
  value varchar
  previous_value varchar
  catalog_value_reference varchar
  inserted_at timestamp
  updated_at timestamp
  dwc_attribute_id uuid
  run_id uuid
}

Table encoding_change_events {
  id uuid [pk]
  catalog_value_reference varchar
  inserted_at timestamp
  updated_at timestamp
  change_event_id uuid
  catalog_id uuid
  record_id uuid
}

Table runs {
  id uuid [pk]
  comment varchar
  state varchar
  value_suggestion varchar
  user varchar
  inserted_at timestamp
  updated_at timestamp
}

Table schema_migrations {
  version integer
  inserted_at timestamp
}

Ref: catalogs.id < attribute_resolving_strategies.catalog_id
Ref: catalogs.id < dwc_attributes.default_catalog_id
Ref: catalogs.id < encoding_change_events.catalog_id
Ref: change_events.id < encoding_change_events.change_event_id
Ref: change_events.id < import_change_events.change_event_id
Ref: collections.id < attribute_resolving_strategies.collection_id
Ref: collections.id < import_files.collection_id
Ref: collections.id < import_records.collection_id
Ref: dwc_attributes.id < annotations.dwc_attribute_id
Ref: dwc_attributes.id < attribute_resolving_strategies.dwc_attribute_id
Ref: dwc_attributes.id < change_events.dwc_attribute_id
Ref: import_records.id < import_change_events.import_record_id
Ref: import_records.id - records.import_record_id
Ref: import_records.id < static_assets.import_record_id
Ref: institutions.id < collections.institution_id
Ref: records.id < annotations.record_id
Ref: records.id < encoding_change_events.record_id
Ref: runs.id < change_events.run_id
