apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aggregator.fullname" . }}-migrate
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.jobAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  activeDeadlineSeconds: 43200
  template:
    metadata:
      name: {{ include "aggregator.fullname" . }}-migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aggregator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
            - configMapRef:
                name: {{ include "aggregator.fullname" . }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ include "aggregator.fullname" . }}-pg-app"
                  key: uri
          command:
            - /bin/sh
          args:
            - -c
            - "/app/bin/migrate"
        - name: catalog-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
            - configMapRef:
                name: {{ include "aggregator.fullname" . }}
          command:
            - /bin/sh
          args:
            - -c
            - "/app/bin/catalog_init"
