apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aggregator.fullname" . }}-migrate
  labels:
    {{- include "aggregator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: {{ include "aggregator.fullname" . }}-migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aggregator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
            - configMapRef:
                name: {{ include "aggregator.fullname" . }}
          command:
            - /bin/sh
          args:
            - -c
            - "/app/bin/migrate"
        - name: catalog-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.envSecret }}
            - configMapRef:
                name: {{ include "aggregator.fullname" . }}
          command:
            - /bin/sh
          args:
            - -c
            - "/app/bin/catalog_init"
