defmodule Mix.Tasks.DataAggregator.Records.Generate do
  @default_count 100

  @moduledoc """
  Generates a number of records and dumps them to stdout as CSV.

  By default it will generate #{@default_count} records, but you can pass a number as an argument to generate more.

  ## Options

  * `--count` - The number of records to generate (default: #{@default_count})

  ## Examples

  ```shell
  mix data_aggregator.records.generate --count 1000 > test/support/fixtures/files/dataset-1k.csv
  mix data_aggregator.records.generate --count 10000 > test/support/fixtures/files/dataset-10k.csv
  mix data_aggregator.records.generate --count 100000 > test/support/fixtures/files/dataset-100k.csv
  mix data_aggregator.records.generate --count 1000000 > test/support/fixtures/files/dataset-1m.csv
  ```

  """
  use Mix.Task

  @switches [count: :integer]

  def run(args) do
    {opts, _, _} = OptionParser.parse(args, switches: @switches)
    count = opts[:count] || @default_count

    count
    |> generate_records()
    |> CSV.encode(headers: true)
    |> Stream.into(IO.stream())
    |> Stream.run()
  end

  defp generate_records(count) do
    Stream.map(1..count, &generate_record(&1))
  end

  defp generate_record(index) do
    %{
      "Numéro scientifique GBIF" => "GEN.#{index}",
      "Scientific Name" => "Recordus Examplaris #{index}",
      "Age" => "",
      "Auteur et date ssp" => "Wagler, 1831",
      "Autres numéros" => "",
      "Collecteur" => "Dr Gosse",
      "DAYCOLLECTED" => "",
      "ENDOFPERIODDAY" => "",
      "ENDOFPERIODMONTH" => "",
      "ENDOFPERIODYEAR" => "",
      "Espèce" => "tridactylus",
      "Famille" => "Bradypodidae",
      "Genre" => "Bradypus",
      "LatitudeDecimale" => "-13",
      "Localité" => "Amérique du Sud",
      "LongitudeDecimale" => "-59",
      "MONTHCOLLECTED" => "",
      "Ordre" => "Pilosa",
      "Parties" => "Peau+crâne",
      "Pays" => "",
      "PrecisionGEO" => "2 pays seulement",
      "Province" => "",
      "Remarques" => "This is an example record generated by `mix data_aggregator.gen.records`",
      "Sexe" => "F.",
      "Sous espèce" => "cuculliger",
      "Station" => "",
      "YEARCOLLECTED" => ""
    }
  end
end
