import Config

# Configure your database
database_url = "ecto://postgres:postgres@localhost:5432/data-aggregator-dev"

config :data_aggregator, DataAggregator.Repo,
  url: System.get_env("DATABASE_URL") || database_url,
  pool_size: 20,
  queue_target: 100,
  log: false,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  timeout: 10 * 60 * 1000

# backoff_max: 120_000,
# ownership_timeout: 60_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :data_aggregator, DataAggregatorWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "rs4+NR9FM90SkkrmYTJDIn0wK0Cac6qKzU82uKfNirNVIvYjdulbQ7lIUvIx2S4m",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:data_aggregator, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:data_aggregator, ~w(--watch)]},
    storybook: {Tailwind, :install_and_run, [:storybook, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :data_aggregator, DataAggregatorWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/data_aggregator_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"storybook/.*(exs)$"
    ]
  ]

# Configure esbuild (the version is required)
config :esbuild,
  version: "0.20.1",
  data_aggregator: [
    args:
      ~w(js/app.ts js/storybook.ts --bundle --target=es2017 --outdir=../priv/static/assets --external:/fonts/* --external:/images/*),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

# Configure tailwind (the version is required)
config :tailwind,
  version: "3.4.1",
  data_aggregator: [
    args: ~w(
      --config=tailwind.config.js
      --input=css/app.css
      --output=../priv/static/assets/app.css
    ),
    cd: Path.expand("../assets", __DIR__)
  ],
  storybook: [
    args: ~w(
          --config=tailwind.storybook.config.js
          --input=css/storybook.css
          --output=../priv/static/assets/storybook.css
        ),
    cd: Path.expand("../assets", __DIR__)
  ]

# Enable dev routes for dashboard and mailbox
config :data_aggregator, dev_routes: true

# Serve uploaded files from the priv/storage directory
config :data_aggregator, serve_files_from: "priv/storage/dev/files"

# Cache files in the priv/storage directory
config :data_aggregator, DataAggregator.Files, cache_dir: "priv/storage/dev/cache"

# Log ash pubsub messages for debugging
# config :ash, :pub_sub, debug?: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Disable debug logs
config :logger, level: :debug

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Configure git hooks. They can be installed manuallu by running `mix git_hooks.install`
config :git_hooks,
  auto_install: true,
  verbose: true,
  hooks: [
    pre_commit: [
      tasks: [
        {:cmd, "mix lint"}
      ]
    ],
    pre_push: [
      tasks: [
        {:cmd, "mix test --color"}
      ]
    ]
  ]
