import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :data_aggregator, DataAggregatorWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: false,
  code_reloader: false,
  server: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: DataAggregator.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Enable Postgres SSL in production
config :data_aggregator, DataAggregator.Repo,
  ssl: true,
  ssl_opts: [verify: :verify_none]

# Enable dev routes for dashboard and mailbox
# remove the line below before going live
config :data_aggregator, dev_routes: true

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
