defmodule DataAggregator.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:change_events) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :catalog_value_reference
    # end
    # 
  end

  def down do
    # alter table(:change_events) do
    # This is the `down` migration of the statement:
    #
    #     remove :catalog_value_reference
    #
    # 
    # add :catalog_value_reference, :text
    # end
    # 
  end
end