defmodule DataAggregator.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tag, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:static_assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :import_id, :uuid
    end

    create table(:records2tags, primary_key: false) do
      add :record_id, :uuid, null: false, primary_key: true
      add :tag_id, :uuid, null: false, primary_key: true
    end

    create table(:records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:records2tags) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "records2tags_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tag_id,
             references(:tags,
               column: :id,
               name: "records2tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:records) do
      add :unique_qualifier, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :import_id, :uuid
    end

    create table(:record_change_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :category, :text, null: false
      add :value, :text
      add :previous_value, :text
      add :catalog_value_ref, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "record_change_events_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :catalog_id, :uuid
      add :dwc_attribute_id, :uuid
    end

    create table(:institutions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :address, :text
      add :zip_code, :text
      add :city, :text
      add :country, :text
      add :mail, :text
      add :tel, :text
      add :contact_person, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:static_assets) do
      modify :import_id,
             references(:imports,
               column: :id,
               name: "static_assets_import_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:records) do
      modify :import_id,
             references(:imports,
               column: :id,
               name: "records_import_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:imports) do
      add :name, :text, null: false
      add :meta_data, :map
      add :version, :bigint, null: false
      add :import_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
    end

    create table(:import_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :parsed_data, :map
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :import_id,
          references(:imports,
            column: :id,
            name: "import_files_import_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:entity_edges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :child_id, :uuid
      add :parent_id, :uuid
    end

    create table(:entities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:entity_edges) do
      modify :child_id,
             references(:entities,
               column: :id,
               name: "entity_edges_child_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :parent_id,
             references(:entities,
               column: :id,
               name: "entity_edges_parent_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:entities) do
      add :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:dwc_attributes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :attribute_resolving_strategy_id, :uuid
      add :entity_id, :uuid
    end

    create table(:collections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:collections) do
      add :name, :text, null: false
      add :meta_data, :map

      add :institution_id,
          references(:institutions,
            column: :id,
            name: "collections_institution_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:catalogs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:record_change_events) do
      modify :catalog_id,
             references(:catalogs,
               column: :id,
               name: "record_change_events_catalog_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :dwc_attribute_id,
             references(:dwc_attributes,
               column: :id,
               name: "record_change_events_dwc_attribute_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalogs) do
      add :name, :text
      add :description, :text
      add :version, :bigint, null: false, default: 1
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:attribute_resolving_strategies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:dwc_attributes) do
      modify :attribute_resolving_strategy_id,
             references(:attribute_resolving_strategies,
               column: :id,
               name: "dwc_attributes_attribute_resolving_strategy_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :entity_id,
             references(:entities,
               column: :id,
               name: "dwc_attributes_entity_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:attribute_resolving_strategies) do
      add :name, :text
      add :url, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :catalog_id,
          references(:catalogs,
            column: :id,
            name: "attribute_resolving_strategies_catalog_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:annotations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :comment, :text, null: false
      add :value_suggestion, :text
      add :user, :text
      add :dwc_attribute_id, :uuid, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "annotations_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:annotations, "annotations_record_id_fkey")

    drop table(:annotations)

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_catalog_id_fkey"
         )

    alter table(:attribute_resolving_strategies) do
      remove :catalog_id
      remove :updated_at
      remove :inserted_at
      remove :url
      remove :name
    end

    drop constraint(:dwc_attributes, "dwc_attributes_attribute_resolving_strategy_id_fkey")

    drop constraint(:dwc_attributes, "dwc_attributes_entity_id_fkey")

    alter table(:dwc_attributes) do
      modify :entity_id, :uuid
      modify :attribute_resolving_strategy_id, :uuid
    end

    drop table(:attribute_resolving_strategies)

    alter table(:catalogs) do
      remove :updated_at
      remove :inserted_at
      remove :version
      remove :description
      remove :name
    end

    drop constraint(:record_change_events, "record_change_events_catalog_id_fkey")

    drop constraint(:record_change_events, "record_change_events_dwc_attribute_id_fkey")

    alter table(:record_change_events) do
      modify :dwc_attribute_id, :uuid
      modify :catalog_id, :uuid
    end

    drop table(:catalogs)

    drop constraint(:collections, "collections_institution_id_fkey")

    alter table(:collections) do
      remove :updated_at
      remove :inserted_at
      remove :institution_id
      remove :meta_data
      remove :name
    end

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id, :uuid
    end

    drop table(:collections)

    drop table(:dwc_attributes)

    alter table(:entities) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:entity_edges, "entity_edges_child_id_fkey")

    drop constraint(:entity_edges, "entity_edges_parent_id_fkey")

    alter table(:entity_edges) do
      modify :parent_id, :uuid
      modify :child_id, :uuid
    end

    drop table(:entities)

    drop table(:entity_edges)

    drop constraint(:import_files, "import_files_import_id_fkey")

    drop table(:import_files)

    alter table(:imports) do
      remove :collection_id
      remove :updated_at
      remove :inserted_at
      remove :import_data
      remove :version
      remove :meta_data
      remove :name
    end

    drop constraint(:records, "records_import_id_fkey")

    alter table(:records) do
      modify :import_id, :uuid
    end

    drop constraint(:static_assets, "static_assets_import_id_fkey")

    alter table(:static_assets) do
      modify :import_id, :uuid
    end

    drop table(:imports)

    drop table(:institutions)

    drop constraint(:record_change_events, "record_change_events_record_id_fkey")

    drop table(:record_change_events)

    alter table(:records) do
      remove :import_id
      remove :updated_at
      remove :inserted_at
      remove :meta_data
      remove :unique_qualifier
    end

    drop constraint(:records2tags, "records2tags_record_id_fkey")

    drop constraint(:records2tags, "records2tags_tag_id_fkey")

    alter table(:records2tags) do
      modify :tag_id, :uuid
      modify :record_id, :uuid
    end

    drop table(:records)

    drop table(:records2tags)

    drop table(:static_assets)

    drop table(:tags)
  end
end