defmodule DataAggregator.Repo.Migrations.RefactorImportFileToImport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:imports, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :amount_of_rows, :bigint
      add :columns, {:array, :map}
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "imports_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "imports_attachment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:imports, "imports_collection_id_fkey")

    drop constraint(:imports, "imports_attachment_id_fkey")

    drop table(:imports)
  end
end
