defmodule DataAggregator.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:records, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :import_data, :map
      add :meta_data, :map
      add :materialEntityID, :text, null: false
      add :scientificName, :text, null: false
      add :prs_contact_point, :text
      add :prs_first_name, :text
      add :prs_last_name, :text
      add :prs_date_of_birth, :date
      add :eve_day, :text
      add :eve_event_date, :date
      add :eve_month, :text
      add :eve_year, :text
      add :idf_date_identified, :date
      add :idf_identified_by, :text
      add :ref_bibliographic_citation, :text
      add :ref_creator, :text
      add :ref_date, :date
      add :ref_rights, :text
      add :ref_source, :text
      add :ref_title, :text
      add :ref_relationship_established_date, :date
      add :rrp_relationship_of_resource, :text
      add :rrp_relationship_of_resource_id, :text
      add :tax_family, :text
      add :tax_scientific_name_authorship, :text
      add :tax_order, :text
      add :loc_continent, :text
      add :loc_country, :text
      add :occ_recorded_by, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
    end

    create table(:record_images, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :size, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :attachment_id, :uuid
      add :record_id, :uuid
    end

    create table(:institutions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :code, :text
      add :address, :text
      add :zip_code, :text
      add :city, :text
      add :country, :text
      add :mail, :text
      add :tel, :text
      add :contact_person, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:import_files, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :amount_of_rows, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
      add :attachment_id, :uuid
    end

    create table(:dwc_attributes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :default_catalog_id, :uuid
    end

    create table(:collections, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:records) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "records_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:import_files) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "import_files_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:collections) do
      add :name, :text, null: false
      add :code, :text
      add :description, :text
      add :mapping, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :institution_id,
          references(:institutions,
            column: :id,
            name: "collections_institution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:catalogs, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:dwc_attributes) do
      modify :default_catalog_id,
             references(:catalogs,
               column: :id,
               name: "dwc_attributes_default_catalog_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalogs) do
      add :name, :text
      add :description, :text
      add :url, :text
      add :version, :bigint, null: false, default: 1
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:attribute_resolving_strategies, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :do_not_encode, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "attribute_resolving_strategies_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :dwc_attribute_id,
          references(:dwc_attributes,
            column: :id,
            name: "attribute_resolving_strategies_dwc_attribute_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :catalog_id,
          references(:catalogs,
            column: :id,
            name: "attribute_resolving_strategies_catalog_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:attachments, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:record_images) do
      modify :attachment_id,
             references(:attachments,
               column: :id,
               name: "record_images_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :record_id,
             references(:records,
               column: :id,
               name: "record_images_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:import_files) do
      modify :attachment_id,
             references(:attachments,
               column: :id,
               name: "import_files_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:attachments) do
      add :url, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:attachments) do
      remove :updated_at
      remove :inserted_at
      remove :meta_data
      remove :url
    end

    drop constraint(:import_files, "import_files_attachment_id_fkey")

    alter table(:import_files) do
      modify :attachment_id, :uuid
    end

    drop constraint(:record_images, "record_images_attachment_id_fkey")

    drop constraint(:record_images, "record_images_record_id_fkey")

    alter table(:record_images) do
      modify :record_id, :uuid
      modify :attachment_id, :uuid
    end

    drop table(:attachments)

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_collection_id_fkey"
         )

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_dwc_attribute_id_fkey"
         )

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_catalog_id_fkey"
         )

    drop table(:attribute_resolving_strategies)

    alter table(:catalogs) do
      remove :updated_at
      remove :inserted_at
      remove :version
      remove :url
      remove :description
      remove :name
    end

    drop constraint(:dwc_attributes, "dwc_attributes_default_catalog_id_fkey")

    alter table(:dwc_attributes) do
      modify :default_catalog_id, :uuid
    end

    drop table(:catalogs)

    drop constraint(:collections, "collections_institution_id_fkey")

    alter table(:collections) do
      remove :institution_id
      remove :updated_at
      remove :inserted_at
      remove :mapping
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:import_files, "import_files_collection_id_fkey")

    alter table(:import_files) do
      modify :collection_id, :uuid
    end

    drop constraint(:records, "records_collection_id_fkey")

    alter table(:records) do
      modify :collection_id, :uuid
    end

    drop table(:collections)

    drop table(:dwc_attributes)

    drop table(:import_files)

    drop table(:institutions)

    drop table(:record_images)

    drop table(:records)
  end
end
