defmodule DataAggregator.Repo.Migrations.AddStateToRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :state, :text, null: false, default: "imported"
    end
  end

  def down do
    alter table(:records) do
      remove :state
    end
  end
end
