defmodule DataAggregator.Repo.Migrations.AddColums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:import_files) do
      add :columns, {:array, :text}
    end
  end

  def down do
    alter table(:import_files) do
      remove :columns
    end
  end
end
