defmodule DataAggregator.Repo.Migrations.AddCollectionToRecordId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Delete records without a collection_id in staging environment
    execute "DELETE FROM records WHERE collection_id IS NULL"

    alter table(:records) do
      modify :collection_id, :uuid, null: false
    end

    drop_if_exists unique_index(:records, [:mte_material_entity_id],
                     name: "records_mte_material_entity_id_index"
                   )

    create unique_index(:records, [:collection_id, :mte_material_entity_id],
             name: "records_mte_material_entity_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:records, [:collection_id, :mte_material_entity_id],
                     name: "records_mte_material_entity_id_index"
                   )

    create unique_index(:records, [:mte_material_entity_id],
             name: "records_mte_material_entity_id_index"
           )

    alter table(:records) do
      modify :collection_id, :uuid, null: true
    end
  end
end
