defmodule DataAggregator.Repo.Migrations.AddResAndAttrsForPublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :tax_accepted_name_usage_id, :text
      add :tax_parent_name_usage_id, :text
      add :tax_taxon_id, :text
      add :tax_taxon_rank, :text
      add :tax_kingdom, :text
      add :tax_class, :text
      add :tax_phylum, :text
    end

    alter table(:consumers) do
      add :publication_type, :text, null: false
    end
  end

  def down do
    alter table(:consumers) do
      remove :publication_type
    end

    alter table(:records) do
      remove :tax_phylum
      remove :tax_class
      remove :tax_kingdom
      remove :tax_taxon_rank
      remove :tax_taxon_id
      remove :tax_parent_name_usage_id
      remove :tax_accepted_name_usage_id
    end
  end
end
