defmodule DataAggregator.Repo.Migrations.AddImportJob do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "imports_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:imports, "imports_job_id_fkey")

    alter table(:imports) do
      remove :job_id
    end
  end
end
