defmodule DataAggregator.Repo.Migrations.ChangeEventAttributeTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      remove :eve_end_of_period_year
      remove :eve_end_of_period_month
      remove :eve_end_of_period_day
      remove :eve_year
      remove :eve_month
      remove :eve_day

      add :eve_end_of_period_year, :bigint
      add :eve_end_of_period_month, :bigint
      add :eve_end_of_period_day, :bigint
      add :eve_year, :bigint
      add :eve_month, :bigint
      add :eve_day, :bigint
    end
  end

  def down do
    alter table(:records) do
      remove :eve_end_of_period_year
      remove :eve_end_of_period_month
      remove :eve_end_of_period_day
      remove :eve_year
      remove :eve_month
      remove :eve_day

      add :eve_end_of_period_year, :text
      add :eve_end_of_period_month, :text
      add :eve_end_of_period_day, :text
      add :eve_year, :text
      add :eve_month, :text
      add :eve_day, :text
    end
  end
end
