defmodule DataAggregator.Repo.Migrations.AddRecAmountAndOwnerToCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :items_to_digitize, :bigint, null: false, default: 0
      add :owner, :text, null: false
    end
  end

  def down do
    alter table(:collections) do
      remove :owner
      remove :items_to_digitize
    end
  end
end
