defmodule DataAggregator.Repo.Migrations.RequireImportCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "DELETE FROM imports WHERE collection_id IS NULL"

    alter table(:imports) do
      modify :collection_id, :uuid, null: false
    end
  end

  def down do
    alter table(:imports) do
      modify :collection_id, :uuid, null: true
    end
  end
end
