defmodule DataAggregator.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:static_assets, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :url, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :import_record_id, :uuid
    end

    create table(:runs, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :comment, :text
      add :state, :text, default: "open"
      add :value_suggestion, :text
      add :user, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:records, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :unique_qualifier, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :import_record_id, :uuid
    end

    create table(:institutions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :address, :text
      add :zip_code, :text
      add :city, :text
      add :country, :text
      add :mail, :text
      add :tel, :text
      add :contact_person, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:import_records, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:static_assets) do
      modify :import_record_id,
             references(:import_records,
               column: :id,
               name: "static_assets_import_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:records) do
      modify :import_record_id,
             references(:import_records,
               column: :id,
               name: "records_import_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:import_records) do
      add :unique_qualifier, :text, null: false
      add :import_data, :map
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
    end

    create table(:import_files, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :url, :text, null: false
      add :meta_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
    end

    create table(:import_change_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :import_record_id,
          references(:import_records,
            column: :id,
            name: "import_change_events_import_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :change_event_id, :uuid
    end

    create table(:encoding_change_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :catalog_value_reference, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :change_event_id, :uuid
      add :catalog_id, :uuid
      add :record_id, :uuid
    end

    create table(:dwc_attributes, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :default_catalog_id, :uuid
    end

    create table(:collections, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:import_records) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "import_records_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:import_files) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "import_files_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:collections) do
      add :name, :text, null: false
      add :code, :text
      add :description, :text
      add :owner, :text
      add :collection_type, :text, null: false, default: "other"
      add :digitization_status, :text, null: false, default: "planned"
      add :collection_size, :bigint
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :institution_id,
          references(:institutions,
            column: :id,
            name: "collections_institution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:change_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:import_change_events) do
      modify :change_event_id,
             references(:change_events,
               column: :id,
               name: "import_change_events_change_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:encoding_change_events) do
      modify :change_event_id,
             references(:change_events,
               column: :id,
               name: "encoding_change_events_change_event_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:change_events) do
      add :category, :text, null: false
      add :value, :text
      add :previous_value, :text
      add :catalog_value_reference, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :dwc_attribute_id,
          references(:dwc_attributes,
            column: :id,
            name: "change_events_dwc_attribute_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :run_id,
          references(:runs,
            column: :id,
            name: "change_events_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:catalogs, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:encoding_change_events) do
      modify :catalog_id,
             references(:catalogs,
               column: :id,
               name: "encoding_change_events_catalog_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :record_id,
             references(:records,
               column: :id,
               name: "encoding_change_events_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:dwc_attributes) do
      modify :default_catalog_id,
             references(:catalogs,
               column: :id,
               name: "dwc_attributes_default_catalog_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:catalogs) do
      add :name, :text
      add :description, :text
      add :url, :text
      add :version, :bigint, null: false, default: 1
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:attribute_resolving_strategies, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :do_not_encode, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :catalog_id,
          references(:catalogs,
            column: :id,
            name: "attribute_resolving_strategies_catalog_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :dwc_attribute_id,
          references(:dwc_attributes,
            column: :id,
            name: "attribute_resolving_strategies_dwc_attribute_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :collection_id,
          references(:collections,
            column: :id,
            name: "attribute_resolving_strategies_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:annotations, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :comment, :text
      add :state, :text, default: "open"
      add :value_suggestion, :text
      add :user, :text

      add :dwc_attribute_id,
          references(:dwc_attributes,
            column: :id,
            name: "annotations_dwc_attribute_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "annotations_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:annotations, "annotations_dwc_attribute_id_fkey")

    drop constraint(:annotations, "annotations_record_id_fkey")

    drop table(:annotations)

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_catalog_id_fkey"
         )

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_dwc_attribute_id_fkey"
         )

    drop constraint(
           :attribute_resolving_strategies,
           "attribute_resolving_strategies_collection_id_fkey"
         )

    drop table(:attribute_resolving_strategies)

    alter table(:catalogs) do
      remove :updated_at
      remove :inserted_at
      remove :version
      remove :url
      remove :description
      remove :name
    end

    drop constraint(:dwc_attributes, "dwc_attributes_default_catalog_id_fkey")

    alter table(:dwc_attributes) do
      modify :default_catalog_id, :uuid
    end

    drop constraint(:encoding_change_events, "encoding_change_events_catalog_id_fkey")

    drop constraint(:encoding_change_events, "encoding_change_events_record_id_fkey")

    alter table(:encoding_change_events) do
      modify :record_id, :uuid
      modify :catalog_id, :uuid
    end

    drop table(:catalogs)

    drop constraint(:change_events, "change_events_dwc_attribute_id_fkey")

    drop constraint(:change_events, "change_events_run_id_fkey")

    alter table(:change_events) do
      remove :run_id
      remove :dwc_attribute_id
      remove :updated_at
      remove :inserted_at
      remove :catalog_value_reference
      remove :previous_value
      remove :value
      remove :category
    end

    drop constraint(:encoding_change_events, "encoding_change_events_change_event_id_fkey")

    alter table(:encoding_change_events) do
      modify :change_event_id, :uuid
    end

    drop constraint(:import_change_events, "import_change_events_change_event_id_fkey")

    alter table(:import_change_events) do
      modify :change_event_id, :uuid
    end

    drop table(:change_events)

    drop constraint(:collections, "collections_institution_id_fkey")

    alter table(:collections) do
      remove :institution_id
      remove :updated_at
      remove :inserted_at
      remove :collection_size
      remove :digitization_status
      remove :collection_type
      remove :owner
      remove :description
      remove :code
      remove :name
    end

    drop constraint(:import_files, "import_files_collection_id_fkey")

    alter table(:import_files) do
      modify :collection_id, :uuid
    end

    drop constraint(:import_records, "import_records_collection_id_fkey")

    alter table(:import_records) do
      modify :collection_id, :uuid
    end

    drop table(:collections)

    drop table(:dwc_attributes)

    drop table(:encoding_change_events)

    drop constraint(:import_change_events, "import_change_events_import_record_id_fkey")

    drop table(:import_change_events)

    drop table(:import_files)

    alter table(:import_records) do
      remove :collection_id
      remove :updated_at
      remove :inserted_at
      remove :meta_data
      remove :import_data
      remove :unique_qualifier
    end

    drop constraint(:records, "records_import_record_id_fkey")

    alter table(:records) do
      modify :import_record_id, :uuid
    end

    drop constraint(:static_assets, "static_assets_import_record_id_fkey")

    alter table(:static_assets) do
      modify :import_record_id, :uuid
    end

    drop table(:import_records)

    drop table(:institutions)

    drop table(:records)

    drop table(:runs)

    drop table(:static_assets)
  end
end
