defmodule DataAggregator.Repo.Migrations.RenameRecordMetaData do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:records), :meta_data, to: :extra_data

    create unique_index(:records, [:mte_material_entity_id],
             name: "records_mte_material_entity_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:records, [:mte_material_entity_id],
                     name: "records_mte_material_entity_id_index"
                   )

    rename table(:records), :extra_data, to: :meta_data
  end
end
