defmodule DataAggregator.Repo.Migrations.RenameImportImportedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:imports), :import_started_at, to: :started_at
    rename table(:imports), :imported_at, to: :finished_at

    alter table(:imports) do
      remove :validated_at
      remove :validation_started_at
    end
  end

  def down do
    alter table(:imports) do
      add :validation_started_at, :utc_datetime
      add :validated_at, :utc_datetime
    end

    rename table(:imports), :finished_at, to: :imported_at
    rename table(:imports), :started_at, to: :import_started_at
  end
end
