defmodule DataAggregator.Repo.Migrations.RemoveStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:record_images, "record_images_attachment_id_fkey")

    alter table(:record_images) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "record_images_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:import_files, "import_files_attachment_id_fkey")

    alter table(:import_files) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "import_files_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    execute(
      "ALTER TABLE import_files alter CONSTRAINT import_files_attachment_id_fkey NOT DEFERRABLE"
    )

    execute(
      "ALTER TABLE record_images alter CONSTRAINT record_images_attachment_id_fkey NOT DEFERRABLE"
    )
  end

  def down do
    drop constraint(:import_files, "import_files_attachment_id_fkey")

    alter table(:import_files) do
      modify :attachment_id,
             references(:attachments,
               column: :id,
               name: "import_files_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:record_images, "record_images_attachment_id_fkey")

    alter table(:record_images) do
      modify :attachment_id,
             references(:attachments,
               column: :id,
               name: "record_images_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
