defmodule DataAggregator.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:providers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :address, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :url, :text, null: false
      add :metaData, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :collection_id, :uuid
    end

    create table(:collections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
    end

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:collections) do
      add :name, :text, null: false
      add :metaData, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :provider_id,
          references(:providers,
            column: :id,
            name: "collections_provider_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:collections, "collections_provider_id_fkey")

    alter table(:collections) do
      remove :provider_id
      remove :updated_at
      remove :inserted_at
      remove :metaData
      remove :name
    end

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id, :uuid
    end

    drop table(:collections)

    drop table(:imports)

    drop table(:providers)
  end
end