defmodule DataAggregator.Repo.Migrations.AddFilesByteSize do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_attachments) do
      add :byte_size, :bigint
    end

    execute "UPDATE file_attachments SET byte_size = 0"

    alter table(:file_attachments) do
      modify :byte_size, :bigint, null: false
    end
  end

  def down do
    alter table(:file_attachments) do
      remove :byte_size
    end
  end
end
