defmodule DataAggregator.Repo.Migrations.CreateFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:file_attachments, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :filename, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    drop table(:file_attachments)
  end
end
