defmodule DataAggregator.Repo.Migrations.AddExportAssets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :tax_accepted_name_usage_id, :text
      add :tax_parent_name_usage_id, :text
      add :tax_taxon_id, :text
      add :tax_taxon_rank, :text
      add :tax_kingdom, :text
      add :tax_class, :text
      add :tax_phylum, :text
    end

    create table(:exports, primary_key: false) do
      add :state, :text, null: false, default: "pending"
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :exported_at, :utc_datetime
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :mapping, :map
      add :exported_count, :bigint, null: false, default: 0
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "exports_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "exports_attachment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:export_records, primary_key: false) do
      add :export_id,
          references(:exports,
            column: :id,
            name: "export_records_export_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :record_id,
          references(:records,
            column: :id,
            name: "export_records_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    alter table(:collections) do
      add :reviewer, :text
    end
  end

  def down do
    alter table(:collections) do
      remove :reviewer
    end

    drop constraint(:export_records, "export_records_export_id_fkey")

    drop constraint(:export_records, "export_records_record_id_fkey")

    drop table(:export_records)

    drop constraint(:exports, "exports_collection_id_fkey")

    drop constraint(:exports, "exports_attachment_id_fkey")

    drop table(:exports)

    alter table(:records) do
      remove :tax_phylum
      remove :tax_class
      remove :tax_kingdom
      remove :tax_taxon_rank
      remove :tax_taxon_id
      remove :tax_parent_name_usage_id
      remove :tax_accepted_name_usage_id
    end
  end
end
