defmodule DataAggregator.Repo.Migrations.AddPublicationResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exports, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :exported_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :consumer_id, :uuid
    end

    create table(:export_records, primary_key: false) do
      add :export_id,
          references(:exports,
            column: :id,
            name: "export_records_export_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :record_id,
          references(:records,
            column: :id,
            name: "export_records_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create table(:consumers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:exports) do
      modify :consumer_id,
             references(:consumers,
               column: :id,
               name: "exports_consumer_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:consumers) do
      add :name, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:consumers) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:exports, "exports_consumer_id_fkey")

    alter table(:exports) do
      modify :consumer_id, :uuid
    end

    drop table(:consumers)

    drop constraint(:export_records, "export_records_export_id_fkey")

    drop constraint(:export_records, "export_records_record_id_fkey")

    drop table(:export_records)

    drop table(:exports)
  end
end
