defmodule DataAggregator.Repo.Migrations.AddImportValidationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:imports), :started_at, to: :import_started_at
    rename table(:imports), :imported_count, to: :rows_imported_count
    rename table(:imports), :invalid_count, to: :rows_invalid_count

    alter table(:imports) do
      remove :finished_at

      add :validation_started_at, :utc_datetime
      add :validated_at, :utc_datetime
      add :rows_valid_count, :bigint
      # add :rows_invalid_count, :bigint
      # add :rows_imported_count, :bigint
    end

    execute "UPDATE imports SET rows_valid_count = rows_imported_count"
  end

  def down do
    alter table(:imports) do
      # remove :rows_imported_count
      # remove :rows_invalid_count
      remove :rows_valid_count
      remove :validated_at
      remove :validation_started_at
      add :finished_at, :utc_datetime
    end

    rename table(:imports), :rows_invalid_count, to: :invalid_count
    rename table(:imports), :rows_imported_count, to: :imported_count
    rename table(:imports), :import_started_at, to: :started_at
  end
end
