defmodule DataAggregator.Repo.Migrations.RemoveAmountOfRowsFromImportRes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:imports) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :amount_of_rows
    # end
    # 
  end

  def down do
    # alter table(:imports) do
    # This is the `down` migration of the statement:
    #
    #     remove :amount_of_rows
    #
    # 
    # add :amount_of_rows, :bigint
    # end
    # 
  end
end
