defmodule DataAggregator.Repo.Migrations.AddEncodingJobRelations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:encoder_jobs, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "encoder_jobs_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "encoder_jobs_job_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:encoder_jobs, "encoder_jobs_record_id_fkey")

    drop constraint(:encoder_jobs, "encoder_jobs_job_id_fkey")

    drop table(:encoder_jobs)
  end
end
