defmodule DataAggregator.Repo.Migrations.AddRowsCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :rows_count, :bigint
    end

    execute "UPDATE imports SET rows_count = imported_count + invalid_count"
  end

  def down do
    alter table(:imports) do
      remove :rows_count
    end
  end
end
