defmodule DataAggregator.Repo.Migrations.CreateImportRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:import_records, primary_key: false) do
      add :import_id,
          references(:imports,
            column: :id,
            name: "import_records_import_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :record_id,
          references(:records,
            column: :id,
            name: "import_records_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:import_records, "import_records_import_id_fkey")

    drop constraint(:import_records, "import_records_record_id_fkey")

    drop table(:import_records)
  end
end
