defmodule DataAggregator.Repo.Migrations.RenameImportInvalidCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:imports), :failed_count, to: :invalid_count
  end

  def down do
    rename table(:imports), :invalid_count, to: :failed_count
  end
end
