defmodule DataAggregator.Repo.Migrations.AddAddAttachmentToExport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exports) do
      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "exports_attachment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:exports, "exports_attachment_id_fkey")

    alter table(:exports) do
      remove :attachment_id
    end
  end
end
