defmodule DataAggregator.Repo.Migrations.AddSpecificEpithetToRecordResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :tax_specific_epithet, :text
    end
  end

  def down do
    alter table(:records) do
      remove :tax_specific_epithet
    end
  end
end
