defmodule DataAggregator.Repo.Migrations.AddEncoding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:encoded_records, primary_key: false) do
      add :mts_material_sample_type, :text
      add :mte_material_entity_id, :text, null: false
      add :occ_occurrence_remarks, :text
      add :occ_associated_occurrences, :text
      add :occ_sex, :text
      add :occ_recorded_by, :text
      add :loc_georeference_remarks, :text
      add :loc_decimal_latitude, :float
      add :loc_decimal_longitude, :float
      add :loc_state_province, :text
      add :loc_verbatim_locality, :text
      add :loc_locality, :text
      add :loc_country, :text
      add :loc_continent, :text
      add :spp_life_stage, :text
      add :tax_specific_epithet, :text
      add :tax_infraspecific_epithet, :text
      add :tax_scientific_name_authorship, :text
      add :tax_scientific_name, :text, null: false
      add :tax_genus, :text
      add :tax_family, :text
      add :tax_order, :text
      add :rrp_relationship_of_resource_id, :text
      add :rrp_relationship_of_resource, :text
      add :ref_relationship_established_date, :date
      add :ref_title, :text
      add :ref_source, :text
      add :ref_rights, :text
      add :ref_date, :date
      add :ref_creator, :text
      add :ref_bibliographic_citation, :text
      add :idf_type_status, :text
      add :idf_identified_by, :text
      add :idf_date_identified, :date
      add :eve_end_of_period_year, :bigint
      add :eve_end_of_period_month, :bigint
      add :eve_end_of_period_day, :bigint
      add :eve_year, :bigint
      add :eve_month, :bigint
      add :eve_day, :bigint
      add :eve_event_date, :date
      add :prs_date_of_birth, :date
      add :prs_last_name, :text
      add :prs_first_name, :text
      add :prs_contact_point, :text
      add :id, :uuid, null: false, primary_key: true
      add :extra_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "encoded_records_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    drop table(:encoded_records)
  end
end
