defmodule DataAggregator.Repo.Migrations.AddImportImportedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :imported_at, :utc_datetime
    end
  end

  def down do
    alter table(:imports) do
      remove :imported_at
    end
  end
end
