defmodule DataAggregator.Repo.Migrations.AddImportStartedFinishedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
    end
  end

  def down do
    alter table(:imports) do
      remove :finished_at
      remove :started_at
    end
  end
end
