defmodule DataAggregator.Repo.Migrations.AddRecordIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:encoded_records, [:record_id, :mte_material_entity_id],
             name: "encoded_records_record_mte_material_entity_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:encoded_records, [:record_id, :mte_material_entity_id],
                     name: "encoded_records_record_mte_material_entity_id_index"
                   )
  end
end
