defmodule DataAggregator.Repo.Migrations.AddRecordsQueryToExport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exports) do
      add :records_query, :binary, null: false
    end
  end

  def down do
    alter table(:exports) do
      remove :records_query
    end
  end
end
