defmodule DataAggregator.Repo.Migrations.AddImportedFailedCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :imported_count, :bigint
      add :failed_count, :bigint
    end
  end

  def down do
    alter table(:imports) do
      remove :failed_count
      remove :imported_count
    end
  end
end
