defmodule DataAggregator.Repo.Migrations.AddAdditionalRecordAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :eve_end_of_period_day, :text
      add :eve_end_of_period_month, :text
      add :eve_end_of_period_year, :text
      add :tax_genus, :text
      add :tax_infraspecific_epithet, :text
      add :spp_life_stage, :text
      add :loc_state_province, :text
      add :loc_verbatim_locality, :text
      add :loc_decimal_longitude, :float
      add :loc_decimal_latitude, :float
      add :loc_georeference_remarks, :text
      add :occ_sex, :text
      add :occ_associated_occurrences, :text
      add :occ_occurrence_remarks, :text
      add :mts_material_sample_type, :text
    end
  end

  def down do
    alter table(:records) do
      remove :mts_material_sample_type
      remove :occ_occurrence_remarks
      remove :occ_associated_occurrences
      remove :occ_sex
      remove :loc_georeference_remarks
      remove :loc_decimal_latitude
      remove :loc_decimal_longitude
      remove :loc_verbatim_locality
      remove :loc_state_province
      remove :spp_life_stage
      remove :tax_infraspecific_epithet
      remove :tax_genus
      remove :eve_end_of_period_year
      remove :eve_end_of_period_month
      remove :eve_end_of_period_day
    end
  end
end
