defmodule DataAggregator.Repo.Migrations.AddImportMappingToCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :mapping

      add :import_mapping, {:array, :map}
    end
  end

  def down do
    alter table(:collections) do
      remove :import_mapping
      # This is the `down` migration of the statement:
      #
      #     remove :mapping
      #

      add :mapping, :map
    end
  end
end
