defmodule DataAggregator.Repo.Migrations.AddStateIndexToRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:records, [:state, :approval_status, :fast_track_status], include: ["id"])
  end

  def down do
    drop_if_exists index(:records, [:state, :approval_status, :fast_track_status])
  end
end
