defmodule DataAggregator.Repo.Migrations.CorrectCollectionTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      modify :type, :text, null: false, default: nil
    end
  end

  def down do
    alter table(:collections) do
      modify :type, :text, null: true, default: "other"
    end
  end
end
