defmodule DataAggregator.Repo.Migrations.AddIucnProperties do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :iucn_redlist_category, :text
    end

    alter table(:encoded_records) do
      add :iucn_redlist_category, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :iucn_redlist_category
    end

    alter table(:records) do
      remove :iucn_redlist_category
    end
  end
end
