defmodule DataAggregator.Repo.Migrations.MoveBelognsToSwissSpeciesToEncodedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:records, "records_tax_taxon_id_fkey")

    alter table(:records) do
      modify :tax_taxon_id, :bigint
    end

    alter table(:encoded_records) do
      modify :tax_taxon_id, :bigint
    end

    create index(:encoded_records, [:tax_taxon_id])

    create index(:records, [:tax_taxon_id])
  end

  def down do
    drop_if_exists index(:records, [:tax_taxon_id])

    drop_if_exists index(:encoded_records, [:tax_taxon_id])

    alter table(:encoded_records) do
      modify :tax_taxon_id, :bigint
    end

    alter table(:records) do
      modify :tax_taxon_id,
             references(:swiss_species,
               column: :usage_key,
               name: "records_tax_taxon_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end
  end
end
