defmodule DataAggregator.Repo.Migrations.RecordVersionImprovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records_versions) do
      add :mte_material_entity_id, :text, null: false
      add :tax_scientific_name, :text, null: false
    end
  end

  def down do
    alter table(:records_versions) do
      remove :tax_scientific_name
      remove :mte_material_entity_id
    end
  end
end
