defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToImageUploads do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:record_images, "record_images_image_upload_id_fkey")

    alter table(:record_images) do
      modify :image_upload_id,
             references(:image_uploads,
               column: :id,
               name: "record_images_image_upload_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:record_images, "record_images_image_upload_id_fkey")

    alter table(:record_images) do
      modify :image_upload_id,
             references(:image_uploads,
               column: :id,
               name: "record_images_image_upload_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end
end
