defmodule DataAggregator.Repo.Migrations.AddPrimaryKeyConstraintToModelsToCollectionsReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("record_images", "record_images_pkey")

    drop constraint("record_encoding_results", "record_encoding_results_pkey")

    drop constraint("import_records", "import_records_pkey")

    drop constraint("approved_records", "approved_records_pkey")

    alter table(:record_images) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: true
    end

    alter table(:record_encoding_results) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: true
    end

    alter table(:import_records) do
      modify :collection_id, :uuid, primary_key: true
      modify :record_id, :uuid, primary_key: true
      modify :import_id, :uuid, primary_key: true
    end

    alter table(:approved_records) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: true
    end
  end

  def down do
    drop constraint("record_images", "record_images_pkey")

    drop constraint("record_encoding_results", "record_encoding_results_pkey")

    drop constraint("import_records", "import_records_pkey")

    drop constraint("approved_records", "approved_records_pkey")

    alter table(:approved_records) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: false
    end

    alter table(:import_records) do
      modify :collection_id, :uuid, primary_key: false
      modify :record_id, :uuid, primary_key: true
      modify :import_id, :uuid, primary_key: true
    end

    alter table(:record_encoding_results) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: false
    end

    alter table(:record_images) do
      modify :id, :uuid, primary_key: true
      modify :collection_id, :uuid, primary_key: false
    end
  end
end
