defmodule DataAggregator.Repo.Migrations.ModifySwissSpeciesRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:swiss_species) do
      add :center, :text
    end

    alter table(:records) do
      modify :tax_taxon_id, :bigint
    end
  end

  def down do
    alter table(:records) do
      modify :tax_taxon_id, :bigint
    end

    alter table(:swiss_species) do
      remove :center
    end
  end
end
