defmodule DataAggregator.Repo.Migrations.AddMoreDatamodelAttributes1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records_versions) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :mte_material_entity_id

      add :mte_catalog_number, :text, null: false
    end

    alter table(:records) do
      modify :mte_material_entity_id, :text, null: true
      add :mts_verbatim_label, :text
      add :mts_references, :text
      add :mts_preservation_id, :text
      add :mts_permit_id, :text
      add :mts_method_id, :text
      add :mts_geological_context_id, :text
      add :mts_event_id, :text
      add :mts_material_sample_id, :text
      add :mte_year_collection_entrance, :text
      add :mte_verbatim_label, :text
      add :mte_tissue_bank_id, :text
      add :mte_taphonomy, :text
      add :mte_sample_designation, :text
      add :mte_reproductive_condition, :text
      add :mte_replacement_minerals, :text
      add :mte_record_number, :text
      add :mte_post_burial_transportation, :text
      add :mte_part_of_organism, :text
      add :mte_paleo_completeness, :text
      add :mte_other_catalog_numbers, :text
      add :mte_original_biominerals, :text
      add :mte_orig_col_author, :text
      add :mte_orientation, :text
      add :mte_organism_quantity_type, :text
      add :mte_organism_quantity_method, :text
      add :mte_organism_quantity, :text
      add :mte_occurrence_status, :text
      add :mte_mineralization, :text
      add :mte_matrix, :text
      add :mte_material_entity_type, :text
      add :mte_material_entity_remarks, :text
      add :mte_life_stage, :text
      add :mte_gbif_doi, :text
      add :mte_form, :text
      add :mte_feeding_predation_traces, :text
      add :mte_extraction_temporary_id, :text
      add :mte_encrustation, :text
      add :mte_dna_stable_id, :text
      add :mte_dna_bank_id, :text
      add :mte_digital_entity_type, :text
      add :mte_depositional_environment_type, :text
      add :mte_depositional_environment_text, :text
      add :mte_completeness, :text
      add :mte_catalog_number, :text, null: false
      add :mte_bioerosion, :text
      add :mte_behavior, :text
      add :mte_barcode_label, :text
      add :mte_assemblage_origin, :text
      add :mte_articulation, :text
      add :mte_anatomical_description, :text
      add :mte_references, :text
      add :mte_preservation_id, :text
      add :mte_permit_id, :text
      add :mte_parent_material_entity_id, :text
      add :mte_organism_id, :text
      add :mte_method_id, :text
      add :mte_material_sample_id, :text
      add :mte_geological_context_id, :text
      add :mte_associated_media, :text
    end

    drop_if_exists unique_index(:records, [:collection_id, :mte_material_entity_id],
                     name: "records_collection_mte_material_entity_id_index"
                   )

    create unique_index(:records, [:collection_id, :mte_catalog_number],
             name: "records_collection_mte_catalog_number_index"
           )

    alter table(:encoded_records) do
      modify :mte_material_entity_id, :text, null: true
      add :mts_verbatim_label, :text
      add :mts_references, :text
      add :mts_preservation_id, :text
      add :mts_permit_id, :text
      add :mts_method_id, :text
      add :mts_geological_context_id, :text
      add :mts_event_id, :text
      add :mts_material_sample_id, :text
      add :mte_year_collection_entrance, :text
      add :mte_verbatim_label, :text
      add :mte_tissue_bank_id, :text
      add :mte_taphonomy, :text
      add :mte_sample_designation, :text
      add :mte_reproductive_condition, :text
      add :mte_replacement_minerals, :text
      add :mte_record_number, :text
      add :mte_post_burial_transportation, :text
      add :mte_part_of_organism, :text
      add :mte_paleo_completeness, :text
      add :mte_other_catalog_numbers, :text
      add :mte_original_biominerals, :text
      add :mte_orig_col_author, :text
      add :mte_orientation, :text
      add :mte_organism_quantity_type, :text
      add :mte_organism_quantity_method, :text
      add :mte_organism_quantity, :text
      add :mte_occurrence_status, :text
      add :mte_mineralization, :text
      add :mte_matrix, :text
      add :mte_material_entity_type, :text
      add :mte_material_entity_remarks, :text
      add :mte_life_stage, :text
      add :mte_gbif_doi, :text
      add :mte_form, :text
      add :mte_feeding_predation_traces, :text
      add :mte_extraction_temporary_id, :text
      add :mte_encrustation, :text
      add :mte_dna_stable_id, :text
      add :mte_dna_bank_id, :text
      add :mte_digital_entity_type, :text
      add :mte_depositional_environment_type, :text
      add :mte_depositional_environment_text, :text
      add :mte_completeness, :text
      add :mte_catalog_number, :text, null: false
      add :mte_bioerosion, :text
      add :mte_behavior, :text
      add :mte_barcode_label, :text
      add :mte_assemblage_origin, :text
      add :mte_articulation, :text
      add :mte_anatomical_description, :text
      add :mte_references, :text
      add :mte_preservation_id, :text
      add :mte_permit_id, :text
      add :mte_parent_material_entity_id, :text
      add :mte_organism_id, :text
      add :mte_method_id, :text
      add :mte_material_sample_id, :text
      add :mte_geological_context_id, :text
      add :mte_associated_media, :text
    end

    drop_if_exists unique_index(:encoded_records, [:mte_material_entity_id, :record_id],
                     name: "encoded_records_record_mte_material_entity_id_index"
                   )

    create unique_index(:encoded_records, [:record_id, :mte_catalog_number],
             name: "encoded_records_record_mte_catalog_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:encoded_records, [:record_id, :mte_catalog_number],
                     name: "encoded_records_record_mte_catalog_number_index"
                   )

    create unique_index(:encoded_records, [:mte_material_entity_id, :record_id],
             name: "encoded_records_record_mte_material_entity_id_index"
           )

    alter table(:encoded_records) do
      remove :mte_associated_media
      remove :mte_geological_context_id
      remove :mte_material_sample_id
      remove :mte_method_id
      remove :mte_organism_id
      remove :mte_parent_material_entity_id
      remove :mte_permit_id
      remove :mte_preservation_id
      remove :mte_references
      remove :mte_anatomical_description
      remove :mte_articulation
      remove :mte_assemblage_origin
      remove :mte_barcode_label
      remove :mte_behavior
      remove :mte_bioerosion
      remove :mte_catalog_number
      remove :mte_completeness
      remove :mte_depositional_environment_text
      remove :mte_depositional_environment_type
      remove :mte_digital_entity_type
      remove :mte_dna_bank_id
      remove :mte_dna_stable_id
      remove :mte_encrustation
      remove :mte_extraction_temporary_id
      remove :mte_feeding_predation_traces
      remove :mte_form
      remove :mte_gbif_doi
      remove :mte_life_stage
      remove :mte_material_entity_remarks
      remove :mte_material_entity_type
      remove :mte_matrix
      remove :mte_mineralization
      remove :mte_occurrence_status
      remove :mte_organism_quantity
      remove :mte_organism_quantity_method
      remove :mte_organism_quantity_type
      remove :mte_orientation
      remove :mte_orig_col_author
      remove :mte_original_biominerals
      remove :mte_other_catalog_numbers
      remove :mte_paleo_completeness
      remove :mte_part_of_organism
      remove :mte_post_burial_transportation
      remove :mte_record_number
      remove :mte_replacement_minerals
      remove :mte_reproductive_condition
      remove :mte_sample_designation
      remove :mte_taphonomy
      remove :mte_tissue_bank_id
      remove :mte_verbatim_label
      remove :mte_year_collection_entrance
      remove :mts_material_sample_id
      remove :mts_event_id
      remove :mts_geological_context_id
      remove :mts_method_id
      remove :mts_permit_id
      remove :mts_preservation_id
      remove :mts_references
      remove :mts_verbatim_label
      modify :mte_material_entity_id, :text, null: false
    end

    drop_if_exists unique_index(:records, [:collection_id, :mte_catalog_number],
                     name: "records_collection_mte_catalog_number_index"
                   )

    create unique_index(:records, [:collection_id, :mte_material_entity_id],
             name: "records_collection_mte_material_entity_id_index"
           )

    alter table(:records) do
      remove :mte_associated_media
      remove :mte_geological_context_id
      remove :mte_material_sample_id
      remove :mte_method_id
      remove :mte_organism_id
      remove :mte_parent_material_entity_id
      remove :mte_permit_id
      remove :mte_preservation_id
      remove :mte_references
      remove :mte_anatomical_description
      remove :mte_articulation
      remove :mte_assemblage_origin
      remove :mte_barcode_label
      remove :mte_behavior
      remove :mte_bioerosion
      remove :mte_catalog_number
      remove :mte_completeness
      remove :mte_depositional_environment_text
      remove :mte_depositional_environment_type
      remove :mte_digital_entity_type
      remove :mte_dna_bank_id
      remove :mte_dna_stable_id
      remove :mte_encrustation
      remove :mte_extraction_temporary_id
      remove :mte_feeding_predation_traces
      remove :mte_form
      remove :mte_gbif_doi
      remove :mte_life_stage
      remove :mte_material_entity_remarks
      remove :mte_material_entity_type
      remove :mte_matrix
      remove :mte_mineralization
      remove :mte_occurrence_status
      remove :mte_organism_quantity
      remove :mte_organism_quantity_method
      remove :mte_organism_quantity_type
      remove :mte_orientation
      remove :mte_orig_col_author
      remove :mte_original_biominerals
      remove :mte_other_catalog_numbers
      remove :mte_paleo_completeness
      remove :mte_part_of_organism
      remove :mte_post_burial_transportation
      remove :mte_record_number
      remove :mte_replacement_minerals
      remove :mte_reproductive_condition
      remove :mte_sample_designation
      remove :mte_taphonomy
      remove :mte_tissue_bank_id
      remove :mte_verbatim_label
      remove :mte_year_collection_entrance
      remove :mts_material_sample_id
      remove :mts_event_id
      remove :mts_geological_context_id
      remove :mts_method_id
      remove :mts_permit_id
      remove :mts_preservation_id
      remove :mts_references
      remove :mts_verbatim_label
      modify :mte_material_entity_id, :text, null: false
    end

    alter table(:records_versions) do
      remove :mte_catalog_number
      # This is the `down` migration of the statement:
      #
      #     remove :mte_material_entity_id
      #

      add :mte_material_entity_id, :text, null: false
    end
  end
end
