defmodule DataAggregator.Repo.Migrations.AddUserActorToVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "records_versions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:encoded_records_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "encoded_records_versions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:encoded_records_versions, "encoded_records_versions_user_id_fkey")

    alter table(:encoded_records_versions) do
      remove :user_id
    end

    drop constraint(:records_versions, "records_versions_user_id_fkey")

    alter table(:records_versions) do
      remove :user_id
    end
  end
end
