defmodule DataAggregator.Repo.Migrations.ActivatePaperTrailForEncodedRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("encoded_records", "encoded_records_pkey")

    create table(:encoded_records_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map
      add :version_inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :version_updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:encoded_records) do
      modify :record_id, :uuid, primary_key: false
    end
  end

  def down do
    alter table(:encoded_records) do
      modify :record_id, :uuid, primary_key: true
    end

    drop table(:encoded_records_versions)
  end
end
