defmodule DataAggregator.Repo.Migrations.AddRecordsCountToCollections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :records_count, :bigint, null: false, default: 0
    end

    # update records count
    execute """
      UPDATE collections
      SET records_count = (
        SELECT COUNT(*)
        FROM records
        WHERE collection_id = collections.id
      )
    """
  end

  def down do
    alter table(:collections) do
      remove :records_count
    end
  end
end
