defmodule DataAggregator.Repo.Migrations.OnDeleteConstraintsForRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:records, "records_collection_id_fkey")

    alter table(:records) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "records_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:record_images, "record_images_record_id_fkey")

    drop constraint(:record_images, "record_images_attachment_id_fkey")

    alter table(:record_images) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "record_images_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:record_encoding_results, "record_encoding_results_record_id_fkey")

    alter table(:record_encoding_results) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "record_encoding_results_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    alter table(:encoded_records) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "encoded_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE encoded_records alter CONSTRAINT encoded_records_record_id_fkey NOT DEFERRABLE"
    )

    execute(
      "ALTER TABLE record_encoding_results alter CONSTRAINT record_encoding_results_record_id_fkey NOT DEFERRABLE"
    )

    execute(
      "ALTER TABLE record_images alter CONSTRAINT record_images_attachment_id_fkey NOT DEFERRABLE"
    )

    alter table(:record_images) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "record_images_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE record_images alter CONSTRAINT record_images_record_id_fkey NOT DEFERRABLE"
    )

    execute("ALTER TABLE records alter CONSTRAINT records_collection_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:record_images, "record_images_record_id_fkey")

    alter table(:record_images) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "record_images_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    alter table(:encoded_records) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "encoded_records_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:record_encoding_results, "record_encoding_results_record_id_fkey")

    alter table(:record_encoding_results) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "record_encoding_results_record_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:record_images, "record_images_attachment_id_fkey")

    alter table(:record_images) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "record_images_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:records, "records_collection_id_fkey")

    alter table(:records) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "records_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
