defmodule DataAggregator.Repo.Migrations.AddCreatedByAndStartedByUserToImports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "imports_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :started_by_id,
          references(:users,
            column: :id,
            name: "imports_started_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:imports, "imports_created_by_id_fkey")

    drop constraint(:imports, "imports_started_by_id_fkey")

    alter table(:imports) do
      remove :started_by_id
      remove :created_by_id
    end
  end
end
