defmodule DataAggregator.Repo.Migrations.ConfigureTaxonomyModule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swiss_species, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :taxon_id_ch, :text, null: false
      add :accepted_name, :text
      add :usage_key, :text
      add :accepted_usage_key, :text
      add :scientific_name, :text
      add :rank, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:records) do
      add :tax_accepted_name_usage_id, :text
      add :tax_accepted_name_usage, :text
      add :tax_taxon_id_ch, :text
    end

    alter table(:encoded_records) do
      add :tax_accepted_name_usage_id, :text
      add :tax_accepted_name_usage, :text
      add :tax_taxon_id_ch, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :tax_taxon_id_ch
      remove :tax_accepted_name_usage
      remove :tax_accepted_name_usage_id
    end

    alter table(:records) do
      remove :tax_taxon_id_ch
      remove :tax_accepted_name_usage
      remove :tax_accepted_name_usage_id
    end

    drop table(:swiss_species)
  end
end
