defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToEncodedRecordsAndEncodedRecordsVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    alter table(:encoded_records) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "encoded_records_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    execute "UPDATE encoded_records SET collection_id = records.collection_id FROM records WHERE encoded_records.record_id = records.id"

    alter table(:encoded_records) do
      modify :collection_id, :uuid, null: false
    end

    drop_if_exists unique_index(:encoded_records, [:record_id, :mte_catalog_number],
                     name: "encoded_records_record_mte_catalog_number_index"
                   )

    alter table(:encoded_records) do
      modify :record_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "encoded_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create unique_index(:encoded_records, [:collection_id, :record_id, :mte_catalog_number],
             name: "encoded_records_record_mte_catalog_number_index"
           )

    create unique_index(:encoded_records, [:collection_id, :id],
             name: "encoded_records_by_collection_index"
           )

    drop constraint(:encoded_records_versions, "encoded_records_versions_version_source_id_fkey")

    alter table(:encoded_records_versions) do
      add :collection_id, :uuid
    end

    execute "UPDATE encoded_records_versions SET collection_id = encoded_records.collection_id FROM encoded_records WHERE encoded_records_versions.version_source_id = encoded_records.id"

    alter table(:encoded_records_versions) do
      modify :collection_id, :uuid, null: false

      modify :version_source_id,
             references(:encoded_records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "encoded_records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:encoded_records_versions, "encoded_records_versions_version_source_id_fkey")

    alter table(:encoded_records_versions) do
      modify :version_source_id,
             references(:encoded_records,
               column: :id,
               name: "encoded_records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop_if_exists unique_index(:encoded_records, [:collection_id, :id],
                     name: "encoded_records_by_collection_index"
                   )

    drop_if_exists unique_index(
                     :encoded_records,
                     [:collection_id, :record_id, :mte_catalog_number],
                     name: "encoded_records_record_mte_catalog_number_index"
                   )

    drop constraint(:encoded_records, "encoded_records_collection_id_fkey")

    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    alter table(:encoded_records) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "encoded_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create unique_index(:encoded_records, [:collection_id, :record_id, :mte_catalog_number],
             name: "encoded_records_record_mte_catalog_number_index"
           )

    alter table(:encoded_records) do
      remove :collection_id
    end

    alter table(:encoded_records_versions) do
      remove :collection_id
    end
  end
end
