defmodule DataAggregator.Repo.Migrations.FixTypoInAttributeName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:records), :eve_cover_toal_in_percentage, to: :eve_cover_total_in_percentage

    alter table(:records) do
      modify :eve_cover_total_in_percentage, :float
    end

    rename table(:encoded_records), :eve_cover_toal_in_percentage,
      to: :eve_cover_total_in_percentage

    alter table(:encoded_records) do
      modify :eve_cover_total_in_percentage, :float
    end
  end

  def down do
    alter table(:encoded_records) do
      modify :eve_cover_toal_in_percentage, :float
    end

    rename table(:encoded_records), :eve_cover_total_in_percentage,
      to: :eve_cover_toal_in_percentage

    alter table(:records) do
      modify :eve_cover_toal_in_percentage, :float
    end

    rename table(:records), :eve_cover_total_in_percentage, to: :eve_cover_toal_in_percentage
  end
end
