defmodule DataAggregator.Repo.Migrations.AddExportExtensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:exports, "exports_attachment_id_fkey")

    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      add :rows_count, :bigint, null: false, default: 0

      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "exports_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute("ALTER TABLE exports alter CONSTRAINT exports_collection_id_fkey NOT DEFERRABLE")

    alter table(:exports) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "exports_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute("ALTER TABLE exports alter CONSTRAINT exports_attachment_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:exports, "exports_attachment_id_fkey")

    alter table(:exports) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "exports_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:exports, "exports_job_id_fkey")

    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      remove :job_id
      remove :rows_count
    end
  end
end
