defmodule DataAggregator.Repo.Migrations.AddGrscicollInstitutionNameToCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :grscicoll_institution_name, :text
    end
  end

  def down do
    alter table(:collections) do
      remove :grscicoll_institution_name
    end
  end
end
