defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToApprovedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:approved_records, "approved_records_record_id_fkey")

    alter table(:approved_records) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "approved_records_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    execute "UPDATE approved_records SET collection_id = records.collection_id FROM records WHERE approved_records.record_id = records.id"

    alter table(:approved_records) do
      modify :collection_id, :uuid, null: false
    end

    drop_if_exists unique_index(:approved_records, [:record_id, :mte_catalog_number],
                     name: "approved_records_record_mte_catalog_number_index"
                   )

    alter table(:approved_records) do
      modify :record_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "approved_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create unique_index(:approved_records, [:collection_id, :record_id, :mte_catalog_number],
             name: "approved_records_record_mte_catalog_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :approved_records,
                     [:collection_id, :record_id, :mte_catalog_number],
                     name: "approved_records_record_mte_catalog_number_index"
                   )

    drop constraint(:approved_records, "approved_records_collection_id_fkey")

    drop constraint(:approved_records, "approved_records_record_id_fkey")

    alter table(:approved_records) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "approved_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create unique_index(:approved_records, [:collection_id, :record_id, :mte_catalog_number],
             name: "approved_records_record_mte_catalog_number_index"
           )

    alter table(:approved_records) do
      remove :collection_id
    end
  end
end
