defmodule DataAggregator.Repo.Migrations.RelateImageUploadToRecordImage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:record_images) do
      add :image_upload_id,
          references(:image_uploads,
            column: :id,
            name: "record_images_image_upload_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    create index(:record_images, [:image_upload_id])
  end

  def down do
    drop_if_exists index(:record_images, [:image_upload_id])

    drop constraint(:record_images, "record_images_image_upload_id_fkey")

    alter table(:record_images) do
      remove :image_upload_id
    end
  end
end
