defmodule DataAggregator.Repo.Migrations.MigrateTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:swiss_species) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:records_versions) do
      modify :version_updated_at, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :version_inserted_at, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:records) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:record_images) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:record_encoding_results) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:publications) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:institutions) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:imports) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:file_attachments) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:exports) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:encoded_records_versions) do
      modify :version_updated_at, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :version_inserted_at, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")

      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:encoded_records) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:collections) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:approved_records) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:approvals) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:approvals) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:approved_records) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:collections) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:encoded_records) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:encoded_records_versions) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :version_inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :version_updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:exports) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:file_attachments) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:imports) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:institutions) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:publications) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:record_encoding_results) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:record_images) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:records) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:records_versions) do
      modify :id, :uuid, default: fragment("uuid_generate_v4()")
      modify :version_inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :version_updated_at, :utc_datetime_usec, default: fragment("now()")
    end

    alter table(:swiss_species) do
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
    end
  end
end
