defmodule DataAggregator.Repo.Migrations.MakeQueriesPersistableAsMaps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      modify :records_query, :map
    end

    alter table(:exports) do
      modify :records_query, :map
    end
  end

  def down do
    alter table(:exports) do
      modify :records_query, :binary
    end

    alter table(:publications) do
      modify :records_query, :binary
    end
  end
end
