defmodule DataAggregator.Repo.Migrations.AddGrscicollReferenceToResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:institutions) do
      add :grscicoll_reference, :text, null: false
    end

    alter table(:collections) do
      add :grscicoll_reference, :text, null: false
    end
  end

  def down do
    alter table(:collections) do
      remove :grscicoll_reference
    end

    alter table(:institutions) do
      remove :grscicoll_reference
    end
  end
end
