defmodule DataAggregator.Repo.Migrations.AddUniqueRecordsByCollectionIndexToRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:records, [:id, :collection_id], name: "records_by_collection_index")
  end

  def down do
    drop_if_exists unique_index(:records, [:id, :collection_id],
                     name: "records_by_collection_index"
                   )
  end
end
