defmodule DataAggregator.Repo.Migrations.RemovePlatformDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      remove :institution_id
    end

    drop table(:institutions)
  end

  def down do
    create table(:institutions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, default: fragment("uuid_generate_v7()")
      add :name, :text, null: false
      add :code, :text
      add :address, :text
      add :zip_code, :text
      add :city, :text
      add :country, :text
      add :mail, :text
      add :tel, :text
      add :contact_person, :text
      add :grscicoll_reference, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:collections) do
      add :institution_id,
          references(:institutions,
            column: :id,
            name: "collections_institution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
