defmodule DataAggregator.Repo.Migrations.RemoveRelationshipFromUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:users, "users_institution_id_fkey")

    alter table(:users) do
      modify :institution_id, :uuid
    end
  end

  def down do
    alter table(:users) do
      modify :institution_id,
             references(:institutions,
               column: :id,
               name: "users_institution_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
