defmodule DataAggregator.Repo.Migrations.RemoveJobReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:records, [:fast_track_checker_job_id])

    alter table(:records) do
      remove :fast_track_checker_job_id
      remove :encoder_job_id
    end

    drop_if_exists index(:publications, [:job_id])

    alter table(:publications) do
      remove :job_id
    end

    alter table(:imports) do
      remove :job_id
    end

    drop_if_exists index(:exports, [:job_id])

    alter table(:exports) do
      remove :job_id
    end

    drop_if_exists index(:approvals, [:job_id])

    alter table(:approvals) do
      remove :job_id
    end
  end

  def down do
    alter table(:approvals) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "approvals_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:approvals, [:job_id])

    alter table(:exports) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "exports_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:exports, [:job_id])

    alter table(:imports) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "imports_job_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    alter table(:publications) do
      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "publications_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:publications, [:job_id])

    alter table(:records) do
      add :encoder_job_id,
          references(:oban_jobs,
            column: :id,
            name: "records_encoder_job_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :fast_track_checker_job_id,
          references(:oban_jobs,
            column: :id,
            name: "records_fast_track_checker_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:records, [:fast_track_checker_job_id])
  end
end
