defmodule DataAggregator.Repo.Migrations.ChangeAttributesToFloat do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
    ALTER TABLE records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE float USING eve_herb_layer_height_in_centimeters::double precision,
      ALTER COLUMN eve_inclination_in_degrees TYPE float USING eve_inclination_in_degrees::double precision,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE float USING eve_tree_layer_height_in_meters::double precision,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE float USING loc_minimum_elevation_in_meters::double precision,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE float USING loc_maximum_elevation_in_meters::double precision,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE float USING loc_minimum_depth_in_meters::double precision,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE float USING loc_maximum_depth_in_meters::double precision,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE float USING loc_minimum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE float USING loc_maximum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE float USING loc_coordinate_uncertainty_in_meters::double precision;
    """

    execute """
    ALTER TABLE encoded_records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE float USING eve_herb_layer_height_in_centimeters::double precision,
      ALTER COLUMN eve_inclination_in_degrees TYPE float USING eve_inclination_in_degrees::double precision,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE float USING eve_tree_layer_height_in_meters::double precision,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE float USING loc_minimum_elevation_in_meters::double precision,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE float USING loc_maximum_elevation_in_meters::double precision,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE float USING loc_minimum_depth_in_meters::double precision,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE float USING loc_maximum_depth_in_meters::double precision,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE float USING loc_minimum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE float USING loc_maximum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE float USING loc_coordinate_uncertainty_in_meters::double precision;
    """

    execute """
    ALTER TABLE approved_records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE float USING eve_herb_layer_height_in_centimeters::double precision,
      ALTER COLUMN eve_inclination_in_degrees TYPE float USING eve_inclination_in_degrees::double precision,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE float USING eve_tree_layer_height_in_meters::double precision,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE float USING loc_minimum_elevation_in_meters::double precision,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE float USING loc_maximum_elevation_in_meters::double precision,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE float USING loc_minimum_depth_in_meters::double precision,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE float USING loc_maximum_depth_in_meters::double precision,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE float USING loc_minimum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE float USING loc_maximum_distance_above_surface_in_meters::double precision,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE float USING loc_coordinate_uncertainty_in_meters::double precision;
    """
  end

  def down do
    execute """
    ALTER TABLE records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE bigint,
      ALTER COLUMN eve_inclination_in_degrees TYPE bigint,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE bigint;
    """

    execute """
    ALTER TABLE encoded_records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE bigint,
      ALTER COLUMN eve_inclination_in_degrees TYPE bigint,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE bigint;
    """

    execute """
    ALTER TABLE approved_records
      ALTER COLUMN eve_herb_layer_height_in_centimeters TYPE bigint,
      ALTER COLUMN eve_inclination_in_degrees TYPE bigint,
      ALTER COLUMN eve_tree_layer_height_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_elevation_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_depth_in_meters TYPE bigint,
      ALTER COLUMN loc_minimum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_maximum_distance_above_surface_in_meters TYPE bigint,
      ALTER COLUMN loc_coordinate_uncertainty_in_meters TYPE bigint;
    """
  end
end
