defmodule DataAggregator.Repo.Migrations.PublicationWorkerExtensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :fast_track_status, :map
      add :approval_status, :map
    end

    create table(:publications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :channel, :text, null: false
      add :published_at, :utc_datetime
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :records_query, :map, null: false
      add :published_count, :bigint, null: false, default: 0
      add :rows_count, :bigint, null: false, default: 0
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "publications_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "publications_attachment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "publications_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :state, :text, null: false, default: "pending"
    end
  end

  def down do
    drop constraint(:publications, "publications_collection_id_fkey")

    drop constraint(:publications, "publications_attachment_id_fkey")

    drop constraint(:publications, "publications_job_id_fkey")

    drop table(:publications)

    alter table(:records) do
      remove :approval_status
      remove :fast_track_status
    end
  end
end
