defmodule DataAggregator.Repo.Migrations.AddRecordErrorsField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :errors, :map
    end
  end

  def down do
    alter table(:records) do
      remove :errors
    end
  end
end