defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToApproval do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "DELETE FROM approvals"

    alter table(:approvals) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "approvals_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:approvals, "approvals_collection_id_fkey")

    alter table(:approvals) do
      remove :collection_id
    end
  end
end
