defmodule DataAggregator.Repo.Migrations.AddCollectionTypeToResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :type, :text, default: "other"
    end
  end

  def down do
    alter table(:collections) do
      remove :type
    end
  end
end
