defmodule DataAggregator.Repo.Migrations.AddUuidDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:record_images) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:institutions) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:imports) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:file_attachments) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:dwc_attributes) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:collections) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:catalogs) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:attribute_resolving_strategies) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:attribute_resolving_strategies) do
      modify :id, :uuid, default: nil
    end

    alter table(:catalogs) do
      modify :id, :uuid, default: nil
    end

    alter table(:collections) do
      modify :id, :uuid, default: nil
    end

    alter table(:dwc_attributes) do
      modify :id, :uuid, default: nil
    end

    alter table(:file_attachments) do
      modify :id, :uuid, default: nil
    end

    alter table(:imports) do
      modify :id, :uuid, default: nil
    end

    alter table(:institutions) do
      modify :id, :uuid, default: nil
    end

    alter table(:record_images) do
      modify :id, :uuid, default: nil
    end

    alter table(:records) do
      modify :id, :uuid, default: nil
    end
  end
end
