defmodule DataAggregator.Repo.Migrations.AddUserActorToVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "records_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    alter table(:encoded_records_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "encoded_records_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    execute(
      "ALTER TABLE encoded_records_versions alter CONSTRAINT encoded_records_versions_user_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    create index(:encoded_records_versions, [:user_id])

    execute(
      "ALTER TABLE records_versions alter CONSTRAINT records_versions_user_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    create index(:records_versions, [:user_id])
  end

  def down do
    drop_if_exists index(:records_versions, [:user_id])

    drop_if_exists index(:encoded_records_versions, [:user_id])

    drop constraint(:encoded_records_versions, "encoded_records_versions_user_id_fkey")

    alter table(:encoded_records_versions) do
      remove :user_id
    end

    drop constraint(:records_versions, "records_versions_user_id_fkey")

    alter table(:records_versions) do
      remove :user_id
    end

    execute(
      "ALTER TABLE records_versions alter CONSTRAINT records_versions_user_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    execute(
      "ALTER TABLE encoded_records_versions alter CONSTRAINT encoded_records_versions_user_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )
  end
end
