defmodule DataAggregator.Repo.Migrations.OptimizeVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # record versions

    # delete stale versions
    execute """
      DELETE FROM records_versions
      WHERE version_source_id IN (
        SELECT version_source_id
        FROM records_versions rv
        LEFT JOIN records r ON r.id = rv.version_source_id
        WHERE r.id IS NULL
      )
    """

    alter table(:records_versions) do
      modify :version_source_id,
             references(:records,
               column: :id,
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:records_versions, [:version_source_id])

    # encoded record versions

    # delete stale versions
    execute """
      DELETE FROM encoded_records_versions
      WHERE version_source_id IN (
        SELECT version_source_id
        FROM encoded_records_versions rv
        LEFT JOIN encoded_records r ON r.id = rv.version_source_id
        WHERE r.id IS NULL
      )
    """

    alter table(:encoded_records_versions) do
      modify :version_source_id,
             references(:encoded_records,
               column: :id,
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:encoded_records_versions, [:version_source_id])
  end

  def down do
    # record versions

    drop_if_exists index(:encoded_records_versions, [:version_source_id])

    alter table(:encoded_records_versions) do
      modify :version_source_id, :uuid
    end

    # encoded record versions

    drop_if_exists index(:records_versions, [:version_source_id])

    alter table(:records_versions) do
      modify :version_source_id, :uuid
    end
  end
end
