defmodule DataAggregator.Repo.Migrations.AddInstitutionAndRolesToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :roles, {:array, :text}, default: []

      add :institution_id,
          references(:institutions,
            column: :id,
            name: "users_institution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_institution_id_fkey")

    alter table(:users) do
      remove :institution_id
      remove :roles
    end
  end
end
