defmodule DataAggregator.Repo.Migrations.FixSchemaTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
      ALTER TABLE records
        ALTER COLUMN loc_verbatim_depth TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """

    execute """
      ALTER TABLE encoded_records
        ALTER COLUMN loc_verbatim_depth TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """

    execute """
      ALTER TABLE approved_records
        ALTER COLUMN loc_verbatim_depth TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """
  end

  def down do
    execute """
      ALTER TABLE records
        ALTER COLUMN loc_verbatim_depth TYPE bigint USING loc_verbatim_depth::bigint,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """

    execute """
      ALTER TABLE encoded_records
        ALTER COLUMN loc_verbatim_depth TYPE bigint USING loc_verbatim_depth::bigint,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """

    execute """
      ALTER TABLE approved_records
        ALTER COLUMN loc_verbatim_depth TYPE bigint USING loc_verbatim_depth::bigint,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """
  end
end
