defmodule DataAggregator.Repo.Migrations.AddErrorCountToImport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :rows_error_count, :bigint
    end
  end

  def down do
    alter table(:imports) do
      remove :rows_error_count
    end
  end
end
