defmodule DataAggregator.Repo.Migrations.AddFilterIndicesToEncodedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:encoded_records, [:collection_id, :loc_continent, :tax_kingdom, :tax_phylum])
  end

  def down do
    drop_if_exists index(:encoded_records, [
                     :collection_id,
                     :loc_continent,
                     :tax_kingdom,
                     :tax_phylum
                   ])
  end
end
