defmodule DataAggregator.Repo.Migrations.ModificationsForCollectionRegistration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :gbif_dataset_key, :text
    end
  end

  def down do
    alter table(:collections) do
      remove :gbif_dataset_key
    end
  end
end
