defmodule DataAggregator.Repo.Migrations.ExportExtensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :exported_at, :utc_datetime
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :mapping, :map
      add :records_query, :binary, null: false
      add :exported_count, :bigint, null: false, default: 0
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "exports_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "exports_attachment_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :state, :text, null: false, default: "pending"
    end
  end

  def down do
    drop constraint(:exports, "exports_collection_id_fkey")

    drop constraint(:exports, "exports_attachment_id_fkey")

    drop table(:exports)
  end
end
