defmodule DataAggregator.Repo.Migrations.AddCenterToPublicationResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      add :center, :text
    end
  end

  def down do
    alter table(:publications) do
      remove :center
    end
  end
end
