defmodule DataAggregator.Repo.Migrations.AddNewDefaultApprovalStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :approval_status, :text, default: "not_approved"
    end
  end

  def down do
    alter table(:records) do
      modify :approval_status, :text, default: "not_published"
    end
  end
end
