defmodule DataAggregator.Repo.Migrations.PublicationStatusChangeToText do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :approval_status, :text
      modify :fast_track_status, :text
    end
  end

  def down do
    alter table(:records) do
      modify :fast_track_status, :map
      modify :approval_status, :map
    end
  end
end
