defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToImportRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:import_records, "import_records_record_id_fkey")

    alter table(:import_records) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "import_records_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    execute "UPDATE import_records SET collection_id = records.collection_id FROM records WHERE import_records.record_id = records.id"

    alter table(:import_records) do
      modify :collection_id, :uuid, null: false

      modify :record_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "import_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:import_records, "import_records_collection_id_fkey")

    drop constraint(:import_records, "import_records_record_id_fkey")

    alter table(:import_records) do
      modify :record_id,
             references(:records,
               column: :id,
               name: "import_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )

      remove :collection_id
    end
  end
end
