defmodule DataAggregator.Repo.Migrations.AddGrscicollInstitutionIdentifiersToCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      add :grscicoll_institution_key, :text
      add :grscicoll_institution_code, :text
    end
  end

  def down do
    alter table(:collections) do
      remove :grscicoll_institution_code
      remove :grscicoll_institution_key
    end
  end
end
