defmodule DataAggregator.Repo.Migrations.AddLastApprovalStartedAtRecordResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :last_approval_started_at, :utc_datetime
    end
  end

  def down do
    alter table(:records) do
      remove :last_approval_started_at
    end
  end
end
