defmodule DataAggregator.Repo.Migrations.AddIucnRedlistGeneratedColumnsToEncodedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:encoded_records) do
      add :iucn_redlist, :boolean,
        generated:
          "ALWAYS AS (iucn_redlist_category IN ('EX', 'EW', 'RE', 'CR(PE)', 'CR', 'EN')) STORED"
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :iucn_redlist
    end
  end
end
