defmodule DataAggregator.Repo.Migrations.TemporaryAddTaxKingdom do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :tax_kingdom, :text
    end

    alter table(:encoded_records) do
      add :tax_kingdom, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :tax_kingdom
    end

    alter table(:records) do
      remove :tax_kingdom
    end
  end
end
