defmodule DataAggregator.Repo.Migrations.CorrectPubStatusDefaultValue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :approval_status, :text, null: false, default: "not_published"
      modify :fast_track_status, :text, null: false, default: "not_published"
    end
  end

  def down do
    alter table(:records) do
      modify :fast_track_status, :text, null: true, default: nil
      modify :approval_status, :text, null: true, default: nil
    end
  end
end
