defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:records, [:collection_id])

    drop constraint(:records_versions, "records_versions_version_source_id_fkey")

    alter table(:records_versions) do
      add :collection_id, :uuid
    end

    execute "UPDATE records_versions SET collection_id = records.collection_id FROM records WHERE records_versions.version_source_id = records.id"

    alter table(:records_versions) do
      modify :collection_id, :uuid, null: false

      modify :version_source_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:records_versions, "records_versions_version_source_id_fkey")

    alter table(:records_versions) do
      modify :version_source_id,
             references(:records,
               column: :id,
               name: "records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:records, "records_collection_id_fkey")

    alter table(:records) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "records_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:records_versions) do
      remove :collection_id
    end

    create index(:records, [:collection_id])
  end
end
