defmodule DataAggregator.Repo.Migrations.AddForeignKeyIndeces do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:records, "records_fast_track_checker_job_id_fkey")

    alter table(:records) do
      modify :fast_track_checker_job_id,
             references(:oban_jobs,
               column: :id,
               name: "records_fast_track_checker_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:publications, "publications_job_id_fkey")

    alter table(:publications) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "publications_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:exports, "exports_job_id_fkey")

    alter table(:exports) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "exports_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:approvals, "approvals_job_id_fkey")

    alter table(:approvals) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "approvals_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    execute("ALTER TABLE approvals alter CONSTRAINT approvals_job_id_fkey NOT DEFERRABLE")

    create index(:approvals, [:job_id])

    execute("ALTER TABLE exports alter CONSTRAINT exports_job_id_fkey NOT DEFERRABLE")

    create index(:exports, [:job_id])

    execute("ALTER TABLE publications alter CONSTRAINT publications_job_id_fkey NOT DEFERRABLE")

    create index(:publications, [:job_id])

    execute(
      "ALTER TABLE records alter CONSTRAINT records_fast_track_checker_job_id_fkey NOT DEFERRABLE"
    )

    create index(:records, [:fast_track_checker_job_id])
  end

  def down do
    drop_if_exists index(:records, [:fast_track_checker_job_id])

    drop_if_exists index(:publications, [:job_id])

    drop_if_exists index(:exports, [:job_id])

    drop_if_exists index(:approvals, [:job_id])

    drop constraint(:approvals, "approvals_job_id_fkey")

    alter table(:approvals) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "approvals_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:exports, "exports_job_id_fkey")

    alter table(:exports) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "exports_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:publications, "publications_job_id_fkey")

    alter table(:publications) do
      modify :job_id,
             references(:oban_jobs,
               column: :id,
               name: "publications_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    drop constraint(:records, "records_fast_track_checker_job_id_fkey")

    alter table(:records) do
      modify :fast_track_checker_job_id,
             references(:oban_jobs,
               column: :id,
               name: "records_fast_track_checker_job_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end
  end
end
