defmodule DataAggregator.Repo.Migrations.RemoveUnusedAttributesFromImageUpload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      remove :images_mapped_count
      remove :images_count
    end
  end

  def down do
    alter table(:image_uploads) do
      add :images_count, :bigint
      add :images_mapped_count, :bigint
    end
  end
end
