defmodule DataAggregator.Repo.Migrations.UseAshEnumTypesForStateIndication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:exports) do
      add :header_source, :text, null: false, default: "collection_mapping"
      add :data_layer, :text, null: false, default: "raw"
    end
  end

  def down do
    alter table(:exports) do
      remove :data_layer
      remove :header_source
    end
  end
end
