defmodule DataAggregator.Repo.Migrations.AddAttributeBasedMultitenancyToImports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:import_records, "import_records_import_id_fkey")

    alter table(:import_records) do
      modify :import_id,
             references(:imports,
               column: :id,
               name: "import_records_import_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:import_records, "import_records_import_id_fkey")

    alter table(:import_records) do
      modify :import_id,
             references(:imports,
               column: :id,
               name: "import_records_import_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end
end
