defmodule DataAggregator.Repo.Migrations.ChangePvnPreservationTemperatureToText do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:records) do
    #   modify :pvn_preservation_temperature, :text
    # end

    # alter table(:encoded_records) do
    #   modify :pvn_preservation_temperature, :text
    # end

    # alter table(:approved_records) do
    #   modify :pvn_preservation_temperature, :text
    # end
  end

  def down do
    # alter table(:approved_records) do
    #   modify :pvn_preservation_temperature, :float
    # end

    # alter table(:encoded_records) do
    #   modify :pvn_preservation_temperature, :float
    # end

    # alter table(:records) do
    #   modify :pvn_preservation_temperature, :float
    # end
  end
end
