defmodule DataAggregator.Repo.Migrations.CreateApprovalResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :file_url, :text, null: false
      add :records_count, :bigint, default: 0
      add :records_approved, :bigint, default: 0
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "approvals_attachment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :job_id,
          references(:oban_jobs,
            column: :id,
            name: "approvals_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :state, :text, null: false, default: "pending"
    end
  end

  def down do
    drop constraint(:approvals, "approvals_attachment_id_fkey")

    drop constraint(:approvals, "approvals_job_id_fkey")

    drop table(:approvals)
  end
end
