defmodule DataAggregator.Repo.Migrations.AddOthModifiedField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :oth_modified, :text
    end

    alter table(:encoded_records) do
      add :oth_modified, :text
    end

    alter table(:approved_records) do
      add :oth_modified, :text
    end
  end

  def down do
    alter table(:approved_records) do
      remove :oth_modified
    end

    alter table(:encoded_records) do
      remove :oth_modified
    end

    alter table(:records) do
      remove :oth_modified
    end
  end
end
