defmodule DataAggregator.Repo.Migrations.AddLastImportedAtToRecordResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :last_imported_at, :utc_datetime
    end
  end

  def down do
    alter table(:records) do
      remove :last_imported_at
    end
  end
end
