defmodule DataAggregator.Repo.Migrations.AddLicenseToPublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      add :license, :text, null: false, default: "cc0"
    end
  end

  def down do
    alter table(:publications) do
      remove :license
    end
  end
end
