defmodule DataAggregator.Repo.Migrations.AddLocationAttributesToSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :loc_municipality, :text
      add :loc_county, :text
      add :loc_city, :text
      add :loc_swiss_coordinates_y, :float
      add :loc_swiss_coordinates_x, :float
      add :loc_country_code, :text
    end

    alter table(:encoded_records) do
      add :loc_municipality, :text
      add :loc_county, :text
      add :loc_city, :text
      add :loc_swiss_coordinates_y, :float
      add :loc_swiss_coordinates_x, :float
      add :loc_country_code, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :loc_country_code
      remove :loc_swiss_coordinates_x
      remove :loc_swiss_coordinates_y
      remove :loc_city
      remove :loc_county
      remove :loc_municipality
    end

    alter table(:records) do
      remove :loc_country_code
      remove :loc_swiss_coordinates_x
      remove :loc_swiss_coordinates_y
      remove :loc_city
      remove :loc_county
      remove :loc_municipality
    end
  end
end
