defmodule DataAggregator.Repo.Migrations.AddChangeEventResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:change_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :dwc_attribute, :text, null: false
      add :value, :text
      add :previous_value, :text
      add :category, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "change_events_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:change_events, "change_events_record_id_fkey")

    drop table(:change_events)
  end
end
