defmodule DataAggregator.Repo.Migrations.AddInvalidFileInfosToImageUpload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :invalid_file_infos, {:array, :map}
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :invalid_file_infos
    end
  end
end
