defmodule DataAggregator.Repo.Migrations.MakeDatamodelReadyForPublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records_versions) do
      remove :mte_material_entity_id
      add :mte_catalog_number, :text, null: false
    end

    alter table(:records) do
      remove :prs_contact_point
      remove :prs_first_name
      remove :prs_last_name
      remove :prs_date_of_birth
      remove :ref_bibliographic_citation
      remove :ref_creator
      remove :ref_date
      remove :ref_rights
      remove :ref_source
      remove :ref_title
      remove :ref_relationship_established_date
      remove :rrp_relationship_of_resource
      remove :rrp_relationship_of_resource_id
      remove :spp_life_stage
      remove :loc_city
      remove :occ_recorded_by
      remove :occ_sex
      remove :occ_associated_occurrences
      remove :occ_occurrence_remarks
      modify :mte_material_entity_id, :text, null: true
      add :ext_vernacular_names, :map
      add :ext_species_profile, :map
      add :ext_species_distribution, :map
      add :ext_references, :map
      add :ext_resource_relationship, :map
      add :ext_permit, :map
      add :ext_chronometric, :map
      add :ext_assertions, :map
      add :ext_amplification, :map
      add :oth_specify_author_of_record, :text
      add :oth_specify_event, :text
      add :oth_specify_locality, :text
      add :oth_specify_organism_name, :text
      add :oth_specify_person, :text
      add :oth_type, :text
      add :oth_rights_holder, :text
      add :oth_owner_institution_code, :text
      add :oth_modified_by, :text
      add :oth_license, :text
      add :oth_language, :text
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_information_withheld, :text
      add :oth_date_available, :text
      add :oth_dataset_name, :text
      add :oth_dataset_id, :text
      add :oth_data_generalizations, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
      add :oth_bibliographic_citation, :text
      add :oth_basis_of_record, :text
      add :oth_access_rights, :text
      add :pvn_tissue_bank_institution, :text
      add :pvn_storage_name, :text
      add :pvn_preservation_type, :text
      add :pvn_sequence, :text
      add :pvn_preservation_temperature, :text
      add :pvn_preservation_special_mode, :text
      add :pvn_preservation_quality, :text
      add :pvn_preservation_mode_text, :text
      add :pvn_preservation_mode_keywords, :text
      add :pvn_preservation_method, :text
      add :pvn_preservation_id, :text
      add :pvn_preservation_date_begin, :text
      add :pvn_preservation_alteration_text, :text
      add :pvn_dna_storage_code, :text
      add :pvn_dna_bank_institution, :text
      add :occ_occurrence_id, :text
      add :org_organism_remarks, :text
      add :org_organism_scope, :text
      add :org_organism_name, :text
      add :org_organism_id, :text
      add :org_pathway, :text
      add :org_degree_of_establishment, :text
      add :org_establishment_means, :text
      add :org_sex, :text
      add :gec_place_of_origin, :text
      add :gec_member, :text
      add :gec_group, :text
      add :gec_formation, :text
      add :gec_lithostratigraphic_terms, :text
      add :gec_highest_biostratigraphic_zone, :text
      add :gec_lowest_biostratigraphic_zone, :text
      add :gec_latest_age_or_highest_stage, :text
      add :gec_latest_epoch_or_highest_series, :text
      add :gec_latest_period_or_highest_system, :text
      add :gec_latest_era_or_highest_erathem, :text
      add :gec_latest_eon_or_highest_eonothem, :text
      add :gec_earliest_period_or_lowest_system, :text
      add :gec_earliest_era_or_lowest_erathem, :text
      add :gec_earliest_epoch_or_lowest_series, :text
      add :gec_earliest_eon_or_lowest_eonothem, :text
      add :gec_earliest_age_or_lowest_stage, :text
      add :gec_bed, :text
      add :gec_geological_context_id, :text
      add :mts_material_sample_id, :text
      add :mte_original_biominerals, :text
      add :mte_orig_col_author, :text
      add :mte_year_collection_entrance, :bigint
      add :mte_tissue_bank_id, :text
      add :mte_taphonomy, :text
      add :mte_sample_designation, :text
      add :mte_orientation, :text
      add :mte_organism_quantity_method, :text
      add :mte_mineralization, :text
      add :mte_matrix, :text
      add :mte_gbif_doi, :text
      add :mte_form, :text
      add :mte_feeding_predation_traces, :text
      add :mte_extraction_temporary_id, :text
      add :mte_encrustation, :text
      add :mte_dna_stable_id, :text
      add :mte_dna_bank_id, :text
      add :mte_depositional_environment_type, :text
      add :mte_depositional_environment_text, :text
      add :mte_completeness, :text
      add :mte_paleo_completeness, :text
      add :mte_catalog_number, :text, null: false
      add :mte_bioerosion, :text
      add :mte_assemblage_origin, :text
      add :mte_articulation, :text
      add :mte_permit_id, :text
      add :mte_replacement_minerals, :text
      add :mte_barcode_label, :text
      add :mte_references, :text
      add :mte_other_catalog_numbers, :text
      add :mte_associated_media, :text
      add :mte_occurrence_status, :text
      add :mte_behavior, :text
      add :mte_reproductive_condition, :text
      add :mte_life_stage, :text
      add :mte_organism_quantity_type, :text
      add :mte_organism_quantity, :text
      add :mte_recorded_by_id, :text
      add :mte_recorded_by, :text
      add :mte_record_number, :text
      add :mte_material_entity_remarks, :text
      add :mte_preparations, :text
      add :mte_verbatim_label, :text
      add :mte_post_burial_transportation, :text
      add :mte_part_of_organism, :text
      add :mte_parent_material_entity_id, :text
      add :mte_anatomical_description, :text
      add :loc_georeference_verification_status, :text
      add :loc_georeference_sources, :text
      add :loc_georeference_protocol, :text
      add :loc_georeferenced_date, :date
      add :loc_georeferenced_by, :text
      add :loc_footprint_spatial_fit, :float
      add :loc_footprint_srs, :text
      add :loc_footprint_wkt, :text
      add :loc_verbatim_srs, :text
      add :loc_verbatim_coordinate_system, :text
      add :loc_verbatim_longitude, :text
      add :loc_verbatim_latitude, :text
      add :loc_verbatim_coordinates, :text
      add :loc_point_radius_spatial_fit, :float
      add :loc_coordinate_precision, :float
      add :loc_coordinate_uncertainty_in_meters, :bigint
      add :loc_geodetic_datum, :text
      add :loc_location_remarks, :text
      add :loc_location_according_to, :text
      add :loc_maximum_distance_above_surface_in_meters, :bigint
      add :loc_minimum_distance_above_surface_in_meters, :bigint
      add :loc_verbatim_depth, :bigint
      add :loc_maximum_depth_in_meters, :bigint
      add :loc_minimum_depth_in_meters, :bigint
      add :loc_vertical_datum, :text
      add :loc_verbatim_elevation, :text
      add :loc_maximum_elevation_in_meters, :bigint
      add :loc_minimum_elevation_in_meters, :bigint
      add :loc_island, :text
      add :loc_island_group, :text
      add :loc_higher_geography, :text
      add :loc_water_body_id, :text
      add :loc_water_body, :text
      add :loc_higher_geography_id, :text
      add :loc_location_id, :text
      add :tax_taxon_remarks, :text
      add :tax_nomenclatural_status, :text
      add :tax_taxonomic_status, :text
      add :tax_nomenclatural_code, :text
      add :tax_vernacular_name, :text
      add :tax_verbatim_taxon_rank, :text
      add :tax_cultivar_epithet, :text
      add :tax_infrageneric_epithet, :text
      add :tax_generic_name, :text
      add :tax_sub_tribe, :text
      add :tax_tribe, :text
      add :tax_sub_genus, :text
      add :tax_subfamily, :text
      add :tax_superfamily, :text
      add :tax_taxon_concept_id, :text
      add :tax_higher_classification, :text
      add :tax_name_published_in_year, :text
      add :tax_name_published_in, :text
      add :tax_name_published_in_id, :text
      add :tax_name_according_to, :text
      add :tax_name_according_to_id, :text
      add :tax_original_name_usage, :text
      add :tax_original_name_usage_id, :text
      add :tax_parent_name_usage, :text
      add :tax_parent_name_usage_id, :text
      add :tax_scientific_name_id, :text
      add :tax_identifier, :bigint
      add :idf_last_verified_by_id, :text
      add :idf_last_verified_by, :text
      add :idf_verbatim_identification, :text
      add :idf_previous_identifications, :text
      add :idf_identified_by_id, :text
      add :idf_identification_verification_status, :text
      add :idf_identification_remarks, :text
      add :idf_identification_reference, :text
      add :idf_identification_qualifier, :text
      add :idf_evidence_type, :text
      add :eve_shrub_layer_height_in_meters, :float
      add :eve_start_day_of_year, :text
      add :eve_sampling_effort, :text
      add :eve_sample_size_unit, :bigint
      add :eve_sample_size_value, :bigint
      add :eve_sampling_protocol, :text
      add :eve_substratum_state, :text
      add :eve_substratum, :text
      add :eve_micro_structure, :text
      add :eve_landscape_structure, :text
      add :eve_influence, :text
      add :eve_habitat_ref, :text
      add :eve_habitat_inclusion, :text
      add :eve_habitat_contact, :text
      add :eve_habitat_code, :text
      add :eve_tree_layer_height_in_meters, :bigint
      add :eve_syntaxon_name, :text
      add :eve_project, :text
      add :eve_mosses_identified, :boolean
      add :eve_lichens_identified, :boolean
      add :eve_inclination_in_degrees, :bigint
      add :eve_herb_layer_height_in_centimeters, :bigint
      add :eve_event_remarks, :text
      add :eve_field_notes, :text
      add :eve_habitat, :text
      add :eve_verbatim_event_date, :text
      add :eve_end_day_of_year, :bigint
      add :eve_event_time, :text
      add :eve_field_number, :text
      add :eve_parent_event_id, :text
      add :eve_event_id, :text
      add :eve_cover_water_in_percentage, :float
      add :eve_cover_trees_in_percentage, :float
      add :eve_cover_toal_in_percentage, :float
      add :eve_cover_shrubs_in_percentage, :float
      add :eve_cover_rock_in_percentage, :float
      add :eve_cover_mosses_in_percentage, :float
      add :eve_cover_litter_in_percentage, :float
      add :eve_cover_lychens_in_percentage, :float
      add :eve_cover_herbs_in_percentage, :float
      add :eve_cover_cryptogams_in_percentage, :float
      add :eve_cover_algae_in_percentage, :float
      add :eve_aspect, :text
    end

    drop_if_exists unique_index(:records, [:collection_id, :mte_material_entity_id],
                     name: "records_collection_mte_material_entity_id_index"
                   )

    create unique_index(:records, [:collection_id, :mte_catalog_number],
             name: "records_collection_mte_catalog_number_index"
           )

    alter table(:encoded_records) do
      remove :prs_contact_point
      remove :prs_first_name
      remove :prs_last_name
      remove :prs_date_of_birth
      remove :ref_bibliographic_citation
      remove :ref_creator
      remove :ref_date
      remove :ref_rights
      remove :ref_source
      remove :ref_title
      remove :ref_relationship_established_date
      remove :rrp_relationship_of_resource
      remove :rrp_relationship_of_resource_id
      remove :spp_life_stage
      remove :loc_city
      remove :occ_recorded_by
      remove :occ_sex
      remove :occ_associated_occurrences
      remove :occ_occurrence_remarks
      modify :mte_material_entity_id, :text, null: true
      add :ext_vernacular_names, :map
      add :ext_species_profile, :map
      add :ext_species_distribution, :map
      add :ext_references, :map
      add :ext_resource_relationship, :map
      add :ext_permit, :map
      add :ext_chronometric, :map
      add :ext_assertions, :map
      add :ext_amplification, :map
      add :oth_specify_author_of_record, :text
      add :oth_specify_event, :text
      add :oth_specify_locality, :text
      add :oth_specify_organism_name, :text
      add :oth_specify_person, :text
      add :oth_type, :text
      add :oth_rights_holder, :text
      add :oth_owner_institution_code, :text
      add :oth_modified_by, :text
      add :oth_license, :text
      add :oth_language, :text
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_information_withheld, :text
      add :oth_date_available, :text
      add :oth_dataset_name, :text
      add :oth_dataset_id, :text
      add :oth_data_generalizations, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
      add :oth_bibliographic_citation, :text
      add :oth_basis_of_record, :text
      add :oth_access_rights, :text
      add :pvn_tissue_bank_institution, :text
      add :pvn_storage_name, :text
      add :pvn_preservation_type, :text
      add :pvn_sequence, :text
      add :pvn_preservation_temperature, :text
      add :pvn_preservation_special_mode, :text
      add :pvn_preservation_quality, :text
      add :pvn_preservation_mode_text, :text
      add :pvn_preservation_mode_keywords, :text
      add :pvn_preservation_method, :text
      add :pvn_preservation_id, :text
      add :pvn_preservation_date_begin, :text
      add :pvn_preservation_alteration_text, :text
      add :pvn_dna_storage_code, :text
      add :pvn_dna_bank_institution, :text
      add :occ_occurrence_id, :text
      add :org_organism_remarks, :text
      add :org_organism_scope, :text
      add :org_organism_name, :text
      add :org_organism_id, :text
      add :org_pathway, :text
      add :org_degree_of_establishment, :text
      add :org_establishment_means, :text
      add :org_sex, :text
      add :gec_place_of_origin, :text
      add :gec_member, :text
      add :gec_group, :text
      add :gec_formation, :text
      add :gec_lithostratigraphic_terms, :text
      add :gec_highest_biostratigraphic_zone, :text
      add :gec_lowest_biostratigraphic_zone, :text
      add :gec_latest_age_or_highest_stage, :text
      add :gec_latest_epoch_or_highest_series, :text
      add :gec_latest_period_or_highest_system, :text
      add :gec_latest_era_or_highest_erathem, :text
      add :gec_latest_eon_or_highest_eonothem, :text
      add :gec_earliest_period_or_lowest_system, :text
      add :gec_earliest_era_or_lowest_erathem, :text
      add :gec_earliest_epoch_or_lowest_series, :text
      add :gec_earliest_eon_or_lowest_eonothem, :text
      add :gec_earliest_age_or_lowest_stage, :text
      add :gec_bed, :text
      add :gec_geological_context_id, :text
      add :mts_material_sample_id, :text
      add :mte_original_biominerals, :text
      add :mte_orig_col_author, :text
      add :mte_year_collection_entrance, :bigint
      add :mte_tissue_bank_id, :text
      add :mte_taphonomy, :text
      add :mte_sample_designation, :text
      add :mte_orientation, :text
      add :mte_organism_quantity_method, :text
      add :mte_mineralization, :text
      add :mte_matrix, :text
      add :mte_gbif_doi, :text
      add :mte_form, :text
      add :mte_feeding_predation_traces, :text
      add :mte_extraction_temporary_id, :text
      add :mte_encrustation, :text
      add :mte_dna_stable_id, :text
      add :mte_dna_bank_id, :text
      add :mte_depositional_environment_type, :text
      add :mte_depositional_environment_text, :text
      add :mte_completeness, :text
      add :mte_paleo_completeness, :text
      add :mte_catalog_number, :text, null: false
      add :mte_bioerosion, :text
      add :mte_assemblage_origin, :text
      add :mte_articulation, :text
      add :mte_permit_id, :text
      add :mte_replacement_minerals, :text
      add :mte_barcode_label, :text
      add :mte_references, :text
      add :mte_other_catalog_numbers, :text
      add :mte_associated_media, :text
      add :mte_occurrence_status, :text
      add :mte_behavior, :text
      add :mte_reproductive_condition, :text
      add :mte_life_stage, :text
      add :mte_organism_quantity_type, :text
      add :mte_organism_quantity, :text
      add :mte_recorded_by_id, :text
      add :mte_recorded_by, :text
      add :mte_record_number, :text
      add :mte_material_entity_remarks, :text
      add :mte_preparations, :text
      add :mte_verbatim_label, :text
      add :mte_post_burial_transportation, :text
      add :mte_part_of_organism, :text
      add :mte_parent_material_entity_id, :text
      add :mte_anatomical_description, :text
      add :loc_georeference_verification_status, :text
      add :loc_georeference_sources, :text
      add :loc_georeference_protocol, :text
      add :loc_georeferenced_date, :date
      add :loc_georeferenced_by, :text
      add :loc_footprint_spatial_fit, :float
      add :loc_footprint_srs, :text
      add :loc_footprint_wkt, :text
      add :loc_verbatim_srs, :text
      add :loc_verbatim_coordinate_system, :text
      add :loc_verbatim_longitude, :text
      add :loc_verbatim_latitude, :text
      add :loc_verbatim_coordinates, :text
      add :loc_point_radius_spatial_fit, :float
      add :loc_coordinate_precision, :float
      add :loc_coordinate_uncertainty_in_meters, :bigint
      add :loc_geodetic_datum, :text
      add :loc_location_remarks, :text
      add :loc_location_according_to, :text
      add :loc_maximum_distance_above_surface_in_meters, :bigint
      add :loc_minimum_distance_above_surface_in_meters, :bigint
      add :loc_verbatim_depth, :bigint
      add :loc_maximum_depth_in_meters, :bigint
      add :loc_minimum_depth_in_meters, :bigint
      add :loc_vertical_datum, :text
      add :loc_verbatim_elevation, :text
      add :loc_maximum_elevation_in_meters, :bigint
      add :loc_minimum_elevation_in_meters, :bigint
      add :loc_island, :text
      add :loc_island_group, :text
      add :loc_higher_geography, :text
      add :loc_water_body_id, :text
      add :loc_water_body, :text
      add :loc_higher_geography_id, :text
      add :loc_location_id, :text
      add :tax_taxon_remarks, :text
      add :tax_nomenclatural_status, :text
      add :tax_taxonomic_status, :text
      add :tax_nomenclatural_code, :text
      add :tax_vernacular_name, :text
      add :tax_verbatim_taxon_rank, :text
      add :tax_cultivar_epithet, :text
      add :tax_infrageneric_epithet, :text
      add :tax_generic_name, :text
      add :tax_sub_tribe, :text
      add :tax_tribe, :text
      add :tax_sub_genus, :text
      add :tax_subfamily, :text
      add :tax_superfamily, :text
      add :tax_taxon_concept_id, :text
      add :tax_higher_classification, :text
      add :tax_name_published_in_year, :text
      add :tax_name_published_in, :text
      add :tax_name_published_in_id, :text
      add :tax_name_according_to, :text
      add :tax_name_according_to_id, :text
      add :tax_original_name_usage, :text
      add :tax_original_name_usage_id, :text
      add :tax_parent_name_usage, :text
      add :tax_parent_name_usage_id, :text
      add :tax_scientific_name_id, :text
      add :tax_identifier, :bigint
      add :idf_last_verified_by_id, :text
      add :idf_last_verified_by, :text
      add :idf_verbatim_identification, :text
      add :idf_previous_identifications, :text
      add :idf_identified_by_id, :text
      add :idf_identification_verification_status, :text
      add :idf_identification_remarks, :text
      add :idf_identification_reference, :text
      add :idf_identification_qualifier, :text
      add :idf_evidence_type, :text
      add :eve_shrub_layer_height_in_meters, :float
      add :eve_start_day_of_year, :text
      add :eve_sampling_effort, :text
      add :eve_sample_size_unit, :bigint
      add :eve_sample_size_value, :bigint
      add :eve_sampling_protocol, :text
      add :eve_substratum_state, :text
      add :eve_substratum, :text
      add :eve_micro_structure, :text
      add :eve_landscape_structure, :text
      add :eve_influence, :text
      add :eve_habitat_ref, :text
      add :eve_habitat_inclusion, :text
      add :eve_habitat_contact, :text
      add :eve_habitat_code, :text
      add :eve_tree_layer_height_in_meters, :bigint
      add :eve_syntaxon_name, :text
      add :eve_project, :text
      add :eve_mosses_identified, :boolean
      add :eve_lichens_identified, :boolean
      add :eve_inclination_in_degrees, :bigint
      add :eve_herb_layer_height_in_centimeters, :bigint
      add :eve_event_remarks, :text
      add :eve_field_notes, :text
      add :eve_habitat, :text
      add :eve_verbatim_event_date, :text
      add :eve_end_day_of_year, :bigint
      add :eve_event_time, :text
      add :eve_field_number, :text
      add :eve_parent_event_id, :text
      add :eve_event_id, :text
      add :eve_cover_water_in_percentage, :float
      add :eve_cover_trees_in_percentage, :float
      add :eve_cover_toal_in_percentage, :float
      add :eve_cover_shrubs_in_percentage, :float
      add :eve_cover_rock_in_percentage, :float
      add :eve_cover_mosses_in_percentage, :float
      add :eve_cover_litter_in_percentage, :float
      add :eve_cover_lychens_in_percentage, :float
      add :eve_cover_herbs_in_percentage, :float
      add :eve_cover_cryptogams_in_percentage, :float
      add :eve_cover_algae_in_percentage, :float
      add :eve_aspect, :text
    end

    drop_if_exists unique_index(:encoded_records, [:mte_material_entity_id, :record_id],
                     name: "encoded_records_record_mte_material_entity_id_index"
                   )

    create unique_index(:encoded_records, [:record_id, :mte_catalog_number],
             name: "encoded_records_record_mte_catalog_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:encoded_records, [:record_id, :mte_catalog_number],
                     name: "encoded_records_record_mte_catalog_number_index"
                   )

    create unique_index(:encoded_records, [:mte_material_entity_id, :record_id],
             name: "encoded_records_record_mte_material_entity_id_index"
           )

    alter table(:encoded_records) do
      remove :eve_aspect
      remove :eve_cover_algae_in_percentage
      remove :eve_cover_cryptogams_in_percentage
      remove :eve_cover_herbs_in_percentage
      remove :eve_cover_lychens_in_percentage
      remove :eve_cover_litter_in_percentage
      remove :eve_cover_mosses_in_percentage
      remove :eve_cover_rock_in_percentage
      remove :eve_cover_shrubs_in_percentage
      remove :eve_cover_toal_in_percentage
      remove :eve_cover_trees_in_percentage
      remove :eve_cover_water_in_percentage
      remove :eve_event_id
      remove :eve_parent_event_id
      remove :eve_field_number
      remove :eve_event_time
      remove :eve_end_day_of_year
      remove :eve_verbatim_event_date
      remove :eve_habitat
      remove :eve_field_notes
      remove :eve_event_remarks
      remove :eve_herb_layer_height_in_centimeters
      remove :eve_inclination_in_degrees
      remove :eve_lichens_identified
      remove :eve_mosses_identified
      remove :eve_project
      remove :eve_syntaxon_name
      remove :eve_tree_layer_height_in_meters
      remove :eve_habitat_code
      remove :eve_habitat_contact
      remove :eve_habitat_inclusion
      remove :eve_habitat_ref
      remove :eve_influence
      remove :eve_landscape_structure
      remove :eve_micro_structure
      remove :eve_substratum
      remove :eve_substratum_state
      remove :eve_sampling_protocol
      remove :eve_sample_size_value
      remove :eve_sample_size_unit
      remove :eve_sampling_effort
      remove :eve_start_day_of_year
      remove :eve_shrub_layer_height_in_meters
      remove :idf_evidence_type
      remove :idf_identification_qualifier
      remove :idf_identification_reference
      remove :idf_identification_remarks
      remove :idf_identification_verification_status
      remove :idf_identified_by_id
      remove :idf_previous_identifications
      remove :idf_verbatim_identification
      remove :idf_last_verified_by
      remove :idf_last_verified_by_id
      remove :tax_identifier
      remove :tax_scientific_name_id
      remove :tax_parent_name_usage_id
      remove :tax_parent_name_usage
      remove :tax_original_name_usage_id
      remove :tax_original_name_usage
      remove :tax_name_according_to_id
      remove :tax_name_according_to
      remove :tax_name_published_in_id
      remove :tax_name_published_in
      remove :tax_name_published_in_year
      remove :tax_higher_classification
      remove :tax_taxon_concept_id
      remove :tax_superfamily
      remove :tax_subfamily
      remove :tax_sub_genus
      remove :tax_tribe
      remove :tax_sub_tribe
      remove :tax_generic_name
      remove :tax_infrageneric_epithet
      remove :tax_cultivar_epithet
      remove :tax_verbatim_taxon_rank
      remove :tax_vernacular_name
      remove :tax_nomenclatural_code
      remove :tax_taxonomic_status
      remove :tax_nomenclatural_status
      remove :tax_taxon_remarks
      remove :loc_location_id
      remove :loc_higher_geography_id
      remove :loc_water_body
      remove :loc_water_body_id
      remove :loc_higher_geography
      remove :loc_island_group
      remove :loc_island
      remove :loc_minimum_elevation_in_meters
      remove :loc_maximum_elevation_in_meters
      remove :loc_verbatim_elevation
      remove :loc_vertical_datum
      remove :loc_minimum_depth_in_meters
      remove :loc_maximum_depth_in_meters
      remove :loc_verbatim_depth
      remove :loc_minimum_distance_above_surface_in_meters
      remove :loc_maximum_distance_above_surface_in_meters
      remove :loc_location_according_to
      remove :loc_location_remarks
      remove :loc_geodetic_datum
      remove :loc_coordinate_uncertainty_in_meters
      remove :loc_coordinate_precision
      remove :loc_point_radius_spatial_fit
      remove :loc_verbatim_coordinates
      remove :loc_verbatim_latitude
      remove :loc_verbatim_longitude
      remove :loc_verbatim_coordinate_system
      remove :loc_verbatim_srs
      remove :loc_footprint_wkt
      remove :loc_footprint_srs
      remove :loc_footprint_spatial_fit
      remove :loc_georeferenced_by
      remove :loc_georeferenced_date
      remove :loc_georeference_protocol
      remove :loc_georeference_sources
      remove :loc_georeference_verification_status
      remove :mte_anatomical_description
      remove :mte_parent_material_entity_id
      remove :mte_part_of_organism
      remove :mte_post_burial_transportation
      remove :mte_verbatim_label
      remove :mte_preparations
      remove :mte_material_entity_remarks
      remove :mte_record_number
      remove :mte_recorded_by
      remove :mte_recorded_by_id
      remove :mte_organism_quantity
      remove :mte_organism_quantity_type
      remove :mte_life_stage
      remove :mte_reproductive_condition
      remove :mte_behavior
      remove :mte_occurrence_status
      remove :mte_associated_media
      remove :mte_other_catalog_numbers
      remove :mte_references
      remove :mte_barcode_label
      remove :mte_replacement_minerals
      remove :mte_permit_id
      remove :mte_articulation
      remove :mte_assemblage_origin
      remove :mte_bioerosion
      remove :mte_catalog_number
      remove :mte_paleo_completeness
      remove :mte_completeness
      remove :mte_depositional_environment_text
      remove :mte_depositional_environment_type
      remove :mte_dna_bank_id
      remove :mte_dna_stable_id
      remove :mte_encrustation
      remove :mte_extraction_temporary_id
      remove :mte_feeding_predation_traces
      remove :mte_form
      remove :mte_gbif_doi
      remove :mte_matrix
      remove :mte_mineralization
      remove :mte_organism_quantity_method
      remove :mte_orientation
      remove :mte_sample_designation
      remove :mte_taphonomy
      remove :mte_tissue_bank_id
      remove :mte_year_collection_entrance
      remove :mte_orig_col_author
      remove :mte_original_biominerals
      remove :mts_material_sample_id
      remove :gec_geological_context_id
      remove :gec_bed
      remove :gec_earliest_age_or_lowest_stage
      remove :gec_earliest_eon_or_lowest_eonothem
      remove :gec_earliest_epoch_or_lowest_series
      remove :gec_earliest_era_or_lowest_erathem
      remove :gec_earliest_period_or_lowest_system
      remove :gec_latest_eon_or_highest_eonothem
      remove :gec_latest_era_or_highest_erathem
      remove :gec_latest_period_or_highest_system
      remove :gec_latest_epoch_or_highest_series
      remove :gec_latest_age_or_highest_stage
      remove :gec_lowest_biostratigraphic_zone
      remove :gec_highest_biostratigraphic_zone
      remove :gec_lithostratigraphic_terms
      remove :gec_formation
      remove :gec_group
      remove :gec_member
      remove :gec_place_of_origin
      remove :org_sex
      remove :org_establishment_means
      remove :org_degree_of_establishment
      remove :org_pathway
      remove :org_organism_id
      remove :org_organism_name
      remove :org_organism_scope
      remove :org_organism_remarks
      remove :occ_occurrence_id
      remove :pvn_dna_bank_institution
      remove :pvn_dna_storage_code
      remove :pvn_preservation_alteration_text
      remove :pvn_preservation_date_begin
      remove :pvn_preservation_id
      remove :pvn_preservation_method
      remove :pvn_preservation_mode_keywords
      remove :pvn_preservation_mode_text
      remove :pvn_preservation_quality
      remove :pvn_preservation_special_mode
      remove :pvn_preservation_temperature
      remove :pvn_sequence
      remove :pvn_preservation_type
      remove :pvn_storage_name
      remove :pvn_tissue_bank_institution
      remove :oth_access_rights
      remove :oth_basis_of_record
      remove :oth_bibliographic_citation
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_data_generalizations
      remove :oth_dataset_id
      remove :oth_dataset_name
      remove :oth_date_available
      remove :oth_information_withheld
      remove :oth_institution_code
      remove :oth_institution_id
      remove :oth_language
      remove :oth_license
      remove :oth_modified_by
      remove :oth_owner_institution_code
      remove :oth_rights_holder
      remove :oth_type
      remove :oth_specify_person
      remove :oth_specify_organism_name
      remove :oth_specify_locality
      remove :oth_specify_event
      remove :oth_specify_author_of_record
      remove :ext_amplification
      remove :ext_assertions
      remove :ext_chronometric
      remove :ext_permit
      remove :ext_resource_relationship
      remove :ext_references
      remove :ext_species_distribution
      remove :ext_species_profile
      remove :ext_vernacular_names
      modify :mte_material_entity_id, :text, null: false
      # This is the `down` migration of the statement:
      #
      #     remove :occ_occurrence_remarks
      #

      # add :occ_occurrence_remarks, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_associated_occurrences
      #

      # add :occ_associated_occurrences, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_sex
      #

      # add :occ_sex, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_recorded_by
      #

      # add :occ_recorded_by, :text
      # This is the `down` migration of the statement:
      #
      #     remove :loc_city
      #

      # add :loc_city, :text
      # This is the `down` migration of the statement:
      #
      #     remove :spp_life_stage
      #

      # add :spp_life_stage, :text
      # This is the `down` migration of the statement:
      #
      #     remove :rrp_relationship_of_resource_id
      #

      # add :rrp_relationship_of_resource_id, :text
      # This is the `down` migration of the statement:
      #
      #     remove :rrp_relationship_of_resource
      #

      # add :rrp_relationship_of_resource, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_relationship_established_date
      #

      # add :ref_relationship_established_date, :date
      # This is the `down` migration of the statement:
      #
      #     remove :ref_title
      #

      # add :ref_title, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_source
      #

      # add :ref_source, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_rights
      #

      # add :ref_rights, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_date
      #

      # add :ref_date, :date
      # This is the `down` migration of the statement:
      #
      #     remove :ref_creator
      #

      # add :ref_creator, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_bibliographic_citation
      #

      # add :ref_bibliographic_citation, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_date_of_birth
      #

      # add :prs_date_of_birth, :date
      # This is the `down` migration of the statement:
      #
      #     remove :prs_last_name
      #

      # add :prs_last_name, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_first_name
      #

      # add :prs_first_name, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_contact_point
      #

      # add :prs_contact_point, :text
    end

    drop_if_exists unique_index(:records, [:collection_id, :mte_catalog_number],
                     name: "records_collection_mte_catalog_number_index"
                   )

    create unique_index(:records, [:collection_id, :mte_material_entity_id],
             name: "records_collection_mte_material_entity_id_index"
           )

    alter table(:records) do
      remove :eve_aspect
      remove :eve_cover_algae_in_percentage
      remove :eve_cover_cryptogams_in_percentage
      remove :eve_cover_herbs_in_percentage
      remove :eve_cover_lychens_in_percentage
      remove :eve_cover_litter_in_percentage
      remove :eve_cover_mosses_in_percentage
      remove :eve_cover_rock_in_percentage
      remove :eve_cover_shrubs_in_percentage
      remove :eve_cover_toal_in_percentage
      remove :eve_cover_trees_in_percentage
      remove :eve_cover_water_in_percentage
      remove :eve_event_id
      remove :eve_parent_event_id
      remove :eve_field_number
      remove :eve_event_time
      remove :eve_end_day_of_year
      remove :eve_verbatim_event_date
      remove :eve_habitat
      remove :eve_field_notes
      remove :eve_event_remarks
      remove :eve_herb_layer_height_in_centimeters
      remove :eve_inclination_in_degrees
      remove :eve_lichens_identified
      remove :eve_mosses_identified
      remove :eve_project
      remove :eve_syntaxon_name
      remove :eve_tree_layer_height_in_meters
      remove :eve_habitat_code
      remove :eve_habitat_contact
      remove :eve_habitat_inclusion
      remove :eve_habitat_ref
      remove :eve_influence
      remove :eve_landscape_structure
      remove :eve_micro_structure
      remove :eve_substratum
      remove :eve_substratum_state
      remove :eve_sampling_protocol
      remove :eve_sample_size_value
      remove :eve_sample_size_unit
      remove :eve_sampling_effort
      remove :eve_start_day_of_year
      remove :eve_shrub_layer_height_in_meters
      remove :idf_evidence_type
      remove :idf_identification_qualifier
      remove :idf_identification_reference
      remove :idf_identification_remarks
      remove :idf_identification_verification_status
      remove :idf_identified_by_id
      remove :idf_previous_identifications
      remove :idf_verbatim_identification
      remove :idf_last_verified_by
      remove :idf_last_verified_by_id
      remove :tax_identifier
      remove :tax_scientific_name_id
      remove :tax_parent_name_usage_id
      remove :tax_parent_name_usage
      remove :tax_original_name_usage_id
      remove :tax_original_name_usage
      remove :tax_name_according_to_id
      remove :tax_name_according_to
      remove :tax_name_published_in_id
      remove :tax_name_published_in
      remove :tax_name_published_in_year
      remove :tax_higher_classification
      remove :tax_taxon_concept_id
      remove :tax_superfamily
      remove :tax_subfamily
      remove :tax_sub_genus
      remove :tax_tribe
      remove :tax_sub_tribe
      remove :tax_generic_name
      remove :tax_infrageneric_epithet
      remove :tax_cultivar_epithet
      remove :tax_verbatim_taxon_rank
      remove :tax_vernacular_name
      remove :tax_nomenclatural_code
      remove :tax_taxonomic_status
      remove :tax_nomenclatural_status
      remove :tax_taxon_remarks
      remove :loc_location_id
      remove :loc_higher_geography_id
      remove :loc_water_body
      remove :loc_water_body_id
      remove :loc_higher_geography
      remove :loc_island_group
      remove :loc_island
      remove :loc_minimum_elevation_in_meters
      remove :loc_maximum_elevation_in_meters
      remove :loc_verbatim_elevation
      remove :loc_vertical_datum
      remove :loc_minimum_depth_in_meters
      remove :loc_maximum_depth_in_meters
      remove :loc_verbatim_depth
      remove :loc_minimum_distance_above_surface_in_meters
      remove :loc_maximum_distance_above_surface_in_meters
      remove :loc_location_according_to
      remove :loc_location_remarks
      remove :loc_geodetic_datum
      remove :loc_coordinate_uncertainty_in_meters
      remove :loc_coordinate_precision
      remove :loc_point_radius_spatial_fit
      remove :loc_verbatim_coordinates
      remove :loc_verbatim_latitude
      remove :loc_verbatim_longitude
      remove :loc_verbatim_coordinate_system
      remove :loc_verbatim_srs
      remove :loc_footprint_wkt
      remove :loc_footprint_srs
      remove :loc_footprint_spatial_fit
      remove :loc_georeferenced_by
      remove :loc_georeferenced_date
      remove :loc_georeference_protocol
      remove :loc_georeference_sources
      remove :loc_georeference_verification_status
      remove :mte_anatomical_description
      remove :mte_parent_material_entity_id
      remove :mte_part_of_organism
      remove :mte_post_burial_transportation
      remove :mte_verbatim_label
      remove :mte_preparations
      remove :mte_material_entity_remarks
      remove :mte_record_number
      remove :mte_recorded_by
      remove :mte_recorded_by_id
      remove :mte_organism_quantity
      remove :mte_organism_quantity_type
      remove :mte_life_stage
      remove :mte_reproductive_condition
      remove :mte_behavior
      remove :mte_occurrence_status
      remove :mte_associated_media
      remove :mte_other_catalog_numbers
      remove :mte_references
      remove :mte_barcode_label
      remove :mte_replacement_minerals
      remove :mte_permit_id
      remove :mte_articulation
      remove :mte_assemblage_origin
      remove :mte_bioerosion
      remove :mte_catalog_number
      remove :mte_paleo_completeness
      remove :mte_completeness
      remove :mte_depositional_environment_text
      remove :mte_depositional_environment_type
      remove :mte_dna_bank_id
      remove :mte_dna_stable_id
      remove :mte_encrustation
      remove :mte_extraction_temporary_id
      remove :mte_feeding_predation_traces
      remove :mte_form
      remove :mte_gbif_doi
      remove :mte_matrix
      remove :mte_mineralization
      remove :mte_organism_quantity_method
      remove :mte_orientation
      remove :mte_sample_designation
      remove :mte_taphonomy
      remove :mte_tissue_bank_id
      remove :mte_year_collection_entrance
      remove :mte_orig_col_author
      remove :mte_original_biominerals
      remove :mts_material_sample_id
      remove :gec_geological_context_id
      remove :gec_bed
      remove :gec_earliest_age_or_lowest_stage
      remove :gec_earliest_eon_or_lowest_eonothem
      remove :gec_earliest_epoch_or_lowest_series
      remove :gec_earliest_era_or_lowest_erathem
      remove :gec_earliest_period_or_lowest_system
      remove :gec_latest_eon_or_highest_eonothem
      remove :gec_latest_era_or_highest_erathem
      remove :gec_latest_period_or_highest_system
      remove :gec_latest_epoch_or_highest_series
      remove :gec_latest_age_or_highest_stage
      remove :gec_lowest_biostratigraphic_zone
      remove :gec_highest_biostratigraphic_zone
      remove :gec_lithostratigraphic_terms
      remove :gec_formation
      remove :gec_group
      remove :gec_member
      remove :gec_place_of_origin
      remove :org_sex
      remove :org_establishment_means
      remove :org_degree_of_establishment
      remove :org_pathway
      remove :org_organism_id
      remove :org_organism_name
      remove :org_organism_scope
      remove :org_organism_remarks
      remove :occ_occurrence_id
      remove :pvn_dna_bank_institution
      remove :pvn_dna_storage_code
      remove :pvn_preservation_alteration_text
      remove :pvn_preservation_date_begin
      remove :pvn_preservation_id
      remove :pvn_preservation_method
      remove :pvn_preservation_mode_keywords
      remove :pvn_preservation_mode_text
      remove :pvn_preservation_quality
      remove :pvn_preservation_special_mode
      remove :pvn_preservation_temperature
      remove :pvn_sequence
      remove :pvn_preservation_type
      remove :pvn_storage_name
      remove :pvn_tissue_bank_institution
      remove :oth_access_rights
      remove :oth_basis_of_record
      remove :oth_bibliographic_citation
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_data_generalizations
      remove :oth_dataset_id
      remove :oth_dataset_name
      remove :oth_date_available
      remove :oth_information_withheld
      remove :oth_institution_code
      remove :oth_institution_id
      remove :oth_language
      remove :oth_license
      remove :oth_modified_by
      remove :oth_owner_institution_code
      remove :oth_rights_holder
      remove :oth_type
      remove :oth_specify_person
      remove :oth_specify_organism_name
      remove :oth_specify_locality
      remove :oth_specify_event
      remove :oth_specify_author_of_record
      remove :ext_amplification
      remove :ext_assertions
      remove :ext_chronometric
      remove :ext_permit
      remove :ext_resource_relationship
      remove :ext_references
      remove :ext_species_distribution
      remove :ext_species_profile
      remove :ext_vernacular_names
      modify :mte_material_entity_id, :text, null: false
      # This is the `down` migration of the statement:
      #
      #     remove :occ_occurrence_remarks
      #

      # add :occ_occurrence_remarks, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_associated_occurrences
      #

      # add :occ_associated_occurrences, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_sex
      #

      # add :occ_sex, :text
      # This is the `down` migration of the statement:
      #
      #     remove :occ_recorded_by
      #

      # add :occ_recorded_by, :text
      # This is the `down` migration of the statement:
      #
      #     remove :loc_city
      #

      # add :loc_city, :text
      # This is the `down` migration of the statement:
      #
      #     remove :spp_life_stage
      #

      # add :spp_life_stage, :text
      # This is the `down` migration of the statement:
      #
      #     remove :rrp_relationship_of_resource_id
      #

      # add :rrp_relationship_of_resource_id, :text
      # This is the `down` migration of the statement:
      #
      #     remove :rrp_relationship_of_resource
      #

      # add :rrp_relationship_of_resource, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_relationship_established_date
      #

      # add :ref_relationship_established_date, :date
      # This is the `down` migration of the statement:
      #
      #     remove :ref_title
      #

      # add :ref_title, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_source
      #

      # add :ref_source, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_rights
      #

      # add :ref_rights, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_date
      #

      # add :ref_date, :date
      # This is the `down` migration of the statement:
      #
      #     remove :ref_creator
      #

      # add :ref_creator, :text
      # This is the `down` migration of the statement:
      #
      #     remove :ref_bibliographic_citation
      #

      # add :ref_bibliographic_citation, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_date_of_birth
      #

      # add :prs_date_of_birth, :date
      # This is the `down` migration of the statement:
      #
      #     remove :prs_last_name
      #

      # add :prs_last_name, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_first_name
      #

      # add :prs_first_name, :text
      # This is the `down` migration of the statement:
      #
      #     remove :prs_contact_point
      #

      # add :prs_contact_point, :text
    end

    alter table(:records_versions) do
      remove :mte_catalog_number
      # This is the `down` migration of the statement:
      #
      #     remove :mte_material_entity_id
      #

      # add :mte_material_entity_id, :text, null: false
    end
  end
end
