defmodule DataAggregator.Repo.Migrations.MigrateTokenTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tokens) do
      modify :created_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:tokens) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :created_at, :utc_datetime_usec, default: fragment("now()")
    end
  end
end
