defmodule DataAggregator.Repo.Migrations.ApplyUuidVersionAndRecordAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:swiss_species) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:record_encoding_results) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:encoded_records) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end

    alter table(:change_events) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:change_events) do
      modify :id, :uuid, default: nil
    end

    alter table(:encoded_records) do
      modify :id, :uuid, default: nil
    end

    alter table(:record_encoding_results) do
      modify :id, :uuid, default: nil
    end

    alter table(:swiss_species) do
      modify :id, :uuid, default: nil
    end
  end
end
