defmodule DataAggregator.Repo.Migrations.CreateTsvectors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :tsv, :text,
        null: false,
        generated: "ALWAYS AS (
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(tax_scientific_name, '')), 'A') ||
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(occ_occurrence_id, '')), 'B') ||
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(mte_catalog_number, '')), 'B')
        ) STORED"
    end

    create index(:records, [:tsv], name: "records_tsv_idx", using: "GIN")

    alter table(:encoded_records) do
      add :tsv, :text,
        null: false,
        generated: "ALWAYS AS (
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(tax_scientific_name, '')), 'A') ||
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(occ_occurrence_id, '')), 'B') ||
          SETWEIGHT(TO_TSVECTOR('simple', COALESCE(mte_catalog_number, '')), 'B')
        ) STORED"
    end

    create index(:encoded_records, [:tsv], name: "encoded_records_tsv_idx", using: "GIN")
  end

  def down do
    drop index(:encoded_records, [:tsv], name: "encoded_records_tsv_idx")

    alter table(:encoded_records) do
      remove :tsv
    end

    drop index(:records, [:tsv], name: "records_tsv_idx")

    alter table(:records) do
      remove :tsv
    end
  end
end
