defmodule DataAggregator.Repo.Migrations.AddCreatedByAndStartedByUserToPublications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      add :started_by_id,
          references(:users,
            column: :id,
            name: "publications_started_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:publications, "publications_started_by_id_fkey")

    alter table(:publications) do
      remove :started_by_id
    end
  end
end
