defmodule DataAggregator.Repo.Migrations.DontAllowNilOnMappingIdentifier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      modify :mapping_identifier, :text, null: false, default: "mte_catalog_number"
    end
  end

  def down do
    alter table(:image_uploads) do
      modify :mapping_identifier, :text, null: true, default: nil
    end
  end
end
