defmodule DataAggregator.Repo.Migrations.AddNewSwissCoordinatesField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:records), :loc_swiss_coordinates_y, to: :loc_swiss_coordinates_lv03_y

    rename table(:records), :loc_swiss_coordinates_x, to: :loc_swiss_coordinates_lv03_x

    alter table(:records) do
      add :loc_swiss_coordinates_lv95_y, :float
      add :loc_swiss_coordinates_lv95_x, :float
    end

    rename table(:encoded_records), :loc_swiss_coordinates_y, to: :loc_swiss_coordinates_lv03_y

    rename table(:encoded_records), :loc_swiss_coordinates_x, to: :loc_swiss_coordinates_lv03_x

    alter table(:encoded_records) do
      add :loc_swiss_coordinates_lv95_y, :float
      add :loc_swiss_coordinates_lv95_x, :float
    end

    rename table(:approved_records), :loc_swiss_coordinates_y, to: :loc_swiss_coordinates_lv03_y

    rename table(:approved_records), :loc_swiss_coordinates_x, to: :loc_swiss_coordinates_lv03_x

    alter table(:approved_records) do
      add :loc_swiss_coordinates_lv95_y, :float
      add :loc_swiss_coordinates_lv95_x, :float
    end
  end

  def down do
    alter table(:approved_records) do
      remove :loc_swiss_coordinates_lv95_x
      remove :loc_swiss_coordinates_lv95_y
    end

    rename table(:approved_records), :loc_swiss_coordinates_lv03_x, to: :loc_swiss_coordinates_x

    rename table(:approved_records), :loc_swiss_coordinates_lv03_y, to: :loc_swiss_coordinates_y

    alter table(:encoded_records) do
      remove :loc_swiss_coordinates_lv95_x
      remove :loc_swiss_coordinates_lv95_y
    end

    rename table(:encoded_records), :loc_swiss_coordinates_lv03_x, to: :loc_swiss_coordinates_x

    rename table(:encoded_records), :loc_swiss_coordinates_lv03_y, to: :loc_swiss_coordinates_y

    alter table(:records) do
      remove :loc_swiss_coordinates_lv95_x
      remove :loc_swiss_coordinates_lv95_y
    end

    rename table(:records), :loc_swiss_coordinates_lv03_x, to: :loc_swiss_coordinates_x

    rename table(:records), :loc_swiss_coordinates_lv03_y, to: :loc_swiss_coordinates_y
  end
end
