defmodule DataAggregator.Repo.Migrations.CreateMissingIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def change do
    create index(:encoded_records, [:record_id])
    create index(:approvals, [:attachment_id])
    create index(:approved_records, [:record_id])
    create index(:exports, [:collection_id])
    create index(:exports, [:attachment_id])
    create index(:import_records, [:import_id])
    create index(:import_records, [:record_id])
    create index(:imports, [:collection_id])
    create index(:imports, [:error_log_id])
    create index(:publications, [:collection_id])
    create index(:publications, [:attachment_id])
    create index(:record_encoding_results, [:record_id])
    create index(:record_images, [:attachment_id])
    create index(:record_images, [:record_id])
    create index(:records, [:collection_id])
  end
end
