defmodule DataAggregator.Repo.Migrations.AddEncodingAndCatalogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swiss_species, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :taxon_id_ch, :bigint, null: false, primary_key: true
      add :accepted_name, :text
      add :usage_key, :bigint, null: false, primary_key: true
      add :accepted_usage_key, :bigint
      add :scientific_name, :text
      add :rank, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:records) do
      add :state, :text, null: false, default: "imported"
      add :tax_taxon_rank, :text
      add :tax_accepted_name_usage_id, :text
      add :tax_accepted_name_usage, :text
      add :tax_taxon_id_ch, :bigint
      add :tax_taxon_id, :bigint
      add :tax_class, :text
      add :tax_phylum, :text
      add :tax_kingdom, :text
      add :errors, :map

      add :encoder_job_id,
          references(:oban_jobs,
            column: :id,
            name: "records_encoder_job_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create table(:encoded_records, primary_key: false) do
      add :mts_material_sample_type, :text
      add :mte_material_entity_id, :text, null: false
      add :occ_occurrence_remarks, :text
      add :occ_associated_occurrences, :text
      add :occ_sex, :text
      add :occ_recorded_by, :text
      add :loc_georeference_remarks, :text
      add :loc_decimal_latitude, :float
      add :loc_decimal_longitude, :float
      add :loc_state_province, :text
      add :loc_verbatim_locality, :text
      add :loc_locality, :text
      add :loc_country, :text
      add :loc_continent, :text
      add :spp_life_stage, :text
      add :tax_taxon_rank, :text
      add :tax_accepted_name_usage_id, :text
      add :tax_accepted_name_usage, :text
      add :tax_taxon_id_ch, :bigint
      add :tax_taxon_id, :bigint
      add :tax_specific_epithet, :text
      add :tax_infraspecific_epithet, :text
      add :tax_scientific_name_authorship, :text
      add :tax_scientific_name, :text, null: false
      add :tax_genus, :text
      add :tax_family, :text
      add :tax_order, :text
      add :tax_class, :text
      add :tax_phylum, :text
      add :tax_kingdom, :text
      add :rrp_relationship_of_resource_id, :text
      add :rrp_relationship_of_resource, :text
      add :ref_relationship_established_date, :date
      add :ref_title, :text
      add :ref_source, :text
      add :ref_rights, :text
      add :ref_date, :date
      add :ref_creator, :text
      add :ref_bibliographic_citation, :text
      add :idf_type_status, :text
      add :idf_identified_by, :text
      add :idf_date_identified, :date
      add :eve_end_of_period_year, :bigint
      add :eve_end_of_period_month, :bigint
      add :eve_end_of_period_day, :bigint
      add :eve_year, :bigint
      add :eve_month, :bigint
      add :eve_day, :bigint
      add :eve_event_date, :date
      add :prs_date_of_birth, :date
      add :prs_last_name, :text
      add :prs_first_name, :text
      add :prs_contact_point, :text
      add :id, :uuid, null: false, primary_key: true
      add :extra_data, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "encoded_records_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:encoded_records, [:record_id, :mte_material_entity_id],
             name: "encoded_records_record_mte_material_entity_id_index"
           )

    create table(:change_events, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :dwc_attribute, :text, null: false
      add :value, :text
      add :previous_value, :text
      add :category, :text, null: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :record_id,
          references(:records,
            column: :id,
            name: "change_events_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:change_events, "change_events_record_id_fkey")

    drop table(:change_events)

    drop_if_exists unique_index(:encoded_records, [:record_id, :mte_material_entity_id],
                     name: "encoded_records_record_mte_material_entity_id_index"
                   )

    drop constraint(:encoded_records, "encoded_records_record_id_fkey")

    drop table(:encoded_records)

    drop constraint(:records, "records_encoder_job_id_fkey")

    alter table(:records) do
      remove :encoder_job_id
      remove :errors
      remove :tax_kingdom
      remove :tax_phylum
      remove :tax_class
      remove :tax_taxon_id
      remove :tax_taxon_id_ch
      remove :tax_accepted_name_usage
      remove :tax_accepted_name_usage_id
      remove :tax_taxon_rank
      remove :state
    end

    drop table(:swiss_species)
  end
end
