defmodule DataAggregator.Repo.Migrations.AddMappingIdentifierToImageUpload do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :mapping_identifier, :text
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :mapping_identifier
    end
  end
end
