defmodule DataAggregator.Repo.Migrations.AddImageUploadResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:image_uploads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :images_count, :bigint
      add :images_mapped_count, :bigint

      add :collection_id,
          references(:collections,
            column: :id,
            name: "image_uploads_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "image_uploads_attachment_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:image_uploads, [:collection_id])

    create table(:image_upload_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :size, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "image_upload_images_attachment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :image_upload_id,
          references(:image_uploads,
            column: :id,
            name: "image_upload_images_image_upload_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    create index(:image_upload_images, [:attachment_id])

    create index(:image_upload_images, [:image_upload_id])
  end

  def down do
    drop_if_exists index(:image_upload_images, [:image_upload_id])

    drop_if_exists index(:image_upload_images, [:attachment_id])

    drop constraint(:image_upload_images, "image_upload_images_attachment_id_fkey")

    drop constraint(:image_upload_images, "image_upload_images_image_upload_id_fkey")

    drop table(:image_upload_images)

    drop_if_exists index(:image_uploads, [:collection_id])

    drop constraint(:image_uploads, "image_uploads_collection_id_fkey")

    drop constraint(:image_uploads, "image_uploads_attachment_id_fkey")

    drop table(:image_uploads)
  end
end
