defmodule DataAggregator.Repo.Migrations.ImportDeleteConstraintWithCollection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    execute("ALTER TABLE imports alter CONSTRAINT imports_collection_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
