defmodule DataAggregator.Repo.Migrations.ChangetDateAttributesToText do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute """
      ALTER TABLE records
        ALTER COLUMN eve_event_date TYPE text,
        ALTER COLUMN idf_date_identified TYPE text,
        ALTER COLUMN loc_georeferenced_date TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """

    execute """
      ALTER TABLE encoded_records
        ALTER COLUMN eve_event_date TYPE text,
        ALTER COLUMN idf_date_identified TYPE text,
        ALTER COLUMN loc_georeferenced_date TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """

    execute """
      ALTER TABLE approved_records
        ALTER COLUMN eve_event_date TYPE text,
        ALTER COLUMN idf_date_identified TYPE text,
        ALTER COLUMN loc_georeferenced_date TYPE text,
        ALTER COLUMN pvn_preservation_date_begin TYPE text,
        ALTER COLUMN oth_date_available TYPE text;
    """
  end

  def down do
    execute """
      ALTER TABLE records
        ALTER COLUMN eve_event_date TYPE date USING eve_event_date::date,
        ALTER COLUMN idf_date_identified TYPE date USING idf_date_identified::date,
        ALTER COLUMN loc_georeferenced_date TYPE date USING loc_georeferenced_date::date,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """

    execute """
      ALTER TABLE encoded_records
        ALTER COLUMN eve_event_date TYPE date USING eve_event_date::date,
        ALTER COLUMN idf_date_identified TYPE date USING idf_date_identified::date,
        ALTER COLUMN loc_georeferenced_date TYPE date USING loc_georeferenced_date::date,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """

    execute """
      ALTER TABLE approved_records
        ALTER COLUMN eve_event_date TYPE date USING eve_event_date::date,
        ALTER COLUMN idf_date_identified TYPE date USING idf_date_identified::date,
        ALTER COLUMN loc_georeferenced_date TYPE date USING loc_georeferenced_date::date,
        ALTER COLUMN pvn_preservation_date_begin TYPE date USING pvn_preservation_date_begin::date,
        ALTER COLUMN oth_date_available TYPE date USING oth_date_available::date;
    """
  end
end
