defmodule DataAggregator.Repo.Migrations.AddFastTrackCheckerJobIdToRecordResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :fast_track_checker_job_id,
          references(:oban_jobs,
            column: :id,
            name: "records_fast_track_checker_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:records, "records_fast_track_checker_job_id_fkey")

    alter table(:records) do
      remove :fast_track_checker_job_id
    end
  end
end
