defmodule DataAggregator.Repo.Migrations.AddErrorLogToImportTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:imports) do
      add :error_log_id,
          references(:file_attachments,
            column: :id,
            name: "imports_error_log_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:imports, "imports_error_log_id_fkey")

    alter table(:imports) do
      remove :error_log_id
    end
  end
end
