defmodule DataAggregator.Repo.Migrations.AddEncodingJobExtensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :encoder_job_id,
          references(:oban_jobs,
            column: :id,
            name: "records_encoder_job_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:records, "records_encoder_job_id_fkey")

    alter table(:records) do
      remove :encoder_job_id
    end
  end
end
