defmodule DataAggregator.Repo.Migrations.ChangingCollectionAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:collections) do
      modify :owner, :text, null: true
    end
  end

  def down do
    alter table(:collections) do
      modify :owner, :text, null: false
    end
  end
end
