defmodule DataAggregator.Repo.Migrations.RenameValidationToAlidationResponse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validation_responses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :file_url, :text, null: false
      add :rows_count, :bigint
      add :rows_invalid_count, :bigint
      add :rows_validated_count, :bigint
      add :rows_error_count, :bigint
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "validation_responses_attachment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :error_log_id,
          references(:file_attachments,
            column: :id,
            name: "validation_responses_error_log_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :collection_id,
          references(:collections,
            column: :id,
            name: "validation_responses_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :state, :text, null: false, default: "pending"
    end

    create index(:validation_responses, [:collection_id, :attachment_id])
  end

  def down do
    drop_if_exists index(:validation_responses, [:collection_id, :attachment_id])

    drop constraint(:validation_responses, "validation_responses_attachment_id_fkey")

    drop constraint(:validation_responses, "validation_responses_error_log_id_fkey")

    drop constraint(:validation_responses, "validation_responses_collection_id_fkey")

    drop table(:validation_responses)
  end
end
