defmodule DataAggregator.Repo.Migrations.ImageUploadGeneralProgressCount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :general_mapping_progress_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :general_mapping_progress_count
    end
  end
end
