defmodule DataAggregator.Repo.Migrations.PublishedRecordsConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:published_records, "published_records_record_id_fkey")

    alter table(:published_records) do
      modify :record_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "published_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:published_records, [:collection_id, :record_id])
  end

  def down do
    drop_if_exists index(:published_records, [:collection_id, :record_id])

    drop constraint(:published_records, "published_records_record_id_fkey")

    alter table(:published_records) do
      modify :record_id, :text
    end
  end
end
