defmodule DataAggregator.Repo.Migrations.CreateValidationRequestTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validation_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :started_at, :utc_datetime
      add :finished_at, :utc_datetime
      add :records_query, :map, null: false
      add :processed_rows_count, :bigint, null: false, default: 0
      add :total_rows_count, :bigint, null: false, default: 0
      add :center, :text
      add :license, :text, null: false, default: "cc_by"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "validation_requests_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :started_by_id,
          references(:users,
            column: :id,
            name: "validation_requests_started_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :attachment_id,
          references(:file_attachments,
            column: :id,
            name: "validation_requests_attachment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )

      add :state, :text, null: false, default: "pending"
    end

    create index(:validation_requests, [:collection_id])
    create index(:validation_requests, [:collection_id, :attachment_id])

    # delete publications where channel is validation
    execute "DELETE FROM publications WHERE channel = 'validation'"
  end

  def down do
    drop_if_exists index(:validation_requests, [:collection_id, :attachment_id])
    drop_if_exists index(:validation_requests, [:collection_id])
    drop constraint(:validation_requests, "validation_requests_collection_id_fkey")
    drop constraint(:validation_requests, "validation_requests_started_by_id_fkey")
    drop constraint(:validation_requests, "validation_requests_attachment_id_fkey")
    drop table(:validation_requests)
  end
end
