defmodule DataAggregator.Repo.Migrations.CreatePublishedRecordsTablePartitioning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @table_names [
    :approved_records,
    :encoded_records,
    :encoded_records_versions,
    :import_records,
    :record_encoding_results,
    :record_images,
    :records,
    :records_versions
  ]

  def up do
    create unique_index(:published_records, [:collection_id, :id],
             name: "published_records_by_collection_index"
           )

    #  Add tripple primary key and rename table to _orig
    execute "ALTER TABLE IF EXISTS published_records DROP CONSTRAINT published_records_pkey"

    execute "ALTER TABLE IF EXISTS published_records ADD CONSTRAINT published_records_pkey_orig PRIMARY KEY (id, record_id, collection_id)"

    execute "ALTER TABLE IF EXISTS published_records RENAME TO published_records_orig"

    execute "CREATE TABLE published_records (LIKE published_records_orig INCLUDING ALL) PARTITION BY LIST (collection_id)"

    # Create partitions for existing collections
    execute """
      DO $$
      DECLARE
        collection_id uuid;
        partition_sql text;
      BEGIN
        FOR collection_id IN
          SELECT id FROM public.collections
        LOOP
          partition_sql := format(
            'CREATE TABLE published_records_%s PARTITION OF published_records FOR VALUES IN (''%s''::uuid);',
            replace(collection_id::text, '-', ''), collection_id
          );
          EXECUTE partition_sql;
        END LOOP;
      END $$;
    """

    # Copy data from published_records_orig to published_records partitions
    execute """
      DO $$
      DECLARE
        col_list text;
      BEGIN
        SELECT string_agg(column_name, ', ') INTO col_list FROM information_schema.columns WHERE table_name = 'published_records_orig' AND column_name NOT IN ('tsv','mids_level_one','mids_level_two','mids_level_three','mids_level_four','iucn_redlist');
        EXECUTE 'INSERT INTO published_records (' || col_list || ') SELECT ' || col_list || ' FROM published_records_orig;';
      END $$;
    """

    # Add foreign key constraints
    # execute """
    #   ALTER TABLE published_records
    #   ADD CONSTRAINT published_records_collection_id_fkey
    #   FOREIGN KEY (collection_id)
    #   REFERENCES collections(id)
    #   ON DELETE CASCADE
    #   ON UPDATE CASCADE
    # """

    execute """
      ALTER TABLE published_records
      ADD CONSTRAINT published_records_publication_id_fkey
      FOREIGN KEY (publication_id)
      REFERENCES publications(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
    """

    # Function to create partitions before collection insert
    execute """
      CREATE OR REPLACE FUNCTION create_partitions_for_collection()
      RETURNS TRIGGER AS $$
      DECLARE
        table_name text;
      BEGIN
        FOR table_name IN
          SELECT unnest(ARRAY[#{Enum.join((@table_names ++ [:published_records]) |> Enum.map(&"'#{&1}'"), ",")}])
        LOOP
          EXECUTE format(
            'CREATE TABLE %s_%s PARTITION OF %s FOR VALUES IN (''%s''::uuid);',
            table_name, replace(NEW.id::text, '-', ''), table_name, NEW.id
          );
        END LOOP;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    """

    # Function to drop partitions before collection delete
    execute """
      CREATE OR REPLACE FUNCTION drop_partitions_for_collection()
      RETURNS TRIGGER AS $$
      DECLARE
        table_name text;
      BEGIN
        FOR table_name IN
          SELECT unnest(ARRAY[#{Enum.join((@table_names ++ [:published_records]) |> Enum.map(&"'#{&1}'"), ",")}])
        LOOP
          EXECUTE format('DROP TABLE IF EXISTS %s_%s CASCADE;', table_name, replace(OLD.id::text, '-', ''));
        END LOOP;
        RETURN OLD;
      END;
      $$ LANGUAGE plpgsql;
    """
  end

  def down do
    # Drop the partitioned table and rename the original table back
    execute "DROP TABLE IF EXISTS published_records CASCADE"
    execute "ALTER TABLE IF EXISTS published_records_orig RENAME TO published_records"
    execute "ALTER TABLE IF EXISTS published_records DROP CONSTRAINT published_records_pkey_orig"

    execute "ALTER TABLE IF EXISTS published_records ADD CONSTRAINT published_records_pkey PRIMARY KEY (id, record_id)"

    drop_if_exists unique_index(:published_records, [:collection_id, :id],
                     name: "published_records_by_collection_index"
                   )

    # Function to create partitions before collection insert
    execute """
      CREATE OR REPLACE FUNCTION create_partitions_for_collection()
      RETURNS TRIGGER AS $$
      DECLARE
        table_name text;
      BEGIN
        FOR table_name IN
          SELECT unnest(ARRAY[#{Enum.join(@table_names |> Enum.map(&"'#{&1}'"), ",")}])
        LOOP
          EXECUTE format(
            'CREATE TABLE %s_%s PARTITION OF %s FOR VALUES IN (''%s''::uuid);',
            table_name, replace(NEW.id::text, '-', ''), table_name, NEW.id
          );
        END LOOP;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    """

    # Function to drop partitions before collection delete
    execute """
      CREATE OR REPLACE FUNCTION drop_partitions_for_collection()
      RETURNS TRIGGER AS $$
      DECLARE
        table_name text;
      BEGIN
        FOR table_name IN
          SELECT unnest(ARRAY[#{Enum.join(@table_names |> Enum.map(&"'#{&1}'"), ",")}])
        LOOP
          EXECUTE format('DROP TABLE IF EXISTS %s_%s CASCADE;', table_name, replace(OLD.id::text, '-', ''));
        END LOOP;
        RETURN OLD;
      END;
      $$ LANGUAGE plpgsql;
    """
  end
end
