defmodule DataAggregator.Repo.Migrations.CreateValidationRequestResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validation_request_records_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :collection_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create table(:validation_request_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :data, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :record_id,
          references(:records,
            column: :id,
            with: [collection_id: :collection_id],
            name: "validation_request_records_record_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :collection_id,
          references(:collections,
            column: :id,
            name: "validation_request_records_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:validation_request_records, [:collection_id, :record_id])

    create index(:validation_request_records, [:collection_id])

    create unique_index(:validation_request_records, [:id, :collection_id],
             name: "validation_request_records_by_collection_index"
           )

    alter table(:validation_request_records_versions) do
      modify :version_source_id,
             references(:validation_request_records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "validation_request_records_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create unique_index(:validation_request_records, [:collection_id, :record_id],
             name: "validation_request_records_by_record_index"
           )

    execute(
      "ALTER TABLE validation_request_records_versions ALTER CONSTRAINT validation_request_records_versions_version_source_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    alter table(:validation_request_records_versions) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "validation_request_records_versions_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE validation_request_records_versions ALTER CONSTRAINT validation_request_records_versions_user_id_fkey DEFERRABLE INITIALLY DEFERRED"
    )

    create index(:validation_request_records_versions, [:collection_id, :version_source_id])

    create index(:validation_request_records_versions, [:collection_id, :user_id])
  end

  def down do
    drop_if_exists index(:validation_request_records_versions, [:collection_id, :user_id])

    drop_if_exists index(:validation_request_records_versions, [
                     :collection_id,
                     :version_source_id
                   ])

    drop constraint(
           :validation_request_records_versions,
           "validation_request_records_versions_user_id_fkey"
         )

    alter table(:validation_request_records_versions) do
      modify :user_id, :uuid
    end

    drop_if_exists unique_index(:validation_request_records, [:collection_id, :record_id],
                     name: "validation_request_records_by_record_index"
                   )

    drop constraint(
           :validation_request_records_versions,
           "validation_request_records_versions_version_source_id_fkey"
         )

    alter table(:validation_request_records_versions) do
      modify :version_source_id, :uuid
    end

    drop_if_exists unique_index(
                     :validation_request_records,
                     [:id, :collection_id],
                     name: "validation_request_records_by_collection_index"
                   )

    drop_if_exists index(:validation_request_records, [:collection_id])

    drop_if_exists index(:validation_request_records, [:collection_id, :record_id])

    drop constraint(:validation_request_records, "validation_request_records_record_id_fkey")

    drop constraint(:validation_request_records, "validation_request_records_collection_id_fkey")

    drop table(:validation_request_records)

    drop table(:validation_request_records_versions)
  end
end
