defmodule DataAggregator.Repo.Migrations.RemoveTenancyFromValidationResponse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:validation_responses, [:collection_id, :attachment_id])

    alter table(:validation_responses) do
      remove :collection_id
    end

    drop constraint(:validation_responses, "validation_responses_attachment_id_fkey")

    alter table(:validation_responses) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:validation_responses, [:attachment_id])
  end

  def down do
    drop_if_exists index(:validation_responses, [:attachment_id])

    drop constraint(:validation_responses, "validation_responses_attachment_id_fkey")

    alter table(:validation_responses) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:validation_responses) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "validation_responses_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create index(:validation_responses, [:collection_id, :attachment_id])
  end
end
