defmodule DataAggregator.Repo.Migrations.PublishedRecordsDeleteCascadeForAssociatedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Drop the unique indizes temporarily if they exist
    drop_if_exists index(:published_records, [:collection_id, :record_id],
                     name: "published_records_unique_record_id_index"
                   )

    drop_if_exists constraint(:published_records, "published_records_record_id_fkey")

    # Change data type of record_id to uuid
    execute "ALTER TABLE published_records ALTER COLUMN record_id TYPE uuid USING record_id::uuid"

    # Identify zombies and shoot them
    execute """
    DELETE FROM published_records
    WHERE record_id NOT IN (SELECT id FROM records)
    """

    alter table(:published_records) do
      modify :record_id,
             references(:records,
               column: :id,
               with: [collection_id: :collection_id],
               name: "published_records_record_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create_if_not_exists unique_index(:published_records, [:collection_id, :record_id],
                           name: "published_records_unique_record_id_index"
                         )
  end

  def down do
    drop_if_exists index(:published_records, [:collection_id, :record_id])

    drop constraint(:published_records, "published_records_record_id_fkey")

    alter table(:published_records) do
      modify :record_id, :text
    end
  end
end
