defmodule DataAggregator.Repo.Migrations.AddLayerToPublications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      add :layer, :text, null: false, default: "approval"
    end
  end

  def down do
    alter table(:publications) do
      remove :layer
    end
  end
end
