defmodule DataAggregator.Repo.Migrations.AddModifiedMidsLevelGeneratedColumnsToEncodedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @mids_level_one_new """
    mte_catalog_number IS NOT NULL AND
    tax_scientific_name IS NOT NULL
  """

  @mids_level_one_old """
    mte_catalog_number IS NOT NULL AND
    tax_scientific_name IS NOT NULL AND
    oth_institution_code IS NOT NULL
  """

  def up do
    alter table(:encoded_records) do
      remove :mids_level_one
      add :mids_level_one, :boolean, generated: "ALWAYS AS (#{@mids_level_one_new}) STORED"
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :mids_level_one
      add :mids_level_one, :boolean, generated: "ALWAYS AS (#{@mids_level_one_old}) STORED"
    end
  end
end
