defmodule DataAggregator.Repo.Migrations.AttachmentDeletionImprovements do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:validation_requests, "validation_requests_collection_id_fkey")

    alter table(:validation_requests) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_requests_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:image_uploads, "image_uploads_collection_id_fkey")

    alter table(:image_uploads) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "image_uploads_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:file_attachments, "file_attachments_collection_id_fkey")

    alter table(:file_attachments) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "file_attachments_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:file_attachments, "file_attachments_collection_id_fkey")

    alter table(:file_attachments) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "file_attachments_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end

    drop constraint(:image_uploads, "image_uploads_collection_id_fkey")

    alter table(:image_uploads) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "image_uploads_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:validation_requests, "validation_requests_collection_id_fkey")

    alter table(:validation_requests) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_requests_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end
  end
end
