defmodule DataAggregator.Repo.Migrations.NewPictisPlusFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validated_records) do
      add :oth_dynamic_properties, :map
      add :oth_type_designated_by, :text
      add :oth_measurement_value, :text
      add :oth_measurement_unit, :text
      add :occ_caste, :text
      add :idf_typified_name, :text
    end

    alter table(:records) do
      add :oth_dynamic_properties, :map
      add :oth_type_designated_by, :text
      add :oth_measurement_value, :text
      add :oth_measurement_unit, :text
      add :occ_caste, :text
      add :idf_typified_name, :text
    end

    alter table(:published_records) do
      add :oth_dynamic_properties, :map
      add :oth_type_designated_by, :text
      add :oth_measurement_value, :text
      add :oth_measurement_unit, :text
      add :occ_caste, :text
      add :idf_typified_name, :text
    end

    alter table(:encoded_records) do
      add :oth_dynamic_properties, :map
      add :oth_type_designated_by, :text
      add :oth_measurement_value, :text
      add :oth_measurement_unit, :text
      add :occ_caste, :text
      add :idf_typified_name, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :idf_typified_name
      remove :occ_caste
      remove :oth_measurement_unit
      remove :oth_measurement_value
      remove :oth_type_designated_by
      remove :oth_dynamic_properties
    end

    alter table(:published_records) do
      remove :idf_typified_name
      remove :occ_caste
      remove :oth_measurement_unit
      remove :oth_measurement_value
      remove :oth_type_designated_by
      remove :oth_dynamic_properties
    end

    alter table(:records) do
      remove :idf_typified_name
      remove :occ_caste
      remove :oth_measurement_unit
      remove :oth_measurement_value
      remove :oth_type_designated_by
      remove :oth_dynamic_properties
    end

    alter table(:validated_records) do
      remove :idf_typified_name
      remove :occ_caste
      remove :oth_measurement_unit
      remove :oth_measurement_value
      remove :oth_type_designated_by
      remove :oth_dynamic_properties
    end
  end
end
