defmodule DataAggregator.Repo.Migrations.AddAllModifiedMidsLevelGeneratedColumnsToEncodedRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  @mids_level_one_new """
    mte_catalog_number IS NOT NULL AND
    tax_scientific_name IS NOT NULL
  """

  @mids_level_two_new """
    #{@mids_level_one_new} AND
    mte_part_of_organism IS NOT NULL AND
    tax_taxon_id IS NOT NULL
  """

  @mids_level_three_new """
    #{@mids_level_two_new} AND
    loc_continent IS NOT NULL AND
    loc_country IS NOT NULL AND
    loc_county IS NOT NULL AND
    loc_higher_geography IS NOT NULL AND
    loc_locality IS NOT NULL AND
    loc_state_province IS NOT NULL AND
    loc_verbatim_depth IS NOT NULL AND
    loc_verbatim_elevation IS NOT NULL AND
    loc_decimal_latitude IS NOT NULL AND
    loc_decimal_longitude IS NOT NULL AND
    eve_event_date IS NOT NULL AND
    mte_recorded_by IS NOT NULL AND
    idf_type_status IS NOT NULL AND
    tax_original_name_usage IS NOT NULL AND
    mte_year_collection_entrance IS NOT NULL AND
    occ_occurrence_id IS NOT NULL
  """

  @mids_level_four_new """
    #{@mids_level_three_new} AND
    (
      loc_georeferenced_by IS NOT NULL OR
      loc_georeference_verification_status IS NOT NULL OR
      loc_verbatim_coordinates IS NOT NULL OR
      loc_verbatim_latitude IS NOT NULL OR
      loc_verbatim_longitude IS NOT NULL OR
      loc_verbatim_locality IS NOT NULL OR
      mte_associated_media IS NOT NULL OR
      mte_completeness IS NOT NULL OR
      mte_other_catalog_numbers IS NOT NULL OR
      mte_verbatim_label IS NOT NULL OR
      idf_identified_by IS NOT NULL OR
      idf_identification_qualifier IS NOT NULL OR
      idf_identification_verification_status IS NOT NULL OR
      idf_last_verified_by IS NOT NULL OR
      idf_verbatim_identification IS NOT NULL
    )
  """

  @mids_level_one_old """
    mte_catalog_number IS NOT NULL AND
    tax_scientific_name IS NOT NULL AND
    oth_institution_code IS NOT NULL
  """

  @mids_level_two_old """
    #{@mids_level_one_old} AND
    mte_part_of_organism IS NOT NULL AND
    tax_taxon_id IS NOT NULL
  """

  @mids_level_three_old """
    #{@mids_level_two_old} AND
    loc_continent IS NOT NULL AND
    loc_country IS NOT NULL AND
    loc_county IS NOT NULL AND
    loc_higher_geography IS NOT NULL AND
    loc_locality IS NOT NULL AND
    loc_state_province IS NOT NULL AND
    loc_verbatim_depth IS NOT NULL AND
    loc_verbatim_elevation IS NOT NULL AND
    loc_decimal_latitude IS NOT NULL AND
    loc_decimal_longitude IS NOT NULL AND
    eve_event_date IS NOT NULL AND
    mte_recorded_by IS NOT NULL AND
    idf_type_status IS NOT NULL AND
    tax_original_name_usage IS NOT NULL AND
    mte_year_collection_entrance IS NOT NULL AND
    occ_occurrence_id IS NOT NULL
  """

  @mids_level_four_old """
    #{@mids_level_three_old} AND
    (
      loc_georeferenced_by IS NOT NULL OR
      loc_georeference_verification_status IS NOT NULL OR
      loc_verbatim_coordinates IS NOT NULL OR
      loc_verbatim_latitude IS NOT NULL OR
      loc_verbatim_longitude IS NOT NULL OR
      loc_verbatim_locality IS NOT NULL OR
      mte_associated_media IS NOT NULL OR
      mte_completeness IS NOT NULL OR
      mte_other_catalog_numbers IS NOT NULL OR
      mte_verbatim_label IS NOT NULL OR
      idf_identified_by IS NOT NULL OR
      idf_identification_qualifier IS NOT NULL OR
      idf_identification_verification_status IS NOT NULL OR
      idf_last_verified_by IS NOT NULL OR
      idf_verbatim_identification IS NOT NULL
    )
  """

  def up do
    alter table(:encoded_records) do
      remove :mids_level_one
      add :mids_level_one, :boolean, generated: "ALWAYS AS (#{@mids_level_one_new}) STORED"

      remove :mids_level_two
      add :mids_level_two, :boolean, generated: "ALWAYS AS (#{@mids_level_two_new}) STORED"

      remove :mids_level_three
      add :mids_level_three, :boolean, generated: "ALWAYS AS (#{@mids_level_three_new}) STORED"

      remove :mids_level_four
      add :mids_level_four, :boolean, generated: "ALWAYS AS (#{@mids_level_four_new}) STORED"
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :mids_level_one
      add :mids_level_one, :boolean, generated: "ALWAYS AS (#{@mids_level_one_old}) STORED"

      remove :mids_level_two
      add :mids_level_two, :boolean, generated: "ALWAYS AS (#{@mids_level_two_old}) STORED"

      remove :mids_level_three
      add :mids_level_three, :boolean, generated: "ALWAYS AS (#{@mids_level_three_old}) STORED"

      remove :mids_level_four
      add :mids_level_four, :boolean, generated: "ALWAYS AS (#{@mids_level_four_old}) STORED"
    end
  end
end
