defmodule DataAggregator.Repo.Migrations.AddAffectedCollectionsToValidatonResponseRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validation_response_2_collections, primary_key: false) do
      add :validation_response_id,
          references(:validation_responses,
            column: :id,
            name: "validation_response_2_collections_validation_response_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :collection_id,
          references(:collections,
            column: :id,
            name: "validation_response_2_collections_collection_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(
             :validation_response_2_collections,
             [:validation_response_id, :collection_id],
             name: "validation_response_2_collections_vr_coll_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :validation_response_2_collections,
                     [:validation_response_id, :collection_id],
                     name: "validation_response_2_collections_vr_coll_key_index"
                   )

    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_validation_response_id_fkey"
         )

    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_collection_id_fkey"
         )

    drop table(:validation_response_2_collections)
  end
end
