defmodule DataAggregator.Repo.Migrations.AddImageUploadErrorMessage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :error_message, :text
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :error_message
    end
  end
end
