defmodule DataAggregator.Repo.Migrations.AddTermsAcceptedAtToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :terms_accepted_at, :utc_datetime
    end
  end

  def down do
    alter table(:users) do
      remove :terms_accepted_at
    end
  end
end
