defmodule DataAggregator.Repo.Migrations.ChangeLicenseDefaultForPublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      modify :license, :text, default: "cc_by"
    end
  end

  def down do
    alter table(:publications) do
      modify :license, :text, default: "cc0"
    end
  end
end
