defmodule DataAggregator.Repo.Migrations.AlterSwissSpeciesPk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("swiss_species", "swiss_species_pkey")

    alter table(:swiss_species) do
      modify :taxon_id_ch, :bigint, null: true, primary_key: false
    end
  end

  def down do
    alter table(:swiss_species) do
      modify :taxon_id_ch, :bigint, null: false, primary_key: true
    end
  end
end
