defmodule DataAggregator.Repo.Migrations.ImageUploadCounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :mapped_images_count, :bigint, null: false, default: 0
      add :unmapped_images_count, :bigint, null: false, default: 0
      add :invalid_files_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :invalid_files_count
      remove :unmapped_images_count
      remove :mapped_images_count
    end
  end
end
