defmodule DataAggregator.Repo.Migrations.AddSwissSpeciesRegisteredToRecords do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :oth_swiss_species_registered_at, :utc_datetime
      add :oth_swiss_species_center, :text
    end

    alter table(:published_records) do
      add :oth_swiss_species_registered_at, :utc_datetime
      add :oth_swiss_species_center, :text
    end

    alter table(:encoded_records) do
      add :oth_swiss_species_registered_at, :utc_datetime
      add :oth_swiss_species_center, :text
    end

    alter table(:validated_records) do
      add :oth_swiss_species_registered_at, :utc_datetime
      add :oth_swiss_species_center, :text
    end
  end

  def down do
    alter table(:validated_records) do
      remove :oth_swiss_species_center
      remove :oth_swiss_species_registered_at
    end

    alter table(:encoded_records) do
      remove :oth_swiss_species_center
      remove :oth_swiss_species_registered_at
    end

    alter table(:published_records) do
      remove :oth_swiss_species_center
      remove :oth_swiss_species_registered_at
    end

    alter table(:records) do
      remove :oth_swiss_species_center
      remove :oth_swiss_species_registered_at
    end
  end
end
