defmodule DataAggregator.Repo.Migrations.ModifyForRefDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:published_records, "published_records_publication_id_fkey")

    alter table(:published_records) do
      modify :publication_id,
             references(:publications,
               column: :id,
               name: "published_records_publication_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:file_attachments) do
      remove :deletable
      add :deleted_at, :utc_datetime
    end
  end

  def down do
    alter table(:file_attachments) do
      remove :deleted_at
      add :deletable, :boolean, null: false, default: false
    end

    drop_if_exists constraint(:published_records, "published_records_publication_id_fkey")

    alter table(:published_records) do
      modify :publication_id,
             references(:publications,
               column: :id,
               name: "published_records_publication_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end
  end
end
