defmodule DataAggregator.Repo.Migrations.RemoveLicenseFromValidationRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validation_requests) do
      remove :license
    end
  end

  def down do
    alter table(:validation_requests) do
      add :license, :text, null: false, default: "cc_by"
    end
  end
end
