defmodule DataAggregator.Repo.Migrations.RemoveChannelFromPublication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:publications) do
      remove :channel
    end
  end

  def down do
    alter table(:publications) do
      add :channel, :text, null: false
    end
  end
end
