defmodule DataAggregator.Repo.Migrations.AddPublishedRecordsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:published_records, primary_key: false) do
      add :ext_vernacular_names, :map
      add :ext_species_profile, :map
      add :ext_species_distribution, :map
      add :ext_references, :map
      add :ext_resource_relationship, :map
      add :ext_permit, :map
      add :ext_chronometric, :map
      add :ext_assertions, :map
      add :ext_amplification, :map
      add :oth_specify_author_of_record, :text
      add :oth_specify_event, :text
      add :oth_specify_locality, :text
      add :oth_specify_organism_name, :text
      add :oth_specify_person, :text
      add :oth_type, :text
      add :oth_rights_holder, :text
      add :oth_owner_institution_code, :text
      add :oth_modified, :text
      add :oth_modified_by, :text
      add :oth_license, :text
      add :oth_language, :text
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_information_withheld, :text
      add :oth_date_available, :text
      add :oth_dataset_name, :text
      add :oth_dataset_id, :text
      add :oth_data_generalizations, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
      add :oth_bibliographic_citation, :text
      add :oth_basis_of_record, :text
      add :oth_access_rights, :text
      add :pvn_tissue_bank_institution, :text
      add :pvn_storage_name, :text
      add :pvn_preservation_type, :text
      add :pvn_sequence, :text
      add :pvn_preservation_temperature, :text
      add :pvn_preservation_special_mode, :text
      add :pvn_preservation_quality, :text
      add :pvn_preservation_mode_text, :text
      add :pvn_preservation_mode_keywords, :text
      add :pvn_preservation_method, :text
      add :pvn_preservation_id, :text
      add :pvn_preservation_date_begin, :text
      add :pvn_preservation_alteration_text, :text
      add :pvn_dna_storage_code, :text
      add :pvn_dna_bank_institution, :text
      add :occ_occurrence_id, :text
      add :org_organism_remarks, :text
      add :org_organism_scope, :text
      add :org_organism_name, :text
      add :org_organism_id, :text
      add :org_pathway, :text
      add :org_degree_of_establishment, :text
      add :org_establishment_means, :text
      add :org_sex, :text
      add :gec_place_of_origin, :text
      add :gec_member, :text
      add :gec_group, :text
      add :gec_formation, :text
      add :gec_lithostratigraphic_terms, :text
      add :gec_highest_biostratigraphic_zone, :text
      add :gec_lowest_biostratigraphic_zone, :text
      add :gec_latest_age_or_highest_stage, :text
      add :gec_latest_epoch_or_highest_series, :text
      add :gec_latest_period_or_highest_system, :text
      add :gec_latest_era_or_highest_erathem, :text
      add :gec_latest_eon_or_highest_eonothem, :text
      add :gec_earliest_period_or_lowest_system, :text
      add :gec_earliest_era_or_lowest_erathem, :text
      add :gec_earliest_epoch_or_lowest_series, :text
      add :gec_earliest_eon_or_lowest_eonothem, :text
      add :gec_earliest_age_or_lowest_stage, :text
      add :gec_bed, :text
      add :gec_geological_context_id, :text
      add :mts_material_sample_type, :text
      add :mts_material_sample_id, :text
      add :mte_original_biominerals, :text
      add :mte_orig_col_author, :text
      add :mte_year_collection_entrance, :bigint
      add :mte_tissue_bank_id, :text
      add :mte_taphonomy, :text
      add :mte_sample_designation, :text
      add :mte_orientation, :text
      add :mte_organism_quantity_method, :text
      add :mte_mineralization, :text
      add :mte_matrix, :text
      add :mte_gbif_doi, :text
      add :mte_form, :text
      add :mte_feeding_predation_traces, :text
      add :mte_extraction_temporary_id, :text
      add :mte_encrustation, :text
      add :mte_dna_stable_id, :text
      add :mte_dna_bank_id, :text
      add :mte_depositional_environment_type, :text
      add :mte_depositional_environment_text, :text
      add :mte_completeness, :text
      add :mte_paleo_completeness, :text
      add :mte_catalog_number, :text, null: false
      add :mte_bioerosion, :text
      add :mte_assemblage_origin, :text
      add :mte_articulation, :text
      add :mte_permit_id, :text
      add :mte_replacement_minerals, :text
      add :mte_barcode_label, :text
      add :mte_references, :text
      add :mte_other_catalog_numbers, :text
      add :mte_associated_media, :text
      add :mte_occurrence_status, :text
      add :mte_behavior, :text
      add :mte_reproductive_condition, :text
      add :mte_life_stage, :text
      add :mte_organism_quantity_type, :text
      add :mte_organism_quantity, :text
      add :mte_recorded_by_id, :text
      add :mte_recorded_by, :text
      add :mte_record_number, :text
      add :mte_material_entity_remarks, :text
      add :mte_preparations, :text
      add :mte_verbatim_label, :text
      add :mte_post_burial_transportation, :text
      add :mte_part_of_organism, :text
      add :mte_parent_material_entity_id, :text
      add :mte_anatomical_description, :text
      add :mte_material_entity_id, :text
      add :loc_swiss_coordinates_lv95_y, :float
      add :loc_swiss_coordinates_lv95_x, :float
      add :loc_swiss_coordinates_lv03_y, :float
      add :loc_swiss_coordinates_lv03_x, :float
      add :loc_georeference_verification_status, :text
      add :loc_georeference_remarks, :text
      add :loc_georeference_sources, :text
      add :loc_georeference_protocol, :text
      add :loc_georeferenced_date, :text
      add :loc_georeferenced_by, :text
      add :loc_footprint_spatial_fit, :float
      add :loc_footprint_srs, :text
      add :loc_footprint_wkt, :text
      add :loc_verbatim_srs, :text
      add :loc_verbatim_coordinate_system, :text
      add :loc_verbatim_longitude, :text
      add :loc_verbatim_latitude, :text
      add :loc_verbatim_coordinates, :text
      add :loc_point_radius_spatial_fit, :float
      add :loc_coordinate_precision, :float
      add :loc_coordinate_uncertainty_in_meters, :float
      add :loc_geodetic_datum, :text
      add :loc_location_remarks, :text
      add :loc_location_according_to, :text
      add :loc_maximum_distance_above_surface_in_meters, :float
      add :loc_minimum_distance_above_surface_in_meters, :float
      add :loc_verbatim_depth, :text
      add :loc_maximum_depth_in_meters, :float
      add :loc_minimum_depth_in_meters, :float
      add :loc_vertical_datum, :text
      add :loc_verbatim_elevation, :text
      add :loc_maximum_elevation_in_meters, :float
      add :loc_minimum_elevation_in_meters, :float
      add :loc_country_code, :text
      add :loc_municipality, :text
      add :loc_county, :text
      add :loc_decimal_latitude, :float
      add :loc_decimal_longitude, :float
      add :loc_state_province, :text
      add :loc_verbatim_locality, :text
      add :loc_locality, :text
      add :loc_country, :text
      add :loc_island, :text
      add :loc_island_group, :text
      add :loc_continent, :text
      add :loc_higher_geography, :text
      add :loc_water_body_id, :text
      add :loc_water_body, :text
      add :loc_higher_geography_id, :text
      add :loc_location_id, :text
      add :tax_taxon_remarks, :text
      add :tax_nomenclatural_status, :text
      add :tax_taxonomic_status, :text
      add :tax_nomenclatural_code, :text
      add :tax_vernacular_name, :text
      add :tax_verbatim_taxon_rank, :text
      add :tax_taxon_rank, :text
      add :tax_accepted_name_usage_id, :text
      add :tax_accepted_name_usage, :text
      add :tax_taxon_id_ch, :bigint
      add :tax_cultivar_epithet, :text
      add :tax_specific_epithet, :text
      add :tax_infraspecific_epithet, :text
      add :tax_infrageneric_epithet, :text
      add :tax_scientific_name_authorship, :text
      add :tax_generic_name, :text
      add :tax_scientific_name, :text, null: false
      add :tax_sub_tribe, :text
      add :tax_tribe, :text
      add :tax_sub_genus, :text
      add :tax_genus, :text
      add :tax_subfamily, :text
      add :tax_family, :text
      add :tax_order, :text
      add :tax_class, :text
      add :tax_superfamily, :text
      add :tax_phylum, :text
      add :tax_kingdom, :text
      add :tax_taxon_concept_id, :text
      add :tax_higher_classification, :text
      add :tax_name_published_in_year, :text
      add :tax_name_published_in, :text
      add :tax_name_published_in_id, :text
      add :tax_name_according_to, :text
      add :tax_name_according_to_id, :text
      add :tax_original_name_usage, :text
      add :tax_original_name_usage_id, :text
      add :tax_parent_name_usage, :text
      add :tax_parent_name_usage_id, :text
      add :tax_scientific_name_id, :text
      add :tax_identifier, :bigint
      add :tax_taxon_id, :bigint
      add :idf_last_verified_by_id, :text
      add :idf_last_verified_by, :text
      add :idf_verbatim_identification, :text
      add :idf_previous_identifications, :text
      add :idf_identified_by_id, :text
      add :idf_identification_verification_status, :text
      add :idf_identification_remarks, :text
      add :idf_identification_reference, :text
      add :idf_identification_qualifier, :text
      add :idf_evidence_type, :text
      add :idf_type_status, :text
      add :idf_identified_by, :text
      add :idf_date_identified, :text
      add :eve_shrub_layer_height_in_meters, :float
      add :eve_start_day_of_year, :text
      add :eve_sampling_effort, :text
      add :eve_sample_size_unit, :bigint
      add :eve_sample_size_value, :bigint
      add :eve_sampling_protocol, :text
      add :eve_substratum_state, :text
      add :eve_substratum, :text
      add :eve_micro_structure, :text
      add :eve_landscape_structure, :text
      add :eve_influence, :text
      add :eve_habitat_ref, :text
      add :eve_habitat_inclusion, :text
      add :eve_habitat_contact, :text
      add :eve_habitat_code, :text
      add :eve_end_of_period_year, :bigint
      add :eve_end_of_period_month, :bigint
      add :eve_end_of_period_day, :bigint
      add :eve_tree_layer_height_in_meters, :float
      add :eve_syntaxon_name, :text
      add :eve_project, :text
      add :eve_mosses_identified, :boolean
      add :eve_lichens_identified, :boolean
      add :eve_inclination_in_degrees, :float
      add :eve_herb_layer_height_in_centimeters, :float
      add :eve_event_remarks, :text
      add :eve_field_notes, :text
      add :eve_habitat, :text
      add :eve_verbatim_event_date, :text
      add :eve_year, :bigint
      add :eve_month, :bigint
      add :eve_day, :bigint
      add :eve_end_day_of_year, :bigint
      add :eve_event_time, :text
      add :eve_event_date, :text
      add :eve_field_number, :text
      add :eve_parent_event_id, :text
      add :eve_event_id, :text
      add :eve_cover_water_in_percentage, :float
      add :eve_cover_trees_in_percentage, :float
      add :eve_cover_total_in_percentage, :float
      add :eve_cover_shrubs_in_percentage, :float
      add :eve_cover_rock_in_percentage, :float
      add :eve_cover_mosses_in_percentage, :float
      add :eve_cover_litter_in_percentage, :float
      add :eve_cover_lychens_in_percentage, :float
      add :eve_cover_herbs_in_percentage, :float
      add :eve_cover_cryptogams_in_percentage, :float
      add :eve_cover_algae_in_percentage, :float
      add :eve_aspect, :text
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :record_id, :text, null: false, primary_key: true
      add :extra_data, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :collection_id,
          references(:collections,
            column: :id,
            name: "published_records_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :publication_id,
          references(:publications,
            column: :id,
            name: "published_records_publication_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:published_records, [:collection_id, :record_id],
             name: "published_records_unique_record_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:published_records, [:collection_id, :record_id],
                     name: "published_records_unique_record_id_index"
                   )

    drop constraint(:published_records, "published_records_collection_id_fkey")

    drop constraint(:published_records, "published_records_publication_id_fkey")

    drop table(:published_records)
  end
end
