defmodule DataAggregator.Repo.Migrations.AddUploadLogToImageUploadResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :upload_log_id,
          references(:file_attachments,
            column: :id,
            name: "image_uploads_upload_log_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:image_uploads, "image_uploads_upload_log_id_fkey")

    alter table(:image_uploads) do
      remove :upload_log_id
    end
  end
end
