defmodule DataAggregator.Repo.Migrations.AddReferentialDeletionForValidationResponse2CollectionsEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_collection_id_fkey"
         )

    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_validation_response_id_fkey"
         )

    alter table(:validation_response_2_collections) do
      modify :validation_response_id,
             references(:validation_responses,
               column: :id,
               name: "validation_response_2_collections_validation_response_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )

      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_response_2_collections_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_validation_response_id_fkey"
         )

    drop constraint(
           :validation_response_2_collections,
           "validation_response_2_collections_collection_id_fkey"
         )

    alter table(:validation_response_2_collections) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_response_2_collections_collection_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :validation_response_id,
             references(:validation_responses,
               column: :id,
               name: "validation_response_2_collections_validation_response_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
