defmodule DataAggregator.Repo.Migrations.RenameFastTrackStatusToPublicationStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:records, [
                     :collection_id,
                     :state,
                     :validation_status,
                     :fast_track_status
                   ])

    rename table(:records), :fast_track_status, to: :publication_status

    create index(:records, [:collection_id, :state, :validation_status, :publication_status],
             include: ["id"]
           )

    execute("""
    UPDATE records_versions
    SET version_action_name = 'update_publication_status'
    WHERE version_action_name = 'update_fast_track_status'
    """)
  end

  def down do
    drop_if_exists index(:records, [
                     :collection_id,
                     :state,
                     :validation_status,
                     :publication_status
                   ])

    rename table(:records), :publication_status, to: :fast_track_status

    create index(:records, [:collection_id, :state, :validation_status, :fast_track_status],
             include: ["id"]
           )

    execute("""
    UPDATE records_versions
    SET version_action_name = 'update_fast_track_status'
    WHERE version_action_name = 'update_publication_status'
    """)
  end
end
