defmodule DataAggregator.Repo.Migrations.SetDefaultValueForValidationResponse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validation_responses) do
      modify :type, :text, default: "validated"
    end
  end

  def down do
    alter table(:validation_responses) do
      modify :type, :text, default: nil
    end
  end
end
