defmodule DataAggregator.Repo.Migrations.CreateMoreDwcFields27052025 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validated_records) do
      add :occ_vitality, :text
      add :occ_occurrence_remarks, :text
      add :occ_associated_taxa, :text
      add :occ_associated_references, :text
      add :occ_associated_occurrences, :text
      add :occ_individual_count, :bigint
      add :org_associated_organisms, :text
      add :mte_associated_sequences, :text
      add :mte_disposition, :text
      add :idf_identification_id, :text
      add :eve_event_type, :text
    end

    alter table(:records) do
      add :occ_vitality, :text
      add :occ_occurrence_remarks, :text
      add :occ_associated_taxa, :text
      add :occ_associated_references, :text
      add :occ_associated_occurrences, :text
      add :occ_individual_count, :bigint
      add :org_associated_organisms, :text
      add :mte_associated_sequences, :text
      add :mte_disposition, :text
      add :idf_identification_id, :text
      add :eve_event_type, :text
    end

    alter table(:published_records) do
      add :occ_vitality, :text
      add :occ_occurrence_remarks, :text
      add :occ_associated_taxa, :text
      add :occ_associated_references, :text
      add :occ_associated_occurrences, :text
      add :occ_individual_count, :bigint
      add :org_associated_organisms, :text
      add :mte_associated_sequences, :text
      add :mte_disposition, :text
      add :idf_identification_id, :text
      add :eve_event_type, :text
    end

    alter table(:encoded_records) do
      add :occ_vitality, :text
      add :occ_occurrence_remarks, :text
      add :occ_associated_taxa, :text
      add :occ_associated_references, :text
      add :occ_associated_occurrences, :text
      add :occ_individual_count, :bigint
      add :org_associated_organisms, :text
      add :mte_associated_sequences, :text
      add :mte_disposition, :text
      add :idf_identification_id, :text
      add :eve_event_type, :text
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :eve_event_type
      remove :idf_identification_id
      remove :mte_disposition
      remove :mte_associated_sequences
      remove :org_associated_organisms
      remove :occ_individual_count
      remove :occ_associated_occurrences
      remove :occ_associated_references
      remove :occ_associated_taxa
      remove :occ_occurrence_remarks
      remove :occ_vitality
    end

    alter table(:published_records) do
      remove :eve_event_type
      remove :idf_identification_id
      remove :mte_disposition
      remove :mte_associated_sequences
      remove :org_associated_organisms
      remove :occ_individual_count
      remove :occ_associated_occurrences
      remove :occ_associated_references
      remove :occ_associated_taxa
      remove :occ_occurrence_remarks
      remove :occ_vitality
    end

    alter table(:records) do
      remove :eve_event_type
      remove :idf_identification_id
      remove :mte_disposition
      remove :mte_associated_sequences
      remove :org_associated_organisms
      remove :occ_individual_count
      remove :occ_associated_occurrences
      remove :occ_associated_references
      remove :occ_associated_taxa
      remove :occ_occurrence_remarks
      remove :occ_vitality
    end

    alter table(:validated_records) do
      remove :eve_event_type
      remove :idf_identification_id
      remove :mte_disposition
      remove :mte_associated_sequences
      remove :org_associated_organisms
      remove :occ_individual_count
      remove :occ_associated_occurrences
      remove :occ_associated_references
      remove :occ_associated_taxa
      remove :occ_occurrence_remarks
      remove :occ_vitality
    end
  end
end
