defmodule DataAggregator.Repo.Migrations.AttachmentCollectionRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_attachments) do
      add :collection_id,
          references(:collections,
            column: :id,
            name: "file_attachments_collection_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing
          )
    end

    execute(
      "ALTER TABLE file_attachments ALTER CONSTRAINT file_attachments_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    create index(:file_attachments, [:collection_id])
  end

  def down do
    drop_if_exists index(:file_attachments, [:collection_id])

    drop constraint(:file_attachments, "file_attachments_collection_id_fkey")

    alter table(:file_attachments) do
      remove :collection_id
    end

    execute(
      "ALTER TABLE file_attachments ALTER CONSTRAINT file_attachments_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )
  end
end
