defmodule DataAggregator.Repo.Migrations.FixNameConflictingAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:validated_records), :ext_references, to: :ext_refs

    rename table(:records), :ext_references, to: :ext_refs

    rename table(:published_records), :ext_references, to: :ext_refs

    rename table(:encoded_records), :ext_references, to: :ext_refs
  end

  def down do
    rename table(:encoded_records), :ext_refs, to: :ext_references

    rename table(:published_records), :ext_refs, to: :ext_references

    rename table(:records), :ext_refs, to: :ext_references

    rename table(:validated_records), :ext_refs, to: :ext_references
  end
end
