defmodule DataAggregator.Repo.Migrations.AddDestroyableToAttachments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:file_attachments) do
      add :deletable, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:file_attachments) do
      remove :deletable
    end
  end
end
