defmodule DataAggregator.Repo.Migrations.AddValidationAnnotationField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      add :validation_annotation, :text
    end
  end

  def down do
    alter table(:records) do
      remove :validation_annotation
    end
  end
end
