defmodule DataAggregator.Repo.Migrations.CreateSwissSpeciesRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swiss_species_registry, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :scientific_name, :text, null: false, primary_key: true
      add :taxon_id_ch, :text
      add :accepted_name_usage, :text
      add :center, :text
      add :rank, :text
      add :status, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:swiss_species_registry)
  end
end
