defmodule DataAggregator.Repo.Migrations.AddImageUploadOperationsProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:image_uploads) do
      add :max_mapping_operations_count, :bigint, null: false, default: 0
      add :current_mapping_operations_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:image_uploads) do
      remove :current_mapping_operations_count
      remove :max_mapping_operations_count
    end
  end
end
