defmodule DataAggregator.Repo.Migrations.ValidationStatusDefaultValue do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :validation_status, :text, default: "unknown"
    end
  end

  def down do
    alter table(:records) do
      modify :validation_status, :text, default: "not_validated"
    end
  end
end
