defmodule DataAggregator.Repo.Migrations.SwissRegistryEncoding do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # For validated_records
    alter table(:validated_records) do
      add_if_not_exists :oth_swiss_species_registered_at, :utc_datetime
      add_if_not_exists :oth_swiss_species_registered, :boolean
      add_if_not_exists :oth_swiss_species_center, :text
    end

    # For records
    alter table(:records) do
      add_if_not_exists :oth_swiss_species_registered_at, :utc_datetime
      add_if_not_exists :oth_swiss_species_registered, :boolean
      add_if_not_exists :oth_swiss_species_center, :text
    end

    # For published_records
    alter table(:published_records) do
      add_if_not_exists :oth_swiss_species_registered_at, :utc_datetime
      add_if_not_exists :oth_swiss_species_registered, :boolean
      add_if_not_exists :oth_swiss_species_center, :text
    end

    # For encoded_records
    alter table(:encoded_records) do
      add_if_not_exists :oth_swiss_species_registered_at, :utc_datetime
      add_if_not_exists :oth_swiss_species_registered, :boolean
      add_if_not_exists :oth_swiss_species_center, :text
    end
  end

  def down do
    # For encoded_records
    remove_if_exists :encoded_records, :oth_swiss_species_center
    remove_if_exists :encoded_records, :oth_swiss_species_registered
    remove_if_exists :encoded_records, :oth_swiss_species_registered_at

    # For published_records
    remove_if_exists :published_records, :oth_swiss_species_center
    remove_if_exists :published_records, :oth_swiss_species_registered
    remove_if_exists :published_records, :oth_swiss_species_registered_at

    # For records
    remove_if_exists :records, :oth_swiss_species_center
    remove_if_exists :records, :oth_swiss_species_registered
    remove_if_exists :records, :oth_swiss_species_registered_at

    # For validated_records
    remove_if_exists :validated_records, :oth_swiss_species_center
    remove_if_exists :validated_records, :oth_swiss_species_registered
    remove_if_exists :validated_records, :oth_swiss_species_registered_at
  end
end
