defmodule DataAggregator.Repo.Migrations.AddSwissSpeciesRegisteredToRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validated_records) do
      add :oth_swiss_species_registered, :boolean
    end

    alter table(:records) do
      add :oth_swiss_species_registered, :boolean
    end

    alter table(:published_records) do
      add :oth_swiss_species_registered, :boolean
    end

    alter table(:encoded_records) do
      add :oth_swiss_species_registered, :boolean
    end
  end

  def down do
    alter table(:encoded_records) do
      remove :oth_swiss_species_registered
    end

    alter table(:published_records) do
      remove :oth_swiss_species_registered
    end

    alter table(:records) do
      remove :oth_swiss_species_registered
    end

    alter table(:validated_records) do
      remove :oth_swiss_species_registered
    end
  end
end
