defmodule DataAggregator.Repo.Migrations.RemovePublicationAttachmentRefDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:publications, [:collection_id, :attachment_id])

    drop constraint(:publications, "publications_attachment_id_fkey")

    alter table(:publications) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "publications_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:publications, [:collection_id, :attachment_id])
  end

  def down do
    drop_if_exists index(:publications, [:collection_id, :attachment_id])

    drop constraint(:publications, "publications_attachment_id_fkey")

    alter table(:publications) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "publications_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:publications, [:collection_id, :attachment_id])
  end
end
