defmodule DataAggregator.Repo.Migrations.AddUniqueIdentifiersToRecord do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:records), :mte_gbif_doi, to: :oth_gbif_doi

    alter table(:records) do
      modify :oth_gbif_doi, :text
      add :oth_gbif_ch_id, :text
      add :oth_gbif_id, :text
    end

    rename table(:published_records), :mte_gbif_doi, to: :oth_gbif_doi

    alter table(:published_records) do
      modify :oth_gbif_doi, :text
      add :oth_gbif_ch_id, :text
      add :oth_gbif_id, :text
    end

    rename table(:encoded_records), :mte_gbif_doi, to: :oth_gbif_doi

    alter table(:encoded_records) do
      modify :oth_gbif_doi, :text
      add :oth_gbif_ch_id, :text
      add :oth_gbif_id, :text
    end

    rename table(:approved_records), :mte_gbif_doi, to: :oth_gbif_doi

    alter table(:approved_records) do
      modify :oth_gbif_doi, :text
      add :oth_gbif_ch_id, :text
      add :oth_gbif_id, :text
    end

    # Copy data from occurrence_id to gbif_id
    execute "UPDATE records SET oth_gbif_id = occ_occurrence_id"
    execute "UPDATE published_records SET oth_gbif_id = occ_occurrence_id"
    execute "UPDATE encoded_records SET oth_gbif_id = occ_occurrence_id"
    execute "UPDATE approved_records SET oth_gbif_id = occ_occurrence_id"

    # Copy data from catalog_number to occurrence_id
    execute "UPDATE records SET occ_occurrence_id = mte_catalog_number"
    execute "UPDATE published_records SET occ_occurrence_id = mte_catalog_number"
    execute "UPDATE encoded_records SET occ_occurrence_id = mte_catalog_number"
    execute "UPDATE approved_records SET occ_occurrence_id = mte_catalog_number"
  end

  def down do
    alter table(:approved_records) do
      remove :oth_gbif_id
      remove :oth_gbif_ch_id
      modify :mte_gbif_doi, :text
    end

    rename table(:approved_records), :oth_gbif_doi, to: :mte_gbif_doi

    alter table(:encoded_records) do
      remove :oth_gbif_id
      remove :oth_gbif_ch_id
      modify :mte_gbif_doi, :text
    end

    rename table(:encoded_records), :oth_gbif_doi, to: :mte_gbif_doi

    alter table(:published_records) do
      remove :oth_gbif_id
      remove :oth_gbif_ch_id
      modify :mte_gbif_doi, :text
    end

    rename table(:published_records), :oth_gbif_doi, to: :mte_gbif_doi

    alter table(:records) do
      remove :oth_gbif_id
      remove :oth_gbif_ch_id
      modify :mte_gbif_doi, :text
    end

    rename table(:records), :oth_gbif_doi, to: :mte_gbif_doi
  end
end
