defmodule DataAggregator.Repo.Migrations.AddValidationSentForValidationCountField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validation_requests) do
      add :sent_for_validation_count, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:validation_requests) do
      remove :sent_for_validation_count
    end
  end
end
