defmodule DataAggregator.Repo.Migrations.DeferrableCollectionRelationConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:validation_requests, [:collection_id, :attachment_id])

    drop constraint(:validation_requests, "validation_requests_attachment_id_fkey")

    drop constraint(:validation_requests, "validation_requests_collection_id_fkey")

    alter table(:validation_requests) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_requests_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:imports, [:collection_id, :error_log_id])

    drop constraint(:imports, "imports_error_log_id_fkey")

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop constraint(:image_uploads, "image_uploads_collection_id_fkey")

    alter table(:image_uploads) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "image_uploads_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    drop_if_exists index(:exports, [:collection_id, :attachment_id])

    drop constraint(:exports, "exports_attachment_id_fkey")

    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE exports ALTER CONSTRAINT exports_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    alter table(:exports) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "exports_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:exports, [:collection_id, :attachment_id])

    execute(
      "ALTER TABLE image_uploads ALTER CONSTRAINT image_uploads_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    execute(
      "ALTER TABLE imports ALTER CONSTRAINT imports_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    alter table(:imports) do
      modify :error_log_id,
             references(:file_attachments,
               column: :id,
               name: "imports_error_log_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:imports, [:collection_id, :error_log_id])

    execute(
      "ALTER TABLE validation_requests ALTER CONSTRAINT validation_requests_collection_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    alter table(:validation_requests) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_requests_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:validation_requests, [:collection_id, :attachment_id])
  end

  def down do
    drop_if_exists index(:validation_requests, [:collection_id, :attachment_id])

    drop constraint(:validation_requests, "validation_requests_attachment_id_fkey")

    alter table(:validation_requests) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_requests_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop_if_exists index(:imports, [:collection_id, :error_log_id])

    drop constraint(:imports, "imports_error_log_id_fkey")

    alter table(:imports) do
      modify :error_log_id,
             references(:file_attachments,
               column: :id,
               name: "imports_error_log_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop_if_exists index(:exports, [:collection_id, :attachment_id])

    drop constraint(:exports, "exports_attachment_id_fkey")

    alter table(:exports) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "exports_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:exports, "exports_collection_id_fkey")

    alter table(:exports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "exports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:exports, [:collection_id, :attachment_id])

    drop constraint(:image_uploads, "image_uploads_collection_id_fkey")

    alter table(:image_uploads) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "image_uploads_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    drop constraint(:imports, "imports_collection_id_fkey")

    alter table(:imports) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "imports_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:imports, [:collection_id, :error_log_id])

    drop constraint(:validation_requests, "validation_requests_collection_id_fkey")

    alter table(:validation_requests) do
      modify :collection_id,
             references(:collections,
               column: :id,
               name: "validation_requests_collection_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    create index(:validation_requests, [:collection_id, :attachment_id])

    execute(
      "ALTER TABLE validation_requests ALTER CONSTRAINT validation_requests_collection_id_fkey NOT DEFERRABLE"
    )

    execute("ALTER TABLE imports ALTER CONSTRAINT imports_collection_id_fkey NOT DEFERRABLE")

    execute(
      "ALTER TABLE image_uploads ALTER CONSTRAINT image_uploads_collection_id_fkey NOT DEFERRABLE"
    )

    execute("ALTER TABLE exports ALTER CONSTRAINT exports_collection_id_fkey NOT DEFERRABLE")
  end
end
