defmodule DataAggregator.Repo.Migrations.SizeAttributesChangeType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:records) do
      modify :eve_sample_size_value, :float
      modify :eve_sample_size_unit, :text
    end

    alter table(:published_records) do
      modify :eve_sample_size_value, :float
      modify :eve_sample_size_unit, :text
    end

    alter table(:encoded_records) do
      modify :eve_sample_size_value, :float
      modify :eve_sample_size_unit, :text
    end

    alter table(:validated_records) do
      modify :eve_sample_size_value, :float
      modify :eve_sample_size_unit, :text
    end
  end

  def down do
    alter table(:validated_records) do
      modify :eve_sample_size_unit, :bigint
      modify :eve_sample_size_value, :bigint
    end

    alter table(:encoded_records) do
      modify :eve_sample_size_unit, :bigint
      modify :eve_sample_size_value, :bigint
    end

    alter table(:published_records) do
      modify :eve_sample_size_unit, :bigint
      modify :eve_sample_size_value, :bigint
    end

    alter table(:records) do
      modify :eve_sample_size_unit, :bigint
      modify :eve_sample_size_value, :bigint
    end
  end
end
