defmodule DataAggregator.Repo.Migrations.RemoveUnusedAttributesFromSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validated_records) do
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_dataset_id
      remove :oth_gbif_doi
      remove :oth_institution_code
      remove :oth_institution_id
    end

    alter table(:records) do
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_dataset_id
      remove :oth_gbif_doi
      remove :oth_institution_code
      remove :oth_institution_id
    end

    alter table(:published_records) do
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_dataset_id
      remove :oth_gbif_doi
      remove :oth_institution_code
      remove :oth_institution_id
    end

    alter table(:encoded_records) do
      remove :oth_collection_code
      remove :oth_collection_id
      remove :oth_dataset_id
      remove :oth_gbif_doi
      remove :oth_institution_code
      remove :oth_institution_id
    end
  end

  def down do
    alter table(:encoded_records) do
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_gbif_doi, :text
      add :oth_dataset_id, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
    end

    alter table(:published_records) do
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_gbif_doi, :text
      add :oth_dataset_id, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
    end

    alter table(:records) do
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_gbif_doi, :text
      add :oth_dataset_id, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
    end

    alter table(:validated_records) do
      add :oth_institution_id, :text
      add :oth_institution_code, :text
      add :oth_gbif_doi, :text
      add :oth_dataset_id, :text
      add :oth_collection_id, :text
      add :oth_collection_code, :text
    end
  end
end
