defmodule DataAggregator.Repo.Migrations.AddCenterAndTaxScientificNameIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:swiss_species_registry, [:center])

    create index(:encoded_records, [:collection_id, :tax_scientific_name])
  end

  def down do
    drop_if_exists index(:encoded_records, [:collection_id, :tax_scientific_name])

    drop_if_exists index(:swiss_species_registry, [:center])
  end
end
