defmodule DataAggregator.Repo.Migrations.DetachAttachmentsFromValidationResponses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:validation_responses, "validation_responses_error_log_id_fkey")

    drop constraint(:validation_responses, "validation_responses_attachment_id_fkey")

    alter table(:validation_responses) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_attachment_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE validation_responses ALTER CONSTRAINT validation_responses_attachment_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )

    alter table(:validation_responses) do
      modify :error_log_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_error_log_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    execute(
      "ALTER TABLE validation_responses ALTER CONSTRAINT validation_responses_error_log_id_fkey DEFERRABLE INITIALLY IMMEDIATE"
    )
  end

  def down do
    drop constraint(:validation_responses, "validation_responses_error_log_id_fkey")

    alter table(:validation_responses) do
      modify :error_log_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_error_log_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:validation_responses, "validation_responses_attachment_id_fkey")

    alter table(:validation_responses) do
      modify :attachment_id,
             references(:file_attachments,
               column: :id,
               name: "validation_responses_attachment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    execute(
      "ALTER TABLE validation_responses ALTER CONSTRAINT validation_responses_error_log_id_fkey NOT DEFERRABLE"
    )

    execute(
      "ALTER TABLE validation_responses ALTER CONSTRAINT validation_responses_attachment_id_fkey NOT DEFERRABLE"
    )
  end
end
