defmodule DataAggregator.Repo.Migrations.AddValidationRequestIdToVrr do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:validation_requests, [:collection_id, :id],
             name: "validation_requests_by_collection_index"
           )

    alter table(:validation_request_records) do
      add :validation_request_id,
          references(:validation_requests,
            column: :id,
            with: [collection_id: :collection_id],
            name: "validation_request_records_validation_request_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:validation_request_records, [:collection_id, :validation_request_id])
  end

  def down do
    drop_if_exists index(:validation_request_records, [:collection_id, :validation_request_id])

    drop constraint(
           :validation_request_records,
           "validation_request_records_validation_request_id_fkey"
         )

    alter table(:validation_request_records) do
      remove :validation_request_id
    end

    drop_if_exists unique_index(:validation_requests, [:collection_id, :id],
                     name: "validation_requests_by_collection_index"
                   )
  end
end
