defmodule DataAggregator.Repo.Migrations.AddObanJobIdAndCascadeVrrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:validation_requests) do
      add :oban_job_id, :bigint
    end

    drop constraint(
           :validation_request_records,
           "validation_request_records_validation_request_id_fkey"
         )

    alter table(:validation_request_records) do
      modify :validation_request_id,
             references(:validation_requests,
               column: :id,
               with: [collection_id: :collection_id],
               name: "validation_request_records_validation_request_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end
  end

  def down do
    drop constraint(
           :validation_request_records,
           "validation_request_records_validation_request_id_fkey"
         )

    alter table(:validation_request_records) do
      modify :validation_request_id,
             references(:validation_requests,
               column: :id,
               with: [collection_id: :collection_id],
               name: "validation_request_records_validation_request_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    alter table(:validation_requests) do
      remove :oban_job_id
    end
  end
end
