defmodule DataAggregator.Repo.Migrations.AshUpgrade072026 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:attachments)

    drop_if_exists table(:attribute_resolving_strategies)

    drop_if_exists table(:change_events)

    drop_if_exists table(:import_files)

    drop_if_exists table(:institutions)

    drop_if_exists table(:validations)

    drop_if_exists table(:dwc_attributes)

    drop_if_exists table(:catalogs)
  end

  def down do
    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually

    # Rollback would require recreating the table manually
  end
end
