imagePullSecrets:
  - name: zebbra-kube-pull-secret

replicaCount: 3

image:
  tag: latest

env:
  BASE_URL: https://staging.aggregator.scnat.zebbra.ch
  SENTRY_DSN: https://128c60631cb044ec8c353307d9352673@sentry.zebbra.ch/325
  SENTRY_SESSION_REPLAY_SCRIPT_URL: https://sentry.zebbra.ch/js-sdk-loader/128c60631cb044ec8c353307d9352673.min.js
  LOG_LEVEL: info
  WAFFLE_STORAGE: s3
  AWS_S3_HOST: a8c524e0ea4a653c03bf5db26dba19a4.eu.r2.cloudflarestorage.com
  WAFFLE_S3_BUCKET: zebbra-data-aggregator-staging
  WAFFLE_ASSET_HOST: https://${AWS_S3_HOST}/${WAFFLE_S3_BUCKET}
  POOL_SIZE: 20
  IMPORT_MAX_CONCURRENCY: 4 # k8s nodes have 8 cpus
  SWISS_NAT_COLL_BASE_URL: https://swissnatcoll.hp.gbif-staging.org
  GBIF_SPECIES_API_BASE_URL: https://api.gbif.org/v1
  GBIF_API_BASE_URL: https://api.gbif-uat.org/v1
  GBIF_BASE_URL: https://www.gbif-uat.org

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.aggregator.scnat.zebbra.ch
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - secretName: staging-aggregator-tls
      hosts:
        - staging.aggregator.scnat.zebbra.ch
