imagePullSecrets:
  - name: zebbra-kube-pull-secret

replicaCount: 3

image:
  tag: latest

env:
  BASE_URL: https://staging.aggregator.scnat.zebbra.ch
  SENTRY_DSN: https://128c60631cb044ec8c353307d9352673@sentry.zebbra.ch/325
  SENTRY_SESSION_REPLAY_SCRIPT_URL: https://sentry.zebbra.ch/js-sdk-loader/128c60631cb044ec8c353307d9352673.min.js
  LOG_LEVEL: info
  WAFFLE_STORAGE: s3
  AWS_S3_HOST: s3.cloud.zebbra.ch
  WAFFLE_S3_BUCKET: data-aggregator-stag
  WAFFLE_ASSET_HOST: https://${AWS_S3_HOST}/${WAFFLE_S3_BUCKET}
  POOL_SIZE: 20
  IMPORT_MAX_CONCURRENCY: 4 # k8s nodes have 8 cpus

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.aggregator.scnat.zebbra.ch
      paths:
        - path: /
          pathType: ImplementationSpecific

  tls:
    - secretName: staging-aggregator-tls
      hosts:
        - staging.aggregator.scnat.zebbra.ch

postgres:
  backup:
    enabled: true
    schedule: "0 0 0 * * *"
    destinationPath: "s3://data-aggregator-stag/postgres"
    endpointURL: "http://minio.minio.svc.cluster.local:9000"
