

Table file_attachments {
  id uuid [pk]
  filename varchar
  byte_size integer
  inserted_at timestamp
  updated_at timestamp
}

Table institutions {
  id uuid [pk]
  name varchar
  code varchar
  address varchar
  zip_code varchar
  city varchar
  country varchar
  mail varchar
  tel varchar
  contact_person varchar
  inserted_at timestamp
  updated_at timestamp
}

Table collections {
  id uuid [pk]
  items_to_digitize integer
  owner varchar
  name varchar
  code varchar
  description varchar
  mapping jsonb
  inserted_at timestamp
  updated_at timestamp
  institution_id uuid
}

Table imports {
  state varchar
  id uuid [pk]
  columns array
  inserted_at timestamp
  updated_at timestamp
  imported_at timestamp
  collection_id uuid
  attachment_id uuid
}

Table import_records {
  import_id uuid [pk]
  record_id uuid [pk]
}

Table records {
  mts_material_sample_type varchar
  mte_material_entity_id varchar
  occ_occurrence_remarks varchar
  occ_associated_occurrences varchar
  occ_sex varchar
  occ_recorded_by varchar
  loc_georeference_remarks varchar
  loc_decimal_latitude float
  loc_decimal_longitude float
  loc_state_province varchar
  loc_verbatim_locality varchar
  loc_locality varchar
  loc_country varchar
  loc_continent varchar
  spp_life_stage varchar
  tax_specific_epithet varchar
  tax_infraspecific_epithet varchar
  tax_scientific_name_authorship varchar
  tax_scientific_name varchar
  tax_genus varchar
  tax_family varchar
  tax_order varchar
  rrp_relationship_of_resource_id varchar
  rrp_relationship_of_resource varchar
  ref_relationship_established_date date
  ref_title varchar
  ref_source varchar
  ref_rights varchar
  ref_date date
  ref_creator varchar
  ref_bibliographic_citation varchar
  idf_type_status varchar
  idf_identified_by varchar
  idf_date_identified date
  eve_end_of_period_year integer
  eve_end_of_period_month integer
  eve_end_of_period_day integer
  eve_year integer
  eve_month integer
  eve_day integer
  eve_event_date date
  prs_date_of_birth date
  prs_last_name varchar
  prs_first_name varchar
  prs_contact_point varchar
  id uuid [pk]
  import_data jsonb
  extra_data jsonb
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
}

Table record_images {
  id uuid [pk]
  size integer
  inserted_at timestamp
  updated_at timestamp
  attachment_id uuid
  record_id uuid
}

Table attribute_resolving_strategies {
  id uuid [pk]
  do_not_encode boolean
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
  dwc_attribute_id uuid
  catalog_id uuid
}

Table catalogs {
  id uuid [pk]
  name varchar
  description varchar
  url varchar
  version integer
  inserted_at timestamp
  updated_at timestamp
}

Table dwc_attributes {
  id uuid [pk]
  name varchar
  inserted_at timestamp
  updated_at timestamp
  default_catalog_id uuid
}

Table schema_migrations {
  version integer [pk]
  inserted_at timestamp
}

Table oban_jobs {
  id integer [pk]
  state varchar
  queue varchar
  worker varchar
  args jsonb
  meta jsonb
  tags array
  errors array
  attempt integer
  attempted_by array
  max_attempts integer
  priority integer
  attempted_at timestamp
  cancelled_at timestamp
  completed_at timestamp
  discarded_at timestamp
  inserted_at timestamp
  scheduled_at timestamp
}

Table "" {
  autogenerated_id uuid [pk]
  value bytea
  name varchar [pk]
  type varchar
  mapped_to varchar
}

Ref: catalogs.id < attribute_resolving_strategies.catalog_id
Ref: catalogs.id < dwc_attributes.default_catalog_id
Ref: collections.id < attribute_resolving_strategies.collection_id
Ref: collections.id < imports.collection_id
Ref: collections.id < records.collection_id
Ref: dwc_attributes.id < attribute_resolving_strategies.dwc_attribute_id
Ref: file_attachments.id < imports.attachment_id
Ref: file_attachments.id < record_images.attachment_id
Ref: imports.id < import_records.import_id
Ref: institutions.id < collections.institution_id
Ref: records.id < import_records.record_id
Ref: records.id < record_images.record_id