erDiagram
  file_attachments {
    uuid id PK
    varchar filename
    integer byte_size
    timestamp inserted_at
    timestamp updated_at
  }
  institutions {
    uuid id PK
    varchar name
    varchar code
    varchar address
    varchar zip_code
    varchar city
    varchar country
    varchar mail
    varchar tel
    varchar contact_person
    varchar grscicoll_reference
    timestamp inserted_at
    timestamp updated_at
  }
  change_events {
    uuid id PK
    varchar dwc_attribute
    varchar value
    varchar previous_value
    varchar category
    timestamp inserted_at
    timestamp updated_at
    uuid record_id
  }
  collections {
    uuid id PK
    integer items_to_digitize
    varchar owner
    varchar name
    varchar code
    varchar grscicoll_reference
    varchar description
    array import_mapping
    varchar type
    timestamp inserted_at
    timestamp updated_at
    uuid institution_id
  }
  encoded_records {
    varchar mts_material_sample_type
    varchar mte_material_entity_id
    varchar occ_occurrence_remarks
    varchar occ_associated_occurrences
    varchar occ_sex
    varchar occ_recorded_by
    varchar loc_municipality
    varchar loc_county
    varchar loc_city
    float loc_swiss_coordinates_y
    float loc_swiss_coordinates_x
    varchar loc_country_code
    varchar loc_georeference_remarks
    float loc_decimal_latitude
    float loc_decimal_longitude
    varchar loc_state_province
    varchar loc_verbatim_locality
    varchar loc_locality
    varchar loc_country
    varchar loc_continent
    varchar spp_life_stage
    varchar tax_taxon_rank
    varchar tax_accepted_name_usage_id
    varchar tax_accepted_name_usage
    integer tax_taxon_id_ch
    integer tax_taxon_id
    varchar tax_specific_epithet
    varchar tax_infraspecific_epithet
    varchar tax_scientific_name_authorship
    varchar tax_scientific_name
    varchar tax_genus
    varchar tax_family
    varchar tax_order
    varchar tax_class
    varchar tax_phylum
    varchar tax_kingdom
    varchar rrp_relationship_of_resource_id
    varchar rrp_relationship_of_resource
    date ref_relationship_established_date
    varchar ref_title
    varchar ref_source
    varchar ref_rights
    date ref_date
    varchar ref_creator
    varchar ref_bibliographic_citation
    varchar idf_type_status
    varchar idf_identified_by
    date idf_date_identified
    integer eve_end_of_period_year
    integer eve_end_of_period_month
    integer eve_end_of_period_day
    integer eve_year
    integer eve_month
    integer eve_day
    date eve_event_date
    date prs_date_of_birth
    varchar prs_last_name
    varchar prs_first_name
    varchar prs_contact_point
    uuid id PK
    jsonb extra_data
    timestamp inserted_at
    timestamp updated_at
    uuid record_id PK
  }
  record_encoding_results {
    uuid id PK
    jsonb input
    jsonb output
    varchar message
    varchar catalog
    varchar state
    timestamp inserted_at
    timestamp updated_at
    uuid record_id
  }
  exports {
    uuid id PK
    varchar name
    timestamp exported_at
    timestamp started_at
    timestamp finished_at
    jsonb mapping
    bytea records_query
    integer exported_count
    integer rows_count
    timestamp inserted_at
    timestamp updated_at
    uuid collection_id
    uuid attachment_id
    integer job_id
    varchar state
  }
  imports {
    uuid id PK
    array columns
    timestamp inserted_at
    timestamp updated_at
    timestamp started_at
    timestamp finished_at
    integer rows_count
    integer rows_valid_count
    integer rows_invalid_count
    integer rows_imported_count
    uuid collection_id
    uuid attachment_id
    integer job_id
    varchar state
  }
  import_records {
    uuid import_id PK
    uuid record_id PK
  }
  records {
    varchar mts_material_sample_type
    varchar mte_material_entity_id
    varchar occ_occurrence_remarks
    varchar occ_associated_occurrences
    varchar occ_sex
    varchar occ_recorded_by
    varchar loc_municipality
    varchar loc_county
    varchar loc_city
    float loc_swiss_coordinates_y
    float loc_swiss_coordinates_x
    varchar loc_country_code
    varchar loc_georeference_remarks
    float loc_decimal_latitude
    float loc_decimal_longitude
    varchar loc_state_province
    varchar loc_verbatim_locality
    varchar loc_locality
    varchar loc_country
    varchar loc_continent
    varchar spp_life_stage
    varchar tax_taxon_rank
    varchar tax_accepted_name_usage_id
    varchar tax_accepted_name_usage
    integer tax_taxon_id_ch
    integer tax_taxon_id
    varchar tax_specific_epithet
    varchar tax_infraspecific_epithet
    varchar tax_scientific_name_authorship
    varchar tax_scientific_name
    varchar tax_genus
    varchar tax_family
    varchar tax_order
    varchar tax_class
    varchar tax_phylum
    varchar tax_kingdom
    varchar rrp_relationship_of_resource_id
    varchar rrp_relationship_of_resource
    date ref_relationship_established_date
    varchar ref_title
    varchar ref_source
    varchar ref_rights
    date ref_date
    varchar ref_creator
    varchar ref_bibliographic_citation
    varchar idf_type_status
    varchar idf_identified_by
    date idf_date_identified
    integer eve_end_of_period_year
    integer eve_end_of_period_month
    integer eve_end_of_period_day
    integer eve_year
    integer eve_month
    integer eve_day
    date eve_event_date
    date prs_date_of_birth
    varchar prs_last_name
    varchar prs_first_name
    varchar prs_contact_point
    uuid id PK
    jsonb import_data
    jsonb extra_data
    jsonb errors
    timestamp inserted_at
    timestamp updated_at
    uuid collection_id
    integer encoder_job_id
    varchar state
  }
  record_images {
    uuid id PK
    integer size
    timestamp inserted_at
    timestamp updated_at
    uuid attachment_id
    uuid record_id
  }
  records_versions {
    uuid id PK
    varchar version_action_type
    varchar version_action_name
    varchar mte_material_entity_id
    varchar tax_scientific_name
    uuid version_source_id
    jsonb changes
    timestamp version_inserted_at
    timestamp version_updated_at
  }
  swiss_species {
    uuid id PK
    integer taxon_id_ch PK
    varchar accepted_name
    integer usage_key PK
    integer accepted_usage_key
    varchar scientific_name
    varchar rank
    timestamp inserted_at
    timestamp updated_at
  }
  schema_migrations {
    integer version PK
    timestamp inserted_at
  }
  oban_jobs {
    integer id PK
    varchar state
    varchar queue
    varchar worker
    jsonb args
    jsonb meta
    array tags
    array errors
    integer attempt
    array attempted_by
    integer max_attempts
    integer priority
    timestamp attempted_at
    timestamp cancelled_at
    timestamp completed_at
    timestamp discarded_at
    timestamp inserted_at
    timestamp scheduled_at
  }
  collections ||--|{ exports : ""
  collections ||--|{ imports : ""
  collections ||--|{ records : ""
  file_attachments ||--|{ exports : ""
  file_attachments ||--|{ imports : ""
  file_attachments ||--|{ record_images : ""
  imports ||--|{ import_records : ""
  institutions ||--|{ collections : ""
  oban_jobs ||--|{ exports : ""
  oban_jobs ||--|{ imports : ""
  oban_jobs ||--|{ records : ""
  records ||--|{ change_events : ""
  records ||--o| encoded_records : ""
  records ||--|{ import_records : ""
  records ||--|{ record_encoding_results : ""
  records ||--|{ record_images : ""
  records ||--|{ records_versions : ""
