

Table file_attachments {
  id uuid [pk]
  filename varchar
  byte_size integer
  inserted_at timestamp
  updated_at timestamp
}

Table institutions {
  id uuid [pk]
  name varchar
  code varchar
  address varchar
  zip_code varchar
  city varchar
  country varchar
  mail varchar
  tel varchar
  contact_person varchar
  grscicoll_reference varchar
  inserted_at timestamp
  updated_at timestamp
}

Table change_events {
  id uuid [pk]
  dwc_attribute varchar
  value varchar
  previous_value varchar
  category varchar
  inserted_at timestamp
  updated_at timestamp
  record_id uuid
}

Table collections {
  id uuid [pk]
  items_to_digitize integer
  owner varchar
  name varchar
  code varchar
  grscicoll_reference varchar
  description varchar
  import_mapping array
  type varchar
  inserted_at timestamp
  updated_at timestamp
  institution_id uuid
}

Table encoded_records {
  mts_material_sample_type varchar
  mte_material_entity_id varchar
  occ_occurrence_remarks varchar
  occ_associated_occurrences varchar
  occ_sex varchar
  occ_recorded_by varchar
  loc_municipality varchar
  loc_county varchar
  loc_city varchar
  loc_swiss_coordinates_y float
  loc_swiss_coordinates_x float
  loc_country_code varchar
  loc_georeference_remarks varchar
  loc_decimal_latitude float
  loc_decimal_longitude float
  loc_state_province varchar
  loc_verbatim_locality varchar
  loc_locality varchar
  loc_country varchar
  loc_continent varchar
  spp_life_stage varchar
  tax_taxon_rank varchar
  tax_accepted_name_usage_id varchar
  tax_accepted_name_usage varchar
  tax_taxon_id_ch integer
  tax_taxon_id integer
  tax_specific_epithet varchar
  tax_infraspecific_epithet varchar
  tax_scientific_name_authorship varchar
  tax_scientific_name varchar
  tax_genus varchar
  tax_family varchar
  tax_order varchar
  tax_class varchar
  tax_phylum varchar
  tax_kingdom varchar
  rrp_relationship_of_resource_id varchar
  rrp_relationship_of_resource varchar
  ref_relationship_established_date date
  ref_title varchar
  ref_source varchar
  ref_rights varchar
  ref_date date
  ref_creator varchar
  ref_bibliographic_citation varchar
  idf_type_status varchar
  idf_identified_by varchar
  idf_date_identified date
  eve_end_of_period_year integer
  eve_end_of_period_month integer
  eve_end_of_period_day integer
  eve_year integer
  eve_month integer
  eve_day integer
  eve_event_date date
  prs_date_of_birth date
  prs_last_name varchar
  prs_first_name varchar
  prs_contact_point varchar
  id uuid [pk]
  extra_data jsonb
  inserted_at timestamp
  updated_at timestamp
  record_id uuid [pk]
}

Table record_encoding_results {
  id uuid [pk]
  input jsonb
  output jsonb
  message varchar
  catalog varchar
  state varchar
  inserted_at timestamp
  updated_at timestamp
  record_id uuid
}

Table exports {
  id uuid [pk]
  name varchar
  exported_at timestamp
  started_at timestamp
  finished_at timestamp
  mapping jsonb
  records_query bytea
  exported_count integer
  rows_count integer
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
  attachment_id uuid
  job_id integer
  state varchar
}

Table imports {
  id uuid [pk]
  columns array
  inserted_at timestamp
  updated_at timestamp
  started_at timestamp
  finished_at timestamp
  rows_count integer
  rows_valid_count integer
  rows_invalid_count integer
  rows_imported_count integer
  collection_id uuid
  attachment_id uuid
  job_id integer
  state varchar
}

Table import_records {
  import_id uuid [pk]
  record_id uuid [pk]
}

Table records {
  mts_material_sample_type varchar
  mte_material_entity_id varchar
  occ_occurrence_remarks varchar
  occ_associated_occurrences varchar
  occ_sex varchar
  occ_recorded_by varchar
  loc_municipality varchar
  loc_county varchar
  loc_city varchar
  loc_swiss_coordinates_y float
  loc_swiss_coordinates_x float
  loc_country_code varchar
  loc_georeference_remarks varchar
  loc_decimal_latitude float
  loc_decimal_longitude float
  loc_state_province varchar
  loc_verbatim_locality varchar
  loc_locality varchar
  loc_country varchar
  loc_continent varchar
  spp_life_stage varchar
  tax_taxon_rank varchar
  tax_accepted_name_usage_id varchar
  tax_accepted_name_usage varchar
  tax_taxon_id_ch integer
  tax_taxon_id integer
  tax_specific_epithet varchar
  tax_infraspecific_epithet varchar
  tax_scientific_name_authorship varchar
  tax_scientific_name varchar
  tax_genus varchar
  tax_family varchar
  tax_order varchar
  tax_class varchar
  tax_phylum varchar
  tax_kingdom varchar
  rrp_relationship_of_resource_id varchar
  rrp_relationship_of_resource varchar
  ref_relationship_established_date date
  ref_title varchar
  ref_source varchar
  ref_rights varchar
  ref_date date
  ref_creator varchar
  ref_bibliographic_citation varchar
  idf_type_status varchar
  idf_identified_by varchar
  idf_date_identified date
  eve_end_of_period_year integer
  eve_end_of_period_month integer
  eve_end_of_period_day integer
  eve_year integer
  eve_month integer
  eve_day integer
  eve_event_date date
  prs_date_of_birth date
  prs_last_name varchar
  prs_first_name varchar
  prs_contact_point varchar
  id uuid [pk]
  import_data jsonb
  extra_data jsonb
  errors jsonb
  inserted_at timestamp
  updated_at timestamp
  collection_id uuid
  encoder_job_id integer
  state varchar
}

Table record_images {
  id uuid [pk]
  size integer
  inserted_at timestamp
  updated_at timestamp
  attachment_id uuid
  record_id uuid
}

Table records_versions {
  id uuid [pk]
  version_action_type varchar
  version_action_name varchar
  mte_material_entity_id varchar
  tax_scientific_name varchar
  version_source_id uuid
  changes jsonb
  version_inserted_at timestamp
  version_updated_at timestamp
}

Table swiss_species {
  id uuid [pk]
  taxon_id_ch integer [pk]
  accepted_name varchar
  usage_key integer [pk]
  accepted_usage_key integer
  scientific_name varchar
  rank varchar
  inserted_at timestamp
  updated_at timestamp
}

Table schema_migrations {
  version integer [pk]
  inserted_at timestamp
}

Table "" {
  autogenerated_id uuid [pk]
  value bytea
  name varchar [pk]
  type varchar
  mapped_to varchar
}

Table oban_jobs {
  id integer [pk]
  state varchar
  queue varchar
  worker varchar
  args jsonb
  meta jsonb
  tags array
  errors array
  attempt integer
  attempted_by array
  max_attempts integer
  priority integer
  attempted_at timestamp
  cancelled_at timestamp
  completed_at timestamp
  discarded_at timestamp
  inserted_at timestamp
  scheduled_at timestamp
}

Ref: collections.id < exports.collection_id
Ref: collections.id < imports.collection_id
Ref: collections.id < records.collection_id
Ref: file_attachments.id < exports.attachment_id
Ref: file_attachments.id < imports.attachment_id
Ref: file_attachments.id < record_images.attachment_id
Ref: imports.id < import_records.import_id
Ref: institutions.id < collections.institution_id
Ref: oban_jobs.id < exports.job_id
Ref: oban_jobs.id < imports.job_id
Ref: oban_jobs.id < records.encoder_job_id
Ref: records.id < change_events.record_id
Ref: records.id - encoded_records.record_id
Ref: records.id < import_records.record_id
Ref: records.id < record_encoding_results.record_id
Ref: records.id < record_images.record_id
Ref: records.id < records_versions.version_source_id