name: Check Semver Integrity

on:
  workflow_call:

jobs:
  validate-semver-order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check semver integrity
        uses: ./.github/actions/check-semver
