name: CI/CD

on:
  push:

  pull_request:
    branches:
      - main
      - develop

env:
  MIX_ENV: test
  DATABASE_URL: postgres://data_aggregator:secret@localhost:5432/data_aggregator

permissions:
  contents: read

jobs:
  check-semver-via-workflow:
    uses: ./.github/workflows/check-semver-integrity.yml

  test:
    name: Run tests
    runs-on: hetzner

    env:
      OPEN_CAGE_DATA_API_KEY: ${{ secrets.OPEN_CAGE_DATA_API_KEY }}
      GBIF_INSTALLATION_KEY: ${{ secrets.GBIF_INSTALLATION_KEY }}
      GBIF_ORGANIZATION_KEY: ${{ secrets.GBIF_ORGANIZATION_KEY }}
      GBIF_USER: ${{ secrets.GBIF_USER }}
      GBIF_PASSWORD: ${{ secrets.GBIF_PASSWORD }}

    services:
      postgres:
        image: postgres:17-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: data_aggregator
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Elixir
      #   uses: erlef/setup-beam@v1
      #   with:
      #     version-file: .tool-versions
      #     version-type: strict

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v4.4.0
      #   with:
      #     node-version-file: .tool-versions
      #     cache: npm
      #     cache-dependency-path: assets/package-lock.json

      # - name: Restore cache
      #   id: cache
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: |
      #       deps
      #       _build
      #       priv/plts
      #     key: ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-
      #       ${{ runner.os }}-mix-

      # - run: mix deps.clean --all
      # - run: mix deps.get
      # - run: mix compile
      # - run: rm -rf priv/plts
      # - run: mix dialyzer --plt

      # - name: Save cache
      #   uses: actions/cache/save@v4
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   with:
      #     path: |
      #       deps
      #       _build
      #       priv/plts
      #     key: ${{ runner.os }}-mix-${{ hashFiles('.tool-versions') }}-${{ hashFiles('mix.lock') }}

      # - run: mix assets.setup
      # - run: mix assets.build
      # - run: mix compile --warnings-as-errors
      # - run: mix lint
      # - run: mix test

      # - name: Test Summary
      #   uses: test-summary/action@v2
      #   with:
      #     paths: test/reports/test-junit-report.xml
      #   if: always()

  build:
    permissions:
      contents: write
      pull-requests: write
    name: Build Docker image
    needs: test
    runs-on: hetzner
    if: github.repository == 'zebbra/data_aggregator'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]

      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/zebbra/data_aggregator
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to quay.io
        if: github.ref == 'refs/heads/develop' || github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      # - name: Build and push image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: ${{ github.ref == 'refs/heads/develop' || github.ref_type == 'tag' }}
      #     load: true
      #     platforms: linux/amd64
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     build-args: |
      #       OTP_VERSION=${{ steps.versions.outputs.erlang }}
      #       ELIXIR_VERSION=${{ steps.versions.outputs.elixir }}
      #       APP_VERSION=${{ github.ref_type == 'tag' && github.ref_name || '0.0.42' }}
      - name: Get token for gh app Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_RUNNER_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_RUNNER_APPLICATION_PRIVATE_KEY }}
      - name: Update Helm chart version and appVersion
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          VERSION=${GITHUB_REF_NAME}

          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Updating version and appVersion to $VERSION"

            git fetch origin develop:develop
            git checkout develop
            git pull origin develop

            perl -i -pe "s/^appVersion: .*/appVersion: \"$VERSION\"/" helm/charts/aggregator/Chart.yaml
            perl -i -pe "s/^version: .*/version: $VERSION/" helm/charts/aggregator/Chart.yaml

            git config --local user.email "ci-bot@zebbra.ch"
            git config --local user.name "ci_bot"

            git add helm/charts/aggregator/Chart.yaml
            git commit -m "Update Helm chart version and appVersion to $VERSION"

            git push origin develop

            echo "Pushed Helm chart updates to develop branch"
          else
            echo "No valid version tag $VERSION, must be of format 1.0.42. Helm Chart will not be updated."
          fi
